use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Acmp",
        extends: None,
        description: Some("ACMP peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "inputctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Inputctrl"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "syncbusy",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Syncbusy"),
                }),
            },
            BlockItem {
                name: "en_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "cfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "ctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "inputctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Inputctrl"),
                }),
            },
            BlockItem {
                name: "inputctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Inputctrl"),
                }),
            },
            BlockItem {
                name: "inputctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Inputctrl"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4124,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8220,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12316,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "bias",
                    description: Some("Bias Configuration."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hyst",
                    description: Some("Hysteresis mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Hyst"),
                },
                Field {
                    name: "inputrange",
                    description: Some("Input Range."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Inputrange"),
                },
                Field {
                    name: "accuracy",
                    description: Some("ACMP accuracy mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Accuracy"),
                },
            ],
        },
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "notrdyval",
                    description: Some("Not Ready Value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Notrdyval"),
                },
                Field {
                    name: "gpioinv",
                    description: Some("Comparator GPIO Output Invert."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Module enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disabling",
                    description: Some("Disablement busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rise",
                    description: Some("Rising edge interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fall",
                    description: Some("Falling edge interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "acmprdy",
                    description: Some("ACMP ready interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "inputconflict",
                    description: Some("Input conflict interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "portallocerr",
                    description: Some("Port allocation error interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rise",
                    description: Some("Rising Edge Triggered Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fall",
                    description: Some("Falling Edge Triggered Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "acmprdy",
                    description: Some("ACMP ready Interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "inputconflict",
                    description: Some("Input conflict."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "portallocerr",
                    description: Some("Port allocation error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Inputctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "possel",
                    description: Some("Positive Input Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 8,
                    array: None,
                    enumm: Some("Possel"),
                },
                Field {
                    name: "negsel",
                    description: Some("Negative Input Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 8,
                    array: None,
                    enumm: Some("Negsel"),
                },
                Field {
                    name: "vrefdiv",
                    description: Some("VREF division."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "csressel",
                    description: Some("Capacitive Sense Mode Internal Resistor."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Csressel"),
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP version ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "acmpout",
                    description: Some("Analog Comparator Output."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "acmprdy",
                    description: Some("Analog Comparator Ready."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "inputconflict",
                    description: Some("INPUT conflict."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "portallocerr",
                    description: Some("Port allocation error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Swrst",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "swrst",
                    description: Some("Software reset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "resetting",
                    description: Some("Software reset busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Syncbusy",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "inputctrl",
                description: Some("Syncbusy for INPUTCTRL."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[
        Enum {
            name: "Accuracy",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "High",
                    description: Some("ACMP operates in high-accuracy mode but consumes more current."),
                    value: 1,
                },
                EnumVariant {
                    name: "Low",
                    description: Some("ACMP operates in low-accuracy mode but consumes less current."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Csressel",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Res0",
                    description: Some("Internal capacitive sense resistor value 0."),
                    value: 0,
                },
                EnumVariant {
                    name: "Res1",
                    description: Some("Internal capacitive sense resistor value 1."),
                    value: 1,
                },
                EnumVariant {
                    name: "Res2",
                    description: Some("Internal capacitive sense resistor value 2."),
                    value: 2,
                },
                EnumVariant {
                    name: "Res3",
                    description: Some("Internal capacitive sense resistor value 3."),
                    value: 3,
                },
                EnumVariant {
                    name: "Res4",
                    description: Some("Internal capacitive sense resistor value 4."),
                    value: 4,
                },
                EnumVariant {
                    name: "Res5",
                    description: Some("Internal capacitive sense resistor value 5."),
                    value: 5,
                },
                EnumVariant {
                    name: "Res6",
                    description: Some("Internal capacitive sense resistor value 6."),
                    value: 6,
                },
            ],
        },
        Enum {
            name: "Hyst",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Disabled",
                    description: Some("Hysteresis disabled."),
                    value: 0,
                },
                EnumVariant {
                    name: "Neg10mv",
                    description: Some("10mV hysteresis on negative edge transitions."),
                    value: 8,
                },
                EnumVariant {
                    name: "Neg20mv",
                    description: Some("20mV hysteresis on negative edge transitions."),
                    value: 9,
                },
                EnumVariant {
                    name: "Neg30mv",
                    description: Some("30mV hysteresis on negative edge transitions."),
                    value: 10,
                },
                EnumVariant {
                    name: "Pos10mv",
                    description: Some("10mV hysteresis on positive edge transitions."),
                    value: 4,
                },
                EnumVariant {
                    name: "Pos20mv",
                    description: Some("20mV hysteresis on positive edge transitions."),
                    value: 5,
                },
                EnumVariant {
                    name: "Pos30mv",
                    description: Some("30mV hysteresis on positive edge transitions."),
                    value: 6,
                },
                EnumVariant {
                    name: "Sym10mv",
                    description: Some("10mV symmetrical hysteresis."),
                    value: 1,
                },
                EnumVariant {
                    name: "Sym20mv",
                    description: Some("20mV symmetrical hysteresis."),
                    value: 2,
                },
                EnumVariant {
                    name: "Sym30mv",
                    description: Some("30mV symmetrical hysteresis."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Inputrange",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Full",
                    description: Some("Use this setting when the input to the comparator core can be from 0 to AVDD."),
                    value: 0,
                },
                EnumVariant {
                    name: "Reduced",
                    description: Some(
                        "It is recommended to use this setting when the input to the comparator core will always be less than AVDD-0.7V.",
                    ),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Negsel",
            description: None,
            bit_size: 8,
            variants: &[
                EnumVariant {
                    name: "Capsense",
                    description: Some("Deprecated capacitive sensing feature, not recommended for new designs."),
                    value: 48,
                },
                EnumVariant {
                    name: "Pa0",
                    description: Some("Port A, Pin0."),
                    value: 128,
                },
                EnumVariant {
                    name: "Pa1",
                    description: Some("Port A, Pin1."),
                    value: 129,
                },
                EnumVariant {
                    name: "Pa10",
                    description: Some("Port A, Pin10."),
                    value: 138,
                },
                EnumVariant {
                    name: "Pa11",
                    description: Some("Port A, Pin11."),
                    value: 139,
                },
                EnumVariant {
                    name: "Pa12",
                    description: Some("Port A, Pin12."),
                    value: 140,
                },
                EnumVariant {
                    name: "Pa13",
                    description: Some("Port A, Pin13."),
                    value: 141,
                },
                EnumVariant {
                    name: "Pa14",
                    description: Some("Port A, Pin14."),
                    value: 142,
                },
                EnumVariant {
                    name: "Pa15",
                    description: Some("Port A, Pin15."),
                    value: 143,
                },
                EnumVariant {
                    name: "Pa2",
                    description: Some("Port A, Pin2."),
                    value: 130,
                },
                EnumVariant {
                    name: "Pa3",
                    description: Some("Port A, Pin3."),
                    value: 131,
                },
                EnumVariant {
                    name: "Pa4",
                    description: Some("Port A, Pin4."),
                    value: 132,
                },
                EnumVariant {
                    name: "Pa5",
                    description: Some("Port A, Pin5."),
                    value: 133,
                },
                EnumVariant {
                    name: "Pa6",
                    description: Some("Port A, Pin6."),
                    value: 134,
                },
                EnumVariant {
                    name: "Pa7",
                    description: Some("Port A, Pin7."),
                    value: 135,
                },
                EnumVariant {
                    name: "Pa8",
                    description: Some("Port A, Pin8."),
                    value: 136,
                },
                EnumVariant {
                    name: "Pa9",
                    description: Some("Port A, Pin9."),
                    value: 137,
                },
                EnumVariant {
                    name: "Pb0",
                    description: Some("Port B, Pin0."),
                    value: 144,
                },
                EnumVariant {
                    name: "Pb1",
                    description: Some("Port B, Pin1."),
                    value: 145,
                },
                EnumVariant {
                    name: "Pb10",
                    description: Some("Port B, Pin10."),
                    value: 154,
                },
                EnumVariant {
                    name: "Pb11",
                    description: Some("Port B, Pin11."),
                    value: 155,
                },
                EnumVariant {
                    name: "Pb12",
                    description: Some("Port B, Pin12."),
                    value: 156,
                },
                EnumVariant {
                    name: "Pb13",
                    description: Some("Port B, Pin13."),
                    value: 157,
                },
                EnumVariant {
                    name: "Pb14",
                    description: Some("Port B, Pin14."),
                    value: 158,
                },
                EnumVariant {
                    name: "Pb15",
                    description: Some("Port B, Pin15."),
                    value: 159,
                },
                EnumVariant {
                    name: "Pb2",
                    description: Some("Port B, Pin2."),
                    value: 146,
                },
                EnumVariant {
                    name: "Pb3",
                    description: Some("Port B, Pin3."),
                    value: 147,
                },
                EnumVariant {
                    name: "Pb4",
                    description: Some("Port B, Pin4."),
                    value: 148,
                },
                EnumVariant {
                    name: "Pb5",
                    description: Some("Port B, Pin5."),
                    value: 149,
                },
                EnumVariant {
                    name: "Pb6",
                    description: Some("Port B, Pin6."),
                    value: 150,
                },
                EnumVariant {
                    name: "Pb7",
                    description: Some("Port B, Pin7."),
                    value: 151,
                },
                EnumVariant {
                    name: "Pb8",
                    description: Some("Port B, Pin8."),
                    value: 152,
                },
                EnumVariant {
                    name: "Pb9",
                    description: Some("Port B, Pin9."),
                    value: 153,
                },
                EnumVariant {
                    name: "Pc0",
                    description: Some("Port C, Pin0."),
                    value: 160,
                },
                EnumVariant {
                    name: "Pc1",
                    description: Some("Port C, Pin1."),
                    value: 161,
                },
                EnumVariant {
                    name: "Pc10",
                    description: Some("Port C, Pin10."),
                    value: 170,
                },
                EnumVariant {
                    name: "Pc11",
                    description: Some("Port C, Pin11."),
                    value: 171,
                },
                EnumVariant {
                    name: "Pc12",
                    description: Some("Port C, Pin12."),
                    value: 172,
                },
                EnumVariant {
                    name: "Pc13",
                    description: Some("Port C, Pin13."),
                    value: 173,
                },
                EnumVariant {
                    name: "Pc14",
                    description: Some("Port C, Pin14."),
                    value: 174,
                },
                EnumVariant {
                    name: "Pc15",
                    description: Some("Port C, Pin15."),
                    value: 175,
                },
                EnumVariant {
                    name: "Pc2",
                    description: Some("Port C, Pin2."),
                    value: 162,
                },
                EnumVariant {
                    name: "Pc3",
                    description: Some("Port C, Pin3."),
                    value: 163,
                },
                EnumVariant {
                    name: "Pc4",
                    description: Some("Port C, Pin4."),
                    value: 164,
                },
                EnumVariant {
                    name: "Pc5",
                    description: Some("Port C, Pin5."),
                    value: 165,
                },
                EnumVariant {
                    name: "Pc6",
                    description: Some("Port C, Pin6."),
                    value: 166,
                },
                EnumVariant {
                    name: "Pc7",
                    description: Some("Port C, Pin7."),
                    value: 167,
                },
                EnumVariant {
                    name: "Pc8",
                    description: Some("Port C, Pin8."),
                    value: 168,
                },
                EnumVariant {
                    name: "Pc9",
                    description: Some("Port C, Pin9."),
                    value: 169,
                },
                EnumVariant {
                    name: "Pd0",
                    description: Some("Port D, Pin0."),
                    value: 176,
                },
                EnumVariant {
                    name: "Pd1",
                    description: Some("Port D, Pin1."),
                    value: 177,
                },
                EnumVariant {
                    name: "Pd10",
                    description: Some("Port D, Pin10."),
                    value: 186,
                },
                EnumVariant {
                    name: "Pd11",
                    description: Some("Port D, Pin11."),
                    value: 187,
                },
                EnumVariant {
                    name: "Pd12",
                    description: Some("Port D, Pin12."),
                    value: 188,
                },
                EnumVariant {
                    name: "Pd13",
                    description: Some("Port D, Pin13."),
                    value: 189,
                },
                EnumVariant {
                    name: "Pd14",
                    description: Some("Port D, Pin14."),
                    value: 190,
                },
                EnumVariant {
                    name: "Pd15",
                    description: Some("Port D, Pin15."),
                    value: 191,
                },
                EnumVariant {
                    name: "Pd2",
                    description: Some("Port D, Pin2."),
                    value: 178,
                },
                EnumVariant {
                    name: "Pd3",
                    description: Some("Port D, Pin3."),
                    value: 179,
                },
                EnumVariant {
                    name: "Pd4",
                    description: Some("Port D, Pin4."),
                    value: 180,
                },
                EnumVariant {
                    name: "Pd5",
                    description: Some("Port D, Pin5."),
                    value: 181,
                },
                EnumVariant {
                    name: "Pd6",
                    description: Some("Port D, Pin6."),
                    value: 182,
                },
                EnumVariant {
                    name: "Pd7",
                    description: Some("Port D, Pin7."),
                    value: 183,
                },
                EnumVariant {
                    name: "Pd8",
                    description: Some("Port D, Pin8."),
                    value: 184,
                },
                EnumVariant {
                    name: "Pd9",
                    description: Some("Port D, Pin9."),
                    value: 185,
                },
                EnumVariant {
                    name: "Vdacout0",
                    description: Some("VDAC0 channel 0 output."),
                    value: 64,
                },
                EnumVariant {
                    name: "Vdacout1",
                    description: Some("VDAC0 channel 1 output."),
                    value: 65,
                },
                EnumVariant {
                    name: "Vrefdiv1v25",
                    description: Some("Divided 1V25 reference."),
                    value: 18,
                },
                EnumVariant {
                    name: "Vrefdiv1v25lp",
                    description: Some("Low-power Divided 1V25 reference."),
                    value: 19,
                },
                EnumVariant {
                    name: "Vrefdiv2v5",
                    description: Some("Divided 2V5 reference."),
                    value: 20,
                },
                EnumVariant {
                    name: "Vrefdiv2v5lp",
                    description: Some("Low-power Divided 2V5 reference."),
                    value: 21,
                },
                EnumVariant {
                    name: "Vrefdivavdd",
                    description: Some("Divided AVDD."),
                    value: 16,
                },
                EnumVariant {
                    name: "Vrefdivavddlp",
                    description: Some("Low-Power Divided AVDD."),
                    value: 17,
                },
                EnumVariant {
                    name: "Vsense01div4",
                    description: Some("VSENSE0 divided by 4."),
                    value: 32,
                },
                EnumVariant {
                    name: "Vsense01div4lp",
                    description: Some("Low-power VSENSE0 divided by 4."),
                    value: 33,
                },
                EnumVariant {
                    name: "Vsense11div4",
                    description: Some("VSENSE1 divided by 4."),
                    value: 34,
                },
                EnumVariant {
                    name: "Vsense11div4lp",
                    description: Some("Low-power VSENSE1 divided by 4."),
                    value: 35,
                },
                EnumVariant {
                    name: "Vss",
                    description: Some("VSS."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Notrdyval",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "High",
                    description: Some("ACMP output is 1 when the ACMP is not ready."),
                    value: 1,
                },
                EnumVariant {
                    name: "Low",
                    description: Some("ACMP output is 0 when the ACMP is not ready."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Possel",
            description: None,
            bit_size: 8,
            variants: &[
                EnumVariant {
                    name: "Extpa",
                    description: Some("External interface, base is PA0."),
                    value: 80,
                },
                EnumVariant {
                    name: "Extpb",
                    description: Some("External interface, base is PB0."),
                    value: 81,
                },
                EnumVariant {
                    name: "Extpc",
                    description: Some("External interface, base is PC0."),
                    value: 82,
                },
                EnumVariant {
                    name: "Extpd",
                    description: Some("External interface, base is PD0."),
                    value: 83,
                },
                EnumVariant {
                    name: "Pa0",
                    description: Some("Port A, Pin0."),
                    value: 128,
                },
                EnumVariant {
                    name: "Pa1",
                    description: Some("Port A, Pin1."),
                    value: 129,
                },
                EnumVariant {
                    name: "Pa10",
                    description: Some("Port A, Pin10."),
                    value: 138,
                },
                EnumVariant {
                    name: "Pa11",
                    description: Some("Port A, Pin11."),
                    value: 139,
                },
                EnumVariant {
                    name: "Pa12",
                    description: Some("Port A, Pin12."),
                    value: 140,
                },
                EnumVariant {
                    name: "Pa13",
                    description: Some("Port A, Pin13."),
                    value: 141,
                },
                EnumVariant {
                    name: "Pa14",
                    description: Some("Port A, Pin14."),
                    value: 142,
                },
                EnumVariant {
                    name: "Pa15",
                    description: Some("Port A, Pin15."),
                    value: 143,
                },
                EnumVariant {
                    name: "Pa2",
                    description: Some("Port A, Pin2."),
                    value: 130,
                },
                EnumVariant {
                    name: "Pa3",
                    description: Some("Port A, Pin3."),
                    value: 131,
                },
                EnumVariant {
                    name: "Pa4",
                    description: Some("Port A, Pin4."),
                    value: 132,
                },
                EnumVariant {
                    name: "Pa5",
                    description: Some("Port A, Pin5."),
                    value: 133,
                },
                EnumVariant {
                    name: "Pa6",
                    description: Some("Port A, Pin6."),
                    value: 134,
                },
                EnumVariant {
                    name: "Pa7",
                    description: Some("Port A, Pin7."),
                    value: 135,
                },
                EnumVariant {
                    name: "Pa8",
                    description: Some("Port A, Pin8."),
                    value: 136,
                },
                EnumVariant {
                    name: "Pa9",
                    description: Some("Port A, Pin9."),
                    value: 137,
                },
                EnumVariant {
                    name: "Pb0",
                    description: Some("Port B, Pin0."),
                    value: 144,
                },
                EnumVariant {
                    name: "Pb1",
                    description: Some("Port B, Pin1."),
                    value: 145,
                },
                EnumVariant {
                    name: "Pb10",
                    description: Some("Port B, Pin10."),
                    value: 154,
                },
                EnumVariant {
                    name: "Pb11",
                    description: Some("Port B, Pin11."),
                    value: 155,
                },
                EnumVariant {
                    name: "Pb12",
                    description: Some("Port B, Pin12."),
                    value: 156,
                },
                EnumVariant {
                    name: "Pb13",
                    description: Some("Port B, Pin13."),
                    value: 157,
                },
                EnumVariant {
                    name: "Pb14",
                    description: Some("Port B, Pin14."),
                    value: 158,
                },
                EnumVariant {
                    name: "Pb15",
                    description: Some("Port B, Pin15."),
                    value: 159,
                },
                EnumVariant {
                    name: "Pb2",
                    description: Some("Port B, Pin2."),
                    value: 146,
                },
                EnumVariant {
                    name: "Pb3",
                    description: Some("Port B, Pin3."),
                    value: 147,
                },
                EnumVariant {
                    name: "Pb4",
                    description: Some("Port B, Pin4."),
                    value: 148,
                },
                EnumVariant {
                    name: "Pb5",
                    description: Some("Port B, Pin5."),
                    value: 149,
                },
                EnumVariant {
                    name: "Pb6",
                    description: Some("Port B, Pin6."),
                    value: 150,
                },
                EnumVariant {
                    name: "Pb7",
                    description: Some("Port B, Pin7."),
                    value: 151,
                },
                EnumVariant {
                    name: "Pb8",
                    description: Some("Port B, Pin8."),
                    value: 152,
                },
                EnumVariant {
                    name: "Pb9",
                    description: Some("Port B, Pin9."),
                    value: 153,
                },
                EnumVariant {
                    name: "Pc0",
                    description: Some("Port C, Pin0."),
                    value: 160,
                },
                EnumVariant {
                    name: "Pc1",
                    description: Some("Port C, Pin1."),
                    value: 161,
                },
                EnumVariant {
                    name: "Pc10",
                    description: Some("Port C, Pin10."),
                    value: 170,
                },
                EnumVariant {
                    name: "Pc11",
                    description: Some("Port C, Pin11."),
                    value: 171,
                },
                EnumVariant {
                    name: "Pc12",
                    description: Some("Port C, Pin12."),
                    value: 172,
                },
                EnumVariant {
                    name: "Pc13",
                    description: Some("Port C, Pin13."),
                    value: 173,
                },
                EnumVariant {
                    name: "Pc14",
                    description: Some("Port C, Pin14."),
                    value: 174,
                },
                EnumVariant {
                    name: "Pc15",
                    description: Some("Port C, Pin15."),
                    value: 175,
                },
                EnumVariant {
                    name: "Pc2",
                    description: Some("Port C, Pin2."),
                    value: 162,
                },
                EnumVariant {
                    name: "Pc3",
                    description: Some("Port C, Pin3."),
                    value: 163,
                },
                EnumVariant {
                    name: "Pc4",
                    description: Some("Port C, Pin4."),
                    value: 164,
                },
                EnumVariant {
                    name: "Pc5",
                    description: Some("Port C, Pin5."),
                    value: 165,
                },
                EnumVariant {
                    name: "Pc6",
                    description: Some("Port C, Pin6."),
                    value: 166,
                },
                EnumVariant {
                    name: "Pc7",
                    description: Some("Port C, Pin7."),
                    value: 167,
                },
                EnumVariant {
                    name: "Pc8",
                    description: Some("Port C, Pin8."),
                    value: 168,
                },
                EnumVariant {
                    name: "Pc9",
                    description: Some("Port C, Pin9."),
                    value: 169,
                },
                EnumVariant {
                    name: "Pd0",
                    description: Some("Port D, Pin0."),
                    value: 176,
                },
                EnumVariant {
                    name: "Pd1",
                    description: Some("Port D, Pin1."),
                    value: 177,
                },
                EnumVariant {
                    name: "Pd10",
                    description: Some("Port D, Pin10."),
                    value: 186,
                },
                EnumVariant {
                    name: "Pd11",
                    description: Some("Port D, Pin11."),
                    value: 187,
                },
                EnumVariant {
                    name: "Pd12",
                    description: Some("Port D, Pin12."),
                    value: 188,
                },
                EnumVariant {
                    name: "Pd13",
                    description: Some("Port D, Pin13."),
                    value: 189,
                },
                EnumVariant {
                    name: "Pd14",
                    description: Some("Port D, Pin14."),
                    value: 190,
                },
                EnumVariant {
                    name: "Pd15",
                    description: Some("Port D, Pin15."),
                    value: 191,
                },
                EnumVariant {
                    name: "Pd2",
                    description: Some("Port D, Pin2."),
                    value: 178,
                },
                EnumVariant {
                    name: "Pd3",
                    description: Some("Port D, Pin3."),
                    value: 179,
                },
                EnumVariant {
                    name: "Pd4",
                    description: Some("Port D, Pin4."),
                    value: 180,
                },
                EnumVariant {
                    name: "Pd5",
                    description: Some("Port D, Pin5."),
                    value: 181,
                },
                EnumVariant {
                    name: "Pd6",
                    description: Some("Port D, Pin6."),
                    value: 182,
                },
                EnumVariant {
                    name: "Pd7",
                    description: Some("Port D, Pin7."),
                    value: 183,
                },
                EnumVariant {
                    name: "Pd8",
                    description: Some("Port D, Pin8."),
                    value: 184,
                },
                EnumVariant {
                    name: "Pd9",
                    description: Some("Port D, Pin9."),
                    value: 185,
                },
                EnumVariant {
                    name: "Vdacout0",
                    description: Some("VDAC0 channel 0 output."),
                    value: 64,
                },
                EnumVariant {
                    name: "Vdacout1",
                    description: Some("VDAC0 channel 1 output."),
                    value: 65,
                },
                EnumVariant {
                    name: "Vrefdiv1v25",
                    description: Some("Divided 1V25 reference."),
                    value: 18,
                },
                EnumVariant {
                    name: "Vrefdiv1v25lp",
                    description: Some("Low-power Divided 1V25 reference."),
                    value: 19,
                },
                EnumVariant {
                    name: "Vrefdiv2v5",
                    description: Some("Divided 2V5 reference."),
                    value: 20,
                },
                EnumVariant {
                    name: "Vrefdiv2v5lp",
                    description: Some("Low-power Divided 2V5 reference."),
                    value: 21,
                },
                EnumVariant {
                    name: "Vrefdivavdd",
                    description: Some("Divided AVDD."),
                    value: 16,
                },
                EnumVariant {
                    name: "Vrefdivavddlp",
                    description: Some("Low-Power Divided AVDD."),
                    value: 17,
                },
                EnumVariant {
                    name: "Vsense01div4",
                    description: Some("VSENSE0 divided by 4."),
                    value: 32,
                },
                EnumVariant {
                    name: "Vsense01div4lp",
                    description: Some("Low-power VSENSE0 divided by 4."),
                    value: 33,
                },
                EnumVariant {
                    name: "Vsense11div4",
                    description: Some("VSENSE1 divided by 4."),
                    value: 34,
                },
                EnumVariant {
                    name: "Vsense11div4lp",
                    description: Some("Low-power VSENSE1 divided by 4."),
                    value: 35,
                },
                EnumVariant {
                    name: "Vss",
                    description: Some("VSS."),
                    value: 0,
                },
            ],
        },
    ],
};
