use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Amuxcp",
        extends: None,
        description: Some("AMUXCP peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("IPVERSION."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("Control."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("Status."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "test",
                description: Some("Test."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Test"),
                }),
            },
            BlockItem {
                name: "trim",
                description: Some("Trim."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Trim"),
                }),
            },
            BlockItem {
                name: "ctrl_set",
                description: Some("Control. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_clr",
                description: Some("Control. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_tgl",
                description: Some("Control. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "test_set",
                description: Some("Test. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Test"),
                }),
            },
            BlockItem {
                name: "test_clr",
                description: Some("Test. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Test"),
                }),
            },
            BlockItem {
                name: "test_tgl",
                description: Some("Test. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Test"),
                }),
            },
            BlockItem {
                name: "trim_set",
                description: Some("Trim. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Trim"),
                }),
            },
            BlockItem {
                name: "trim_clr",
                description: Some("Trim. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Trim"),
                }),
            },
            BlockItem {
                name: "trim_tgl",
                description: Some("Trim. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Trim"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("Control."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "forcehp",
                    description: Some("Force High Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcelp",
                    description: Some("Force Low Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcerun",
                    description: Some("Force run."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcestop",
                    description: Some("Force stop."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("IPVERSION."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IPVERSION."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("Status."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "run",
                    description: Some("running."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hicap",
                    description: Some("high cap."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Test",
            extends: None,
            description: Some("Test."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "syncclk",
                    description: Some("Sync Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syncmode",
                    description: Some("Sync Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcerequest",
                    description: Some("Force Request."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcehicap",
                    description: Some("Force high capacitance driver."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcelocap",
                    description: Some("Force low capacitance driver."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcebooston",
                    description: Some("Force Boost On."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forceboostoff",
                    description: Some("Force Boost Off."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "statusen",
                    description: Some("Enable write to status bits."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Trim",
            extends: None,
            description: Some("Trim."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "warmuptime",
                    description: Some("Warm up time."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Warmuptime"),
                },
                Field {
                    name: "floatvddcplo",
                    description: Some("Float VDDCP Low Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "floatvddcphi",
                    description: Some("Float VDDCP High Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bypassdiv2lo",
                    description: Some("Bypass Div2 Low Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bypassdiv2hi",
                    description: Some("Bypass Div2 High Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bump0p5xlo",
                    description: Some("Bump 0.5X Low Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bump0p5xhi",
                    description: Some("Bump 0.5X High Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bias2xlo",
                    description: Some("Bias 2x Low Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bias2xhi",
                    description: Some("Bias 2x High Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "voltagectrllo",
                    description: Some("Charge Pump Voltage Control Low Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "voltagectrlhi",
                    description: Some("Charge Pump Voltage Control High Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "biasctrllo",
                    description: Some("Bias Control Low Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "biasctrllocont",
                    description: Some("Bias Control Low Power Continuous."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "biasctrlhi",
                    description: Some("Bias Control High Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pumpcaplo",
                    description: Some("Pump Cap Low Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pumpcaphi",
                    description: Some("Pump Cap High Power."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[Enum {
        name: "Warmuptime",
        description: None,
        bit_size: 2,
        variants: &[
            EnumVariant {
                name: "Wucycles128",
                description: Some("Warm up cycle = 128; 6.4us @ 20 MHz."),
                value: 2,
            },
            EnumVariant {
                name: "Wucycles160",
                description: Some("Warm up cycle = 160; 8.0us @ 20 MHz."),
                value: 3,
            },
            EnumVariant {
                name: "Wucycles72",
                description: Some("Warm up cycle = 72; 3.6us @20 MHz."),
                value: 0,
            },
            EnumVariant {
                name: "Wucycles96",
                description: Some("Warm up cycle = 96; 4.8us @ 20 MHz."),
                value: 1,
            },
        ],
    }],
};
