use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Cmu",
        extends: None,
        description: Some("CMU peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "wdoglock",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Wdoglock"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "calcmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 80,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Calcmd"),
                }),
            },
            BlockItem {
                name: "calctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 84,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Calctrl"),
                }),
            },
            BlockItem {
                name: "calcnt",
                description: Some("No Description."),
                array: None,
                byte_offset: 88,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Calcnt"),
                }),
            },
            BlockItem {
                name: "clken0",
                description: Some("No Description."),
                array: None,
                byte_offset: 100,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Clken0"),
                }),
            },
            BlockItem {
                name: "clken1",
                description: Some("No Description."),
                array: None,
                byte_offset: 104,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Clken1"),
                }),
            },
            BlockItem {
                name: "sysclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 112,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Sysclkctrl"),
                }),
            },
            BlockItem {
                name: "traceclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 128,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Traceclkctrl"),
                }),
            },
            BlockItem {
                name: "exportclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 144,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Exportclkctrl"),
                }),
            },
            BlockItem {
                name: "dpllrefclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 256,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dpllrefclkctrl"),
                }),
            },
            BlockItem {
                name: "em01grpaclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 288,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Em01grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em01grpbclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 292,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Em01grpbclkctrl"),
                }),
            },
            BlockItem {
                name: "em23grpaclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 320,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Em23grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em4grpaclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 352,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Em4grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "iadcclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 384,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Iadcclkctrl"),
                }),
            },
            BlockItem {
                name: "wdog0clkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 512,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Wdog0clkctrl"),
                }),
            },
            BlockItem {
                name: "euart0clkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 544,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Euart0clkctrl"),
                }),
            },
            BlockItem {
                name: "rtccclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 576,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rtccclkctrl"),
                }),
            },
            BlockItem {
                name: "prortcclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 584,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Prortcclkctrl"),
                }),
            },
            BlockItem {
                name: "cryptoaccclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 608,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cryptoaccclkctrl"),
                }),
            },
            BlockItem {
                name: "radioclkctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 640,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Radioclkctrl"),
                }),
            },
            BlockItem {
                name: "lock_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "wdoglock_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Wdoglock"),
                }),
            },
            BlockItem {
                name: "wdoglock_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Wdoglock"),
                }),
            },
            BlockItem {
                name: "wdoglock_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Wdoglock"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4132,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8228,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12324,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "calcmd_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4176,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Calcmd"),
                }),
            },
            BlockItem {
                name: "calcmd_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8272,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Calcmd"),
                }),
            },
            BlockItem {
                name: "calcmd_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12368,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Calcmd"),
                }),
            },
            BlockItem {
                name: "calctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4180,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Calctrl"),
                }),
            },
            BlockItem {
                name: "calctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8276,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Calctrl"),
                }),
            },
            BlockItem {
                name: "calctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12372,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Calctrl"),
                }),
            },
            BlockItem {
                name: "clken0_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clken0"),
                }),
            },
            BlockItem {
                name: "clken0_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clken0"),
                }),
            },
            BlockItem {
                name: "clken0_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12388,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clken0"),
                }),
            },
            BlockItem {
                name: "clken1_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clken1"),
                }),
            },
            BlockItem {
                name: "clken1_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clken1"),
                }),
            },
            BlockItem {
                name: "clken1_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12392,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clken1"),
                }),
            },
            BlockItem {
                name: "sysclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Sysclkctrl"),
                }),
            },
            BlockItem {
                name: "sysclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Sysclkctrl"),
                }),
            },
            BlockItem {
                name: "sysclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12400,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Sysclkctrl"),
                }),
            },
            BlockItem {
                name: "traceclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Traceclkctrl"),
                }),
            },
            BlockItem {
                name: "traceclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Traceclkctrl"),
                }),
            },
            BlockItem {
                name: "traceclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12416,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Traceclkctrl"),
                }),
            },
            BlockItem {
                name: "exportclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4240,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Exportclkctrl"),
                }),
            },
            BlockItem {
                name: "exportclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8336,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Exportclkctrl"),
                }),
            },
            BlockItem {
                name: "exportclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12432,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Exportclkctrl"),
                }),
            },
            BlockItem {
                name: "dpllrefclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4352,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dpllrefclkctrl"),
                }),
            },
            BlockItem {
                name: "dpllrefclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8448,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dpllrefclkctrl"),
                }),
            },
            BlockItem {
                name: "dpllrefclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12544,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dpllrefclkctrl"),
                }),
            },
            BlockItem {
                name: "em01grpaclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4384,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em01grpaclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8480,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em01grpaclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12576,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em01grpbclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4388,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01grpbclkctrl"),
                }),
            },
            BlockItem {
                name: "em01grpbclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8484,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01grpbclkctrl"),
                }),
            },
            BlockItem {
                name: "em01grpbclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12580,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01grpbclkctrl"),
                }),
            },
            BlockItem {
                name: "em23grpaclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4416,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em23grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em23grpaclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8512,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em23grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em23grpaclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12608,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em23grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em4grpaclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4448,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em4grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em4grpaclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8544,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em4grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "em4grpaclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12640,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em4grpaclkctrl"),
                }),
            },
            BlockItem {
                name: "iadcclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4480,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iadcclkctrl"),
                }),
            },
            BlockItem {
                name: "iadcclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8576,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iadcclkctrl"),
                }),
            },
            BlockItem {
                name: "iadcclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12672,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Iadcclkctrl"),
                }),
            },
            BlockItem {
                name: "wdog0clkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4608,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Wdog0clkctrl"),
                }),
            },
            BlockItem {
                name: "wdog0clkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8704,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Wdog0clkctrl"),
                }),
            },
            BlockItem {
                name: "wdog0clkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12800,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Wdog0clkctrl"),
                }),
            },
            BlockItem {
                name: "euart0clkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4640,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Euart0clkctrl"),
                }),
            },
            BlockItem {
                name: "euart0clkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8736,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Euart0clkctrl"),
                }),
            },
            BlockItem {
                name: "euart0clkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12832,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Euart0clkctrl"),
                }),
            },
            BlockItem {
                name: "rtccclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4672,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rtccclkctrl"),
                }),
            },
            BlockItem {
                name: "rtccclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8768,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rtccclkctrl"),
                }),
            },
            BlockItem {
                name: "rtccclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12864,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rtccclkctrl"),
                }),
            },
            BlockItem {
                name: "prortcclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4680,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Prortcclkctrl"),
                }),
            },
            BlockItem {
                name: "prortcclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8776,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Prortcclkctrl"),
                }),
            },
            BlockItem {
                name: "prortcclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12872,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Prortcclkctrl"),
                }),
            },
            BlockItem {
                name: "cryptoaccclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4704,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cryptoaccclkctrl"),
                }),
            },
            BlockItem {
                name: "cryptoaccclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8800,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cryptoaccclkctrl"),
                }),
            },
            BlockItem {
                name: "cryptoaccclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12896,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cryptoaccclkctrl"),
                }),
            },
            BlockItem {
                name: "radioclkctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4736,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioclkctrl"),
                }),
            },
            BlockItem {
                name: "radioclkctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8832,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioclkctrl"),
                }),
            },
            BlockItem {
                name: "radioclkctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12928,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioclkctrl"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Calcmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "calstart",
                    description: Some("Calibration Start."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "calstop",
                    description: Some("Calibration Stop."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Calcnt",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "calcnt",
                description: Some("Calibration Result Counter Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 20,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Calctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "caltop",
                    description: Some("Calibration Counter Top Value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 20,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cont",
                    description: Some("Continuous Calibration."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "upsel",
                    description: Some("Calibration Up-counter Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Upsel"),
                },
                Field {
                    name: "downsel",
                    description: Some("Calibration Down-counter Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Downsel"),
                },
            ],
        },
        FieldSet {
            name: "Clken0",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ldma",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ldmaxbar",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "radioaes",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "gpcrc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer1",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer2",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer3",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "usart0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "usart1",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iadc0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "amuxcp0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "letimer0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wdog0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i2c0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i2c1",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syscfg",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dpll0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hfrco0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hfxo0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fsrco",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lfrco",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lfxo",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ulfrco",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "euart0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pdm",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "gpio",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prs",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "buram",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "burtc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rtcc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dcdc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Clken1",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "agc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "modem",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rfcrc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "protimer",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rac",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "synth",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rdscratchpad",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rdmailbox0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rdmailbox1",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prortc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ifadcdebug",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cryptoacc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rfsense",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "smu",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "icache0",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "msc",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer4",
                    description: Some("Enable Bus Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cryptoaccclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "pken",
                    description: Some("PK Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "aesen",
                    description: Some("AES Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Dpllrefclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("DpllrefclkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Em01grpaclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("Em01grpaclkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Em01grpbclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 3,
                array: None,
                enumm: Some("Em01grpbclkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Em23grpaclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("Em23grpaclkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Em4grpaclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("Em4grpaclkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Euart0clkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("Euart0clkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Exportclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "clkoutsel0",
                    description: Some("Clock Output Select 0."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Clkoutsel0"),
                },
                Field {
                    name: "clkoutsel1",
                    description: Some("Clock Output Select 1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Clkoutsel1"),
                },
                Field {
                    name: "clkoutsel2",
                    description: Some("Clock Output Select 2."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Clkoutsel2"),
                },
                Field {
                    name: "presc",
                    description: Some("EXPORTCLK Prescaler."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 5,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Iadcclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("IadcclkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "calrdy",
                    description: Some("Calibration Ready Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "calof",
                    description: Some("Calibration Overflow Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "calrdy",
                    description: Some("Calibration Ready Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "calof",
                    description: Some("Calibration Overflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP Version ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lockkey",
                description: Some("Configuration Lock Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("LockLockkey"),
            }],
        },
        FieldSet {
            name: "Prortcclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("PrortcclkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Radioclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dbgclk",
                    description: Some("Enable Clock for Debugger."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rtccclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("RtccclkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "calrdy",
                    description: Some("Calibration Ready."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wdoglock",
                    description: Some("Configuration Lock Status for WDOG."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lock",
                    description: Some("Configuration Lock Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Sysclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "clksel",
                    description: Some("Clock Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("SysclkctrlClksel"),
                },
                Field {
                    name: "pclkpresc",
                    description: Some("PCLK Prescaler."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Pclkpresc"),
                },
                Field {
                    name: "hclkpresc",
                    description: Some("HCLK Prescaler."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Hclkpresc"),
                },
                Field {
                    name: "rhclkpresc",
                    description: Some("Radio HCLK Prescaler."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Rhclkpresc"),
                },
            ],
        },
        FieldSet {
            name: "Traceclkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "presc",
                description: Some("TRACECLK Prescaler."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                bit_size: 2,
                array: None,
                enumm: Some("Presc"),
            }],
        },
        FieldSet {
            name: "Wdog0clkctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clksel",
                description: Some("Clock Select."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 3,
                array: None,
                enumm: Some("Wdog0clkctrlClksel"),
            }],
        },
        FieldSet {
            name: "Wdoglock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lockkey",
                description: Some("Configuration Lock Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("WdoglockLockkey"),
            }],
        },
    ],
    enums: &[
        Enum {
            name: "Clkoutsel0",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Disabled",
                    description: Some("CLKOUT0 is not clocked."),
                    value: 0,
                },
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking CLKOUT0."),
                    value: 8,
                },
                EnumVariant {
                    name: "Hclk",
                    description: Some("HCLK is clocking CLKOUT0."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hfexpclk",
                    description: Some("EXPORTCLK is clocking CLKOUT0."),
                    value: 2,
                },
                EnumVariant {
                    name: "Hfrcodpll",
                    description: Some("HFRCODPLL is clocking CLKOUT0."),
                    value: 6,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking CLKOUT0."),
                    value: 7,
                },
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking CLKOUT0."),
                    value: 4,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking CLKOUT0."),
                    value: 5,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking CLKOUT0."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Clkoutsel1",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Disabled",
                    description: Some("CLKOUT1 is not clocked."),
                    value: 0,
                },
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking CLKOUT1."),
                    value: 8,
                },
                EnumVariant {
                    name: "Hclk",
                    description: Some("HCLK is clocking CLKOUT1."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hfexpclk",
                    description: Some("EXPORTCLK is clocking CLKOUT1."),
                    value: 2,
                },
                EnumVariant {
                    name: "Hfrcodpll",
                    description: Some("HFRCODPLL is clocking CLKOUT1."),
                    value: 6,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking CLKOUT1."),
                    value: 7,
                },
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking CLKOUT1."),
                    value: 4,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking CLKOUT1."),
                    value: 5,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking CLKOUT1."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Clkoutsel2",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Disabled",
                    description: Some("CLKOUT2 is not clocked."),
                    value: 0,
                },
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking CLKOUT2."),
                    value: 8,
                },
                EnumVariant {
                    name: "Hclk",
                    description: Some("HCLK is clocking CLKOUT2."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hfexpclk",
                    description: Some("EXPORTCLK is clocking CLKOUT2."),
                    value: 2,
                },
                EnumVariant {
                    name: "Hfrcodpll",
                    description: Some("HFRCODPLL is clocking CLKOUT2."),
                    value: 6,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking CLKOUT2."),
                    value: 7,
                },
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking CLKOUT2."),
                    value: 4,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking CLKOUT2."),
                    value: 5,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking CLKOUT2."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Downsel",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Disabled",
                    description: Some("Down-counter is not clocked."),
                    value: 0,
                },
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking down-counter."),
                    value: 9,
                },
                EnumVariant {
                    name: "Hclk",
                    description: Some("HCLK is clocking down-counter."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hfrcodpll",
                    description: Some("HFRCODPLL is clocking down-counter."),
                    value: 5,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking down-counter."),
                    value: 3,
                },
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking down-counter."),
                    value: 10,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking down-counter."),
                    value: 4,
                },
                EnumVariant {
                    name: "Prs",
                    description: Some("PRS CMU_CALDN consumer is clocking down-counter."),
                    value: 2,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking down-counter."),
                    value: 11,
                },
            ],
        },
        Enum {
            name: "DpllrefclkctrlClksel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Clkin0",
                    description: Some("CLKIN0 is clocking DPLLREFCLK."),
                    value: 3,
                },
                EnumVariant {
                    name: "Disabled",
                    description: Some("DPLLREFCLK is not clocked."),
                    value: 0,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking DPLLREFCLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking DPLLREFCLK."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Em01grpaclkctrlClksel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking EM01GRPACLK."),
                    value: 3,
                },
                EnumVariant {
                    name: "Hfrcodpll",
                    description: Some("HFRCODPLL is clocking EM01GRPACLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking EM01GRPACLK."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Em01grpbclkctrlClksel",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Clkin0",
                    description: Some("CLKIN0 is clocking EM01GRPBCLK."),
                    value: 4,
                },
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking EM01GRPBCLK."),
                    value: 3,
                },
                EnumVariant {
                    name: "Hfrcodpll",
                    description: Some("HFRCODPLL is clocking EM01GRPBCLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hfrcodpllrt",
                    description: Some("HFRCODPLL (re-timed) is clocking EM01GRPBCLK."),
                    value: 5,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking EM01GRPBCLK."),
                    value: 2,
                },
                EnumVariant {
                    name: "Hfxort",
                    description: Some("HFXO (re-timed) is clocking EM01GRPBCLK."),
                    value: 6,
                },
            ],
        },
        Enum {
            name: "Em23grpaclkctrlClksel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking EM23GRPACLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking EM23GRPACLK."),
                    value: 2,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking EM23GRPACLK."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Em4grpaclkctrlClksel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking EM4GRPACLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking EM4GRPACLK."),
                    value: 2,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking EM4GRPACLK."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Euart0clkctrlClksel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Disabled",
                    description: Some("UART is not clocked."),
                    value: 0,
                },
                EnumVariant {
                    name: "Em01grpaclk",
                    description: Some("EM01GRPACLK is clocking UART."),
                    value: 1,
                },
                EnumVariant {
                    name: "Em23grpaclk",
                    description: Some("EM23GRPACLK is clocking UART."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Hclkpresc",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Div1",
                    description: Some("HCLK is SYSCLK divided by 1."),
                    value: 0,
                },
                EnumVariant {
                    name: "Div16",
                    description: Some("HCLK is SYSCLK divided by 16."),
                    value: 15,
                },
                EnumVariant {
                    name: "Div2",
                    description: Some("HCLK is SYSCLK divided by 2."),
                    value: 1,
                },
                EnumVariant {
                    name: "Div4",
                    description: Some("HCLK is SYSCLK divided by 4."),
                    value: 3,
                },
                EnumVariant {
                    name: "Div8",
                    description: Some("HCLK is SYSCLK divided by 8."),
                    value: 7,
                },
            ],
        },
        Enum {
            name: "IadcclkctrlClksel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Em01grpaclk",
                    description: Some("EM01GRPACLK is clocking IADCCLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking IADCCLK."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "LockLockkey",
            description: None,
            bit_size: 16,
            variants: &[EnumVariant {
                name: "Unlock",
                description: Some("Write this value to unlock."),
                value: 37879,
            }],
        },
        Enum {
            name: "Pclkpresc",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Div1",
                    description: Some("PCLK is HCLK divided by 1."),
                    value: 0,
                },
                EnumVariant {
                    name: "Div2",
                    description: Some("PCLK is HCLK divided by 2."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Presc",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Div1",
                    description: Some("TRACECLK is SYSCLK divided by 1."),
                    value: 0,
                },
                EnumVariant {
                    name: "Div2",
                    description: Some("TRACECLK is SYSCLK divided by 2."),
                    value: 1,
                },
                EnumVariant {
                    name: "Div4",
                    description: Some("TRACECLK is SYSCLK divided by 4."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "PrortcclkctrlClksel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking PRORTCCLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking PRORTCCLK."),
                    value: 2,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking PRORTCCLK."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Rhclkpresc",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Div1",
                    description: Some("Radio HCLK is SYSCLK divided by 1."),
                    value: 0,
                },
                EnumVariant {
                    name: "Div2",
                    description: Some("Radio HCLK is SYSCLK divided by 2."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "RtccclkctrlClksel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking RTCCCLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking RTCCCLK."),
                    value: 2,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking RTCCCLK."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "SysclkctrlClksel",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Clkin0",
                    description: Some("CLKIN0 is clocking SYSCLK."),
                    value: 4,
                },
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking SYSCLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hfrcodpll",
                    description: Some("HFRCODPLL is clocking SYSCLK."),
                    value: 2,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking SYSCLK."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Upsel",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Disabled",
                    description: Some("Up-counter is not clocked."),
                    value: 0,
                },
                EnumVariant {
                    name: "Fsrco",
                    description: Some("FSRCO is clocking up-counter."),
                    value: 8,
                },
                EnumVariant {
                    name: "Hfrcodpll",
                    description: Some("HFRCODPLL is clocking up-counter."),
                    value: 4,
                },
                EnumVariant {
                    name: "Hfxo",
                    description: Some("HFXO is clocking up-counter."),
                    value: 2,
                },
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking up-counter."),
                    value: 9,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking up-counter."),
                    value: 3,
                },
                EnumVariant {
                    name: "Prs",
                    description: Some("PRS CMU_CALUP consumer is clocking up-counter."),
                    value: 1,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking up-counter."),
                    value: 10,
                },
            ],
        },
        Enum {
            name: "Wdog0clkctrlClksel",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Hclkdiv1024",
                    description: Some("HCLKDIV1024 is clocking WDOG0CLK."),
                    value: 4,
                },
                EnumVariant {
                    name: "Lfrco",
                    description: Some("LFRCO is clocking WDOG0CLK."),
                    value: 1,
                },
                EnumVariant {
                    name: "Lfxo",
                    description: Some("LFXO is clocking WDOG0CLK."),
                    value: 2,
                },
                EnumVariant {
                    name: "Ulfrco",
                    description: Some("ULFRCO is clocking WDOG0CLK."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "WdoglockLockkey",
            description: None,
            bit_size: 16,
            variants: &[EnumVariant {
                name: "Unlock",
                description: Some("Write this value to unlock."),
                value: 37879,
            }],
        },
    ],
};
