use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "CryptoaccNsRngctrl",
        extends: None,
        description: Some("CRYPTOACC_NS_RNGCTRL peripheral."),
        items: &[
            BlockItem {
                name: "rngctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rngctrl"),
                }),
            },
            BlockItem {
                name: "fifolevel",
                description: Some(
                    "Number of 32 bits words of random available in the FIFO. Writing to this register clears the FIFO full interrupt.",
                ),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Fifolevel"),
                }),
            },
            BlockItem {
                name: "fifothresh",
                description: Some(
                    "FIFO level at which the rings are restarted when in the FIFOFull_Off state, expressed in number of 128bit blocks.",
                ),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Fifothresh"),
                }),
            },
            BlockItem {
                name: "fifodepth",
                description: Some("Maximum number of 32 bits words that can be stored in the FIFO: 2^g_fifodepth."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Fifodepth"),
                }),
            },
            BlockItem {
                name: "key0",
                description: Some(
                    "This set of registers bits form the 128-bit AES key used for conditioning function. The first byte (MSB of 128-bit word) is at address 0x0010, the second byte at address 0x0011...",
                ),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Key0"),
                }),
            },
            BlockItem {
                name: "key1",
                description: Some(
                    "This set of registers bits form the 128-bit AES key used for conditioning function. The first byte (MSB of 128-bit word) is at address 0x0010, the second byte at address 0x0011...",
                ),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Key1"),
                }),
            },
            BlockItem {
                name: "key2",
                description: Some(
                    "This set of registers bits form the 128-bit AES key used for conditioning function. The first byte (MSB of 128-bit word) is at address 0x0010, the second byte at address 0x0011...",
                ),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Key2"),
                }),
            },
            BlockItem {
                name: "key3",
                description: Some(
                    "This set of registers bits form the 128-bit AES key used for conditioning function. The first byte (MSB of 128-bit word) is at address 0x0010, the second byte at address 0x0011...",
                ),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Key3"),
                }),
            },
            BlockItem {
                name: "testdata",
                description: Some(
                    "This register is used to feed known data to the conditioning function or to the continuous tests. See manual.",
                ),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Testdata"),
                }),
            },
            BlockItem {
                name: "rngstatus",
                description: Some("No Description."),
                array: None,
                byte_offset: 48,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rngstatus"),
                }),
            },
            BlockItem {
                name: "initwaitval",
                description: Some("No Description."),
                array: None,
                byte_offset: 52,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Initwaitval"),
                }),
            },
            BlockItem {
                name: "swofftmrval",
                description: Some("Number of clk cycles to wait before stopping the rings after the FIFO is full."),
                array: None,
                byte_offset: 64,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Swofftmrval"),
                }),
            },
            BlockItem {
                name: "clkdiv",
                description: Some(
                    "Sample clock divider. The frequency at which the outputs of the rings are sampled is given by Fs = Fpclk/(ClkDiv + 1).",
                ),
                array: None,
                byte_offset: 68,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Clkdiv"),
                }),
            },
            BlockItem {
                name: "ais31conf0",
                description: Some("No Description."),
                array: None,
                byte_offset: 72,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ais31conf0"),
                }),
            },
            BlockItem {
                name: "ais31conf1",
                description: Some("No Description."),
                array: None,
                byte_offset: 76,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ais31conf1"),
                }),
            },
            BlockItem {
                name: "ais31conf2",
                description: Some("No Description."),
                array: None,
                byte_offset: 80,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ais31conf2"),
                }),
            },
            BlockItem {
                name: "ais31status",
                description: Some(
                    "This register is used to obtain diagnostic information about the AIS31 start-up and online tests when g_AIS31=True. Writing to this register clears all fields.",
                ),
                array: None,
                byte_offset: 84,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ais31status"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Ais31conf0",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "startupthres",
                    description: Some("Start-up Threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 15,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "onlinethresh",
                    description: Some("Online Threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 15,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ais31conf1",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "hexpectedvalue",
                    description: Some("Expected History Value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 15,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "onlinerepthresh",
                    description: Some("Online Repeat Threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 15,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ais31conf2",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "hmin",
                    description: Some("Minimum Allowed History Value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 15,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hmax",
                    description: Some("Maximum Allowed History Value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 15,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ais31status",
            extends: None,
            description: Some(
                "This register is used to obtain diagnostic information about the AIS31 start-up and online tests when g_AIS31=True. Writing to this register clears all fields.",
            ),
            bit_size: 32,
            fields: &[
                Field {
                    name: "numprelimalarms",
                    description: Some("Number of preliminary alarms."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prelimnoisealarmrng",
                    description: Some("Preliminary noise alarm RNG."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prelimnoisealarmrep",
                    description: Some("Preliminary noise alarm Rep."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Clkdiv",
            extends: None,
            description: Some(
                "Sample clock divider. The frequency at which the outputs of the rings are sampled is given by Fs = Fpclk/(ClkDiv + 1).",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "value",
                description: Some("Sample clock divider."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Fifodepth",
            extends: None,
            description: Some("Maximum number of 32 bits words that can be stored in the FIFO: 2^g_fifodepth."),
            bit_size: 32,
            fields: &[Field {
                name: "fifodepth",
                description: Some("FIFO Depth."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Fifolevel",
            extends: None,
            description: Some(
                "Number of 32 bits words of random available in the FIFO. Writing to this register clears the FIFO full interrupt.",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "fifolevel",
                description: Some("FIFO Level."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Fifothresh",
            extends: None,
            description: Some(
                "FIFO level at which the rings are restarted when in the FIFOFull_Off state, expressed in number of 128bit blocks.",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "fifothresh",
                description: Some("FIFO threshold level."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Initwaitval",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "initwaitval",
                description: Some("Wait counter value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Key0",
            extends: None,
            description: Some(
                "This set of registers bits form the 128-bit AES key used for conditioning function. The first byte (MSB of 128-bit word) is at address 0x0010, the second byte at address 0x0011...",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "key",
                description: Some("Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Key1",
            extends: None,
            description: Some(
                "This set of registers bits form the 128-bit AES key used for conditioning function. The first byte (MSB of 128-bit word) is at address 0x0010, the second byte at address 0x0011...",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "key",
                description: Some("Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Key2",
            extends: None,
            description: Some(
                "This set of registers bits form the 128-bit AES key used for conditioning function. The first byte (MSB of 128-bit word) is at address 0x0010, the second byte at address 0x0011...",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "key",
                description: Some("Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Key3",
            extends: None,
            description: Some(
                "This set of registers bits form the 128-bit AES key used for conditioning function. The first byte (MSB of 128-bit word) is at address 0x0010, the second byte at address 0x0011...",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "key",
                description: Some("Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Rngctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "enable",
                    description: Some("TRNG Module Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "testen",
                    description: Some("Test Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Testen"),
                },
                Field {
                    name: "condbypass",
                    description: Some("Conditioning Bypass."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Condbypass"),
                },
                Field {
                    name: "repcountien",
                    description: Some("IRQ enable for Repetition Count Test."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "apt64ien",
                    description: Some("IRQ enable for APT64IF."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "apt4096ien",
                    description: Some("IRQ enable for APT4096IF."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fullien",
                    description: Some("IRQ enable for FIFO full."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "softreset",
                    description: Some("Software Reset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Softreset"),
                },
                Field {
                    name: "preien",
                    description: Some("IRQ enable for AIS31 prelim. noise alarm."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "almien",
                    description: Some("IRQ enable for AIS31 noise alarm."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcerun",
                    description: Some("Oscillator Force Run."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Forcerun"),
                },
                Field {
                    name: "bypnist",
                    description: Some("NIST Start-up Test Bypass."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Bypnist"),
                },
                Field {
                    name: "bypais31",
                    description: Some("AIS31 Start-up Test Bypass."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Bypais31"),
                },
                Field {
                    name: "healthtestsel",
                    description: Some("Health test input select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Healthtestsel"),
                },
                Field {
                    name: "ais31testsel",
                    description: Some("AIS31 test input select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Ais31testsel"),
                },
                Field {
                    name: "nb128bitblocks",
                    description: Some("Number of 128b blocks in AES-CBCMAC."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fifowrstartup",
                    description: Some("Fifo Write Start Up."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rngstatus",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "testdatabusy",
                    description: Some("Test Data Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Testdatabusy"),
                },
                Field {
                    name: "state",
                    description: Some("State of the control FSM."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("State"),
                },
                Field {
                    name: "repcountif",
                    description: Some("Repetition Count Test interrupt status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "apt64if",
                    description: Some("64-sample window Adaptive Proportion IF."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "apt4096if",
                    description: Some("4096-sample window Adaptive Prop. IF."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fullif",
                    description: Some("FIFO full interrupt status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "preif",
                    description: Some("AIS31 Preliminary Noise Alarm IF."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "almif",
                    description: Some("AIS31 Noise Alarm interrupt status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Swofftmrval",
            extends: None,
            description: Some("Number of clk cycles to wait before stopping the rings after the FIFO is full."),
            bit_size: 32,
            fields: &[Field {
                name: "swofftmrval",
                description: Some("Switch Off Timer Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Testdata",
            extends: None,
            description: Some(
                "This register is used to feed known data to the conditioning function or to the continuous tests. See manual.",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "value",
                description: Some("Test data input to conditioning tests."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[
        Enum {
            name: "Ais31testsel",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "After",
                    description: Some("After conditioning."),
                    value: 1,
                },
                EnumVariant {
                    name: "Before",
                    description: Some("Before conditioning."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Bypais31",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Bypass",
                    description: Some("AIS31 startup test is bypassed."),
                    value: 1,
                },
                EnumVariant {
                    name: "Normal",
                    description: Some(
                        "AIS31 startup test is applied. No data will be written to the FIFO until the test passes.",
                    ),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Bypnist",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Bypass",
                    description: Some("NIST-800-90B startup test is bypassed."),
                    value: 1,
                },
                EnumVariant {
                    name: "Normal",
                    description: Some(
                        "NIST-800-90B startup test is applied. No data will be written to the FIFO until the test passes.",
                    ),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Condbypass",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Bypass",
                    description: Some("The conditioning function is bypassed."),
                    value: 1,
                },
                EnumVariant {
                    name: "Normal",
                    description: Some("The conditionig function is used."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Forcerun",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Normal",
                    description: Some("Oscillators will shut down when FIFO is full."),
                    value: 0,
                },
                EnumVariant {
                    name: "Run",
                    description: Some("Oscillators will continue to run even after FIFO is full."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Healthtestsel",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "After",
                    description: Some("After conditioning."),
                    value: 1,
                },
                EnumVariant {
                    name: "Before",
                    description: Some("Before conditioning."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Softreset",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Normal",
                    description: Some("Module not in reset."),
                    value: 0,
                },
                EnumVariant {
                    name: "Reset",
                    description: Some("The continuous test, the conditioning function and the FIFO are reset."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "State",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Error",
                    description: Some("ERROR State."),
                    value: 5,
                },
                EnumVariant {
                    name: "Fifofulloff",
                    description: Some("FIFOFULLOFF State."),
                    value: 3,
                },
                EnumVariant {
                    name: "Fifofullon",
                    description: Some("FIFOFULLON State."),
                    value: 2,
                },
                EnumVariant {
                    name: "Reset",
                    description: Some("RESET State."),
                    value: 0,
                },
                EnumVariant {
                    name: "Running",
                    description: Some("RUNNING State."),
                    value: 4,
                },
                EnumVariant {
                    name: "Startup",
                    description: Some("STARTUP State."),
                    value: 1,
                },
                EnumVariant {
                    name: "Unused6",
                    description: Some("UNUSED."),
                    value: 6,
                },
                EnumVariant {
                    name: "Unused7",
                    description: Some("UNUSED."),
                    value: 7,
                },
            ],
        },
        Enum {
            name: "Testdatabusy",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Busy",
                    description: Some("TESTDATA write is still being processed."),
                    value: 1,
                },
                EnumVariant {
                    name: "Idle",
                    description: Some("TESTDATA write is finished processing or no test in progress."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Testen",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Noise",
                    description: Some("Non-determinsitc random number generation."),
                    value: 0,
                },
                EnumVariant {
                    name: "Testdata",
                    description: Some("Pseudo-random number generation."),
                    value: 1,
                },
            ],
        },
    ],
};
