use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Cryptoacc",
        extends: None,
        description: Some("CRYPTOACC peripheral."),
        items: &[
            BlockItem {
                name: "fetchaddr",
                description: Some(
                    "Fetcher: Start address of data block. In direct mode, this register is written by the software. In scatter-gather mode, this register is updated after each processed descriptor.",
                ),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Fetchaddr"),
                }),
            },
            BlockItem {
                name: "fetchlen",
                description: Some(
                    "Fetcher: Length of data block. In direct mode, this register is written by the software. In scatter-gather mode, this register is not used.",
                ),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Fetchlen"),
                }),
            },
            BlockItem {
                name: "fetchtag",
                description: Some(
                    "Fetcher: User tag. In direct mode, this register is written by the software. In scatter-gather mode, this register is not used.",
                ),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Fetchtag"),
                }),
            },
            BlockItem {
                name: "pushaddr",
                description: Some(
                    "Pusher: Start address of data block (LSB). In direct mode, this register is written by the software. In scatter-gather mode, this register is updated after each processed descriptor.",
                ),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Pushaddr"),
                }),
            },
            BlockItem {
                name: "pushlen",
                description: Some(
                    "Pusher: Length of data block. In direct mode, this register is written by the software. In scatter-gather mode, this register is not used.",
                ),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Pushlen"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("Interrupt enable."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("Interrupt flag register."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("Writing a '1' clears the interrupt status. Writing a '0' has no effect."),
                array: None,
                byte_offset: 48,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("IfClr"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("Control register, called CONFIG in Barco datasheet."),
                array: None,
                byte_offset: 52,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("Command register for starting the fetcher and pusher."),
                array: None,
                byte_offset: 56,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("Status register."),
                array: None,
                byte_offset: 60,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "incl_ips_hw_cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 1024,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("InclIpsHwCfg"),
                }),
            },
            BlockItem {
                name: "ba411e_hw_cfg_1",
                description: Some("No Description."),
                array: None,
                byte_offset: 1028,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ba411eHwCfg1"),
                }),
            },
            BlockItem {
                name: "ba411e_hw_cfg_2",
                description: Some("No Description."),
                array: None,
                byte_offset: 1032,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ba411eHwCfg2"),
                }),
            },
            BlockItem {
                name: "ba413_hw_cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 1036,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ba413HwCfg"),
                }),
            },
            BlockItem {
                name: "ba418_hw_cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 1040,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ba418HwCfg"),
                }),
            },
            BlockItem {
                name: "ba419_hw_cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 1044,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ba419HwCfg"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Ba411eHwCfg1",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "g_aes_modes_poss",
                    description: Some("AES Modes Supported."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_cs",
                    description: Some("Generic g_CS value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_use_masking",
                    description: Some("Generic g_UseMasking value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_keysize",
                    description: Some("Generic g_Keysize value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ba411eHwCfg2",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "g_ctr_size",
                description: Some("Generic g_CtrSize value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ba413HwCfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "g_hash_mask_func",
                    description: Some("Generic g_HashMaskFunc value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 7,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_hash_padding",
                    description: Some("Generic g_HashPadding value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_hmac_enabled",
                    description: Some("Generic g_HMAC_enabled value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_hash_verify_digest",
                    description: Some("Generic g_HashVerifyDigest value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ba418HwCfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "g_sha3ctxt_en",
                description: Some("Generic g_Sha3CtxtEn value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ba419HwCfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "g_sm4modes_poss",
                description: Some("Generic g_SM4ModesPoss value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 7,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("Command register for starting the fetcher and pusher."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "startfetcher",
                    description: Some("Start fetch."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "startpusher",
                    description: Some("Start push."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("Control register, called CONFIG in Barco datasheet."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fetcherscattergather",
                    description: Some("Fetcher scatter/gather."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pusherscattergather",
                    description: Some("Pusher scatter/gather."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "stopfetcher",
                    description: Some("Stop fetcher."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "stoppusher",
                    description: Some("Stop pusher."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "swreset",
                    description: Some("Software reset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Fetchaddr",
            extends: None,
            description: Some(
                "Fetcher: Start address of data block. In direct mode, this register is written by the software. In scatter-gather mode, this register is updated after each processed descriptor.",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "addr",
                description: Some("Start address of data block."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Fetchlen",
            extends: None,
            description: Some(
                "Fetcher: Length of data block. In direct mode, this register is written by the software. In scatter-gather mode, this register is not used.",
            ),
            bit_size: 32,
            fields: &[
                Field {
                    name: "length",
                    description: Some("Length of data block."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 28,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "constaddr",
                    description: Some("Constant address."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "realign",
                    description: Some("Realign length."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Fetchtag",
            extends: None,
            description: Some(
                "Fetcher: User tag. In direct mode, this register is written by the software. In scatter-gather mode, this register is not used.",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "tag",
                description: Some("User tag."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("Interrupt enable."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fetcherendofblock",
                    description: Some("End of block interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fetcherstopped",
                    description: Some("Stopped interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fetchererror",
                    description: Some("Error interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pusherendofblock",
                    description: Some("End of block interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pusherstopped",
                    description: Some("Stopped interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pushererror",
                    description: Some("Error interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("Interrupt flag register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fetcherendofblock",
                    description: Some("End of block interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fetcherstopped",
                    description: Some("Stopped interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fetchererror",
                    description: Some("Error interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pusherendofblock",
                    description: Some("End of block interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pusherstopped",
                    description: Some("Stopped interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pushererror",
                    description: Some("Error interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "IfClr",
            extends: None,
            description: Some("Writing a '1' clears the interrupt status. Writing a '0' has no effect."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fetcherendofblock",
                    description: Some("End of block interrupt flag clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fetcherstopped",
                    description: Some("Stopped interrupt flag clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fetchererror",
                    description: Some("Error interrupt flag clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pusherendofblock",
                    description: Some("End of block interrupt flag clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pusherstopped",
                    description: Some("Stopped interrupt flag clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pushererror",
                    description: Some("Error interrupt flag clear."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "InclIpsHwCfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "g_include_aes",
                    description: Some("Generic g_IncludeAES value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_aesgcm",
                    description: Some("Generic g_IncludeAESGCM value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_aesxts",
                    description: Some("Generic g_IncludeAESXTS value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_des",
                    description: Some("Generic g_IncludeDES value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_hash",
                    description: Some("Generic g_IncludeHASH value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_chacha_poly",
                    description: Some("Generic g_IncludeChachaPoly value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_sha3",
                    description: Some("Generic g_IncludeSHA3 value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_zuc",
                    description: Some("Generic g_IncludeZUC value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_sm4",
                    description: Some("Generic g_IncludeSM4 value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_pke",
                    description: Some("Generic g_IncludePKE value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "g_include_ndrng",
                    description: Some("Generic g_IncludeNDRNG value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Pushaddr",
            extends: None,
            description: Some(
                "Pusher: Start address of data block (LSB). In direct mode, this register is written by the software. In scatter-gather mode, this register is updated after each processed descriptor.",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "addr",
                description: Some("Start address of data block."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Pushlen",
            extends: None,
            description: Some(
                "Pusher: Length of data block. In direct mode, this register is written by the software. In scatter-gather mode, this register is not used.",
            ),
            bit_size: 32,
            fields: &[
                Field {
                    name: "length",
                    description: Some("Start address of data block."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 28,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "constaddr",
                    description: Some("Constant address."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "realign",
                    description: Some("Realign length."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "discard",
                    description: Some("Discard data."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("Status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fetcherbsy",
                    description: Some("Fetcher busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pusherbsy",
                    description: Some("Pusher busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "notempty",
                    description: Some("Not empty flag from input FIFO (fetcher)."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "waiting",
                    description: Some("Pusher waiting for FIFO."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "softrstbsy",
                    description: Some("Software reset busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fifodatanum",
                    description: Some("Number of data in output FIFO."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[],
};
