use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Dcdc",
        extends: None,
        description: Some("DCDC peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("IPVERSION."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("Enable."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("Control."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "em01ctrl0",
                description: Some("EM01 Configurations."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Em01ctrl0"),
                }),
            },
            BlockItem {
                name: "em23ctrl0",
                description: Some("EM23 Configurations."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Em23ctrl0"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("Interrupt Flags."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("Interrupt Enable."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("DCDC Status Register."),
                array: None,
                byte_offset: 44,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("No Description."),
                array: None,
                byte_offset: 64,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lockstatus",
                description: Some("No Description."),
                array: None,
                byte_offset: 68,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Lockstatus"),
                }),
            },
            BlockItem {
                name: "en_set",
                description: Some("Enable. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_clr",
                description: Some("Enable. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_tgl",
                description: Some("Enable. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "ctrl_set",
                description: Some("Control. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_clr",
                description: Some("Control. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_tgl",
                description: Some("Control. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "em01ctrl0_set",
                description: Some("EM01 Configurations. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01ctrl0"),
                }),
            },
            BlockItem {
                name: "em01ctrl0_clr",
                description: Some("EM01 Configurations. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01ctrl0"),
                }),
            },
            BlockItem {
                name: "em01ctrl0_tgl",
                description: Some("EM01 Configurations. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em01ctrl0"),
                }),
            },
            BlockItem {
                name: "em23ctrl0_set",
                description: Some("EM23 Configurations. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em23ctrl0"),
                }),
            },
            BlockItem {
                name: "em23ctrl0_clr",
                description: Some("EM23 Configurations. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em23ctrl0"),
                }),
            },
            BlockItem {
                name: "em23ctrl0_tgl",
                description: Some("EM23 Configurations. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em23ctrl0"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("Interrupt Flags. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4132,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("Interrupt Flags. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8228,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("Interrupt Flags. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12324,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("Interrupt Enable. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4136,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("Interrupt Enable. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8232,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("Interrupt Enable. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12328,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "lock_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4160,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8256,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12352,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("Control."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mode",
                    description: Some("DCDC/Bypass Mode Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Mode"),
                },
                Field {
                    name: "dcmonlyen",
                    description: Some("DCDC DCM Only Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Dcmonlyen"),
                },
                Field {
                    name: "ipktmaxctrl",
                    description: Some("Peak Current Timeout Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Ipktmaxctrl"),
                },
            ],
        },
        FieldSet {
            name: "Em01ctrl0",
            extends: None,
            description: Some("EM01 Configurations."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ipkval",
                    description: Some("EM01 Peak Current Setting."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Em01ctrl0Ipkval"),
                },
                Field {
                    name: "drvspeed",
                    description: Some("EM01 Drive Speed Setting."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Em01ctrl0Drvspeed"),
                },
            ],
        },
        FieldSet {
            name: "Em23ctrl0",
            extends: None,
            description: Some("EM23 Configurations."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ipkval",
                    description: Some("EM23 Peak Current Setting."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Em23ctrl0Ipkval"),
                },
                Field {
                    name: "drvspeed",
                    description: Some("EM23 Drive Speed Setting."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Em23ctrl0Drvspeed"),
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("Enable."),
            bit_size: 32,
            fields: &[Field {
                name: "en",
                description: Some("Enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("Interrupt Enable."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "bypsw",
                    description: Some("Bypass Switch Enabled Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "warm",
                    description: Some("DCDC Warmup Time Done Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "running",
                    description: Some("DCDC Running Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vreginlow",
                    description: Some("VREGVDD below threshold Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vreginhigh",
                    description: Some("VREGVDD above threshold Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "regulation",
                    description: Some("DCDC in Regulation Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tmax",
                    description: Some("Ton_max Timeout Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "em4err",
                    description: Some("EM4 Entry Req Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("Interrupt Flags."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "bypsw",
                    description: Some("Bypass Switch Enabled."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "warm",
                    description: Some("DCDC Warmup Time Done."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "running",
                    description: Some("DCDC Running."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vreginlow",
                    description: Some("VREGVDD below threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vreginhigh",
                    description: Some("VREGVDD above threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "regulation",
                    description: Some("DCDC in regulation."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tmax",
                    description: Some("Ton_max Timeout Reached."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "em4err",
                    description: Some("EM4 Entry Request Error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("IPVERSION."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IPVERSION."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lockkey",
                description: Some("Configuration Lock Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("Lockkey"),
            }],
        },
        FieldSet {
            name: "Lockstatus",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lock",
                description: Some("Lock Status."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("DCDC Status Register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "bypsw",
                    description: Some("Bypass Switch is currently enabled."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "warm",
                    description: Some("DCDC Warmup Done."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "running",
                    description: Some("DCDC is running."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vregin",
                    description: Some("VREGVDD comparator status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bypcmpout",
                    description: Some("Bypass Comparator Output."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Dcmonlyen",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Dcmonlyen",
                    description: Some("DCM only mode for normal operation, this is the default setting."),
                    value: 1,
                },
                EnumVariant {
                    name: "Dualmode",
                    description: Some("Support higher load current at lower battery voltage by working in CCM mode."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Em01ctrl0Drvspeed",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "BestEfficiency",
                    description: Some("Not recommended for use (no benefit to this setting)."),
                    value: 3,
                },
                EnumVariant {
                    name: "BestEmi",
                    description: Some("Not recommended for use (no benefit to this setting)."),
                    value: 0,
                },
                EnumVariant {
                    name: "DefaultSetting",
                    description: Some("Recommended for use for best efficiency and low EMI."),
                    value: 1,
                },
                EnumVariant {
                    name: "Intermediate",
                    description: Some("Not recommended for use (no benefit to this setting)."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Em01ctrl0Ipkval",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Load36mA",
                    description: Some("Ipeak = 90mA, Iload = 36mA."),
                    value: 3,
                },
                EnumVariant {
                    name: "Load40mA",
                    description: Some("Ipeak = 100mA, Iload = 40mA."),
                    value: 4,
                },
                EnumVariant {
                    name: "Load44mA",
                    description: Some("Ipeak = 110mA, Iload = 44mA."),
                    value: 5,
                },
                EnumVariant {
                    name: "Load48mA",
                    description: Some("Ipeak = 120mA, Iload = 48mA."),
                    value: 6,
                },
                EnumVariant {
                    name: "Load52mA",
                    description: Some("Ipeak = 130mA, Iload = 52mA."),
                    value: 7,
                },
                EnumVariant {
                    name: "Load56mA",
                    description: Some("Ipeak = 140mA, Iload = 56mA."),
                    value: 8,
                },
                EnumVariant {
                    name: "Load60mA",
                    description: Some("Ipeak = 150mA, Iload = 60mA."),
                    value: 9,
                },
            ],
        },
        Enum {
            name: "Em23ctrl0Drvspeed",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "BestEfficiency",
                    description: Some("Not recommended for use (no benefit to this setting)."),
                    value: 3,
                },
                EnumVariant {
                    name: "BestEmi",
                    description: Some("Not recommended for use (no benefit to this setting)."),
                    value: 0,
                },
                EnumVariant {
                    name: "DefaultSetting",
                    description: Some("Recommended for use for best efficiency and low EMI."),
                    value: 1,
                },
                EnumVariant {
                    name: "Intermediate",
                    description: Some("Not recommended for use (no benefit to this setting)."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Em23ctrl0Ipkval",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Load10ma",
                    description: Some("Ipeak = 150mA, Iload = 10 mA."),
                    value: 9,
                },
                EnumVariant {
                    name: "Load5ma",
                    description: Some("Ipeak = 90mA, Iload = 5 mA."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Ipktmaxctrl",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Off",
                    description: Some("Ton_max disabled."),
                    value: 0,
                },
                EnumVariant {
                    name: "Tmax0p35us",
                    description: Some("0.35us."),
                    value: 1,
                },
                EnumVariant {
                    name: "Tmax0p63us",
                    description: Some("0.63us."),
                    value: 2,
                },
                EnumVariant {
                    name: "Tmax0p91us",
                    description: Some("0.91us."),
                    value: 3,
                },
                EnumVariant {
                    name: "Tmax1p19us",
                    description: Some("1.19us."),
                    value: 4,
                },
                EnumVariant {
                    name: "Tmax1p47us",
                    description: Some("1.47us."),
                    value: 5,
                },
                EnumVariant {
                    name: "Tmax1p75us",
                    description: Some("1.75us."),
                    value: 6,
                },
                EnumVariant {
                    name: "Tmax2p03us",
                    description: Some("2.03us."),
                    value: 7,
                },
            ],
        },
        Enum {
            name: "Lockkey",
            description: None,
            bit_size: 16,
            variants: &[EnumVariant {
                name: "Unlockkey",
                description: Some("Value to write to unlock."),
                value: 43981,
            }],
        },
        Enum {
            name: "Mode",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Bypass",
                    description: Some("DCDC is OFF, bypass switch is enabled."),
                    value: 0,
                },
                EnumVariant {
                    name: "Dcdcregulation",
                    description: Some("Request DCDC regulation, bypass switch disabled."),
                    value: 1,
                },
            ],
        },
    ],
};
