use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Etampdet",
        extends: None,
        description: Some("ETAMPDET peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cntmismatchmax",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cntmismatchmax"),
                }),
            },
            BlockItem {
                name: "chnlfiltwinsize",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Chnlfiltwinsize"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "syncbusy",
                description: Some("No Description."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Syncbusy"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "em4wuen",
                description: Some("No Description."),
                array: None,
                byte_offset: 44,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Em4wuen"),
                }),
            },
            BlockItem {
                name: "chnlseedval0",
                description: Some("No Description."),
                array: None,
                byte_offset: 48,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Chnlseedval0"),
                }),
            },
            BlockItem {
                name: "chnlseedval1",
                description: Some("No Description."),
                array: None,
                byte_offset: 52,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Chnlseedval1"),
                }),
            },
            BlockItem {
                name: "clkprescval",
                description: Some("Finial dividing factor = RIPPLECNTUPPER * CNTLOWER."),
                array: None,
                byte_offset: 56,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Clkprescval"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("No Description."),
                array: None,
                byte_offset: 72,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "en_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "cfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cntmismatchmax_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cntmismatchmax"),
                }),
            },
            BlockItem {
                name: "cntmismatchmax_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cntmismatchmax"),
                }),
            },
            BlockItem {
                name: "cntmismatchmax_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cntmismatchmax"),
                }),
            },
            BlockItem {
                name: "chnlfiltwinsize_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlfiltwinsize"),
                }),
            },
            BlockItem {
                name: "chnlfiltwinsize_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlfiltwinsize"),
                }),
            },
            BlockItem {
                name: "chnlfiltwinsize_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlfiltwinsize"),
                }),
            },
            BlockItem {
                name: "cmd_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4132,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8228,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12324,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "em4wuen_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4140,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em4wuen"),
                }),
            },
            BlockItem {
                name: "em4wuen_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8236,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em4wuen"),
                }),
            },
            BlockItem {
                name: "em4wuen_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12332,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Em4wuen"),
                }),
            },
            BlockItem {
                name: "chnlseedval0_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4144,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlseedval0"),
                }),
            },
            BlockItem {
                name: "chnlseedval0_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8240,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlseedval0"),
                }),
            },
            BlockItem {
                name: "chnlseedval0_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12336,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlseedval0"),
                }),
            },
            BlockItem {
                name: "chnlseedval1_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4148,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlseedval1"),
                }),
            },
            BlockItem {
                name: "chnlseedval1_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8244,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlseedval1"),
                }),
            },
            BlockItem {
                name: "chnlseedval1_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12340,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chnlseedval1"),
                }),
            },
            BlockItem {
                name: "clkprescval_set",
                description: Some("Finial dividing factor = RIPPLECNTUPPER * CNTLOWER. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4152,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clkprescval"),
                }),
            },
            BlockItem {
                name: "clkprescval_clr",
                description: Some("Finial dividing factor = RIPPLECNTUPPER * CNTLOWER. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8248,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clkprescval"),
                }),
            },
            BlockItem {
                name: "clkprescval_tgl",
                description: Some("Finial dividing factor = RIPPLECNTUPPER * CNTLOWER. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12344,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Clkprescval"),
                }),
            },
            BlockItem {
                name: "lock_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4168,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8264,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12360,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "chnlcmpdlyen0",
                    description: Some("enable delay for comparison."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Chnlcmpdlyen0"),
                },
                Field {
                    name: "chnltampdetfilten0",
                    description: Some("enable detect filtering."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlpaden0",
                    description: Some("enable driving pad."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlcmpdlyen1",
                    description: Some("enable delay for comparison."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnltampdetfilten1",
                    description: Some("enable detect filtering."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlpaden1",
                    description: Some("enable driving pad."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Chnlfiltwinsize",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "chnlfiltwinsize0",
                    description: Some("channel 0 Filter moving window size."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Chnlfiltwinsize0"),
                },
                Field {
                    name: "chnlfiltwinsize1",
                    description: Some("channel 1 Filter moving window size."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Chnlfiltwinsize1"),
                },
            ],
        },
        FieldSet {
            name: "Chnlseedval0",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "chnlseedval0",
                description: Some("Channel 0 LFSR Seed Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Chnlseedval1",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "chnlseedval1",
                description: Some("Channel 1 LFSR Seed Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Clkprescval",
            extends: None,
            description: Some("Finial dividing factor = RIPPLECNTUPPER * CNTLOWER."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "lowerpresc",
                    description: Some("Lower part of divider binary counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 6,
                    array: None,
                    enumm: Some("Lowerpresc"),
                },
                Field {
                    name: "upperpresc",
                    description: Some("Upper part of divider ripple counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Upperpresc"),
                },
            ],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "chnlstart0",
                    description: Some("Start channel 0 tamper detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlstop0",
                    description: Some("Stop channel 0 tamper detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlload0",
                    description: Some("Start channel 0 tamper detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlstart1",
                    description: Some("Start channel 1 tamper detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlstop1",
                    description: Some("Stop channel 1 tamper detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlload1",
                    description: Some("Start channel 1 tamper detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cntmismatchmax",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "chnlcntmismatchmax0",
                    description: Some("channel 0 filter counter threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Chnlcntmismatchmax0"),
                },
                Field {
                    name: "chnlcntmismatchmax1",
                    description: Some("channel 1 filter counter threshold."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Chnlcntmismatchmax1"),
                },
            ],
        },
        FieldSet {
            name: "Em4wuen",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "chnlem4wuen0",
                    description: Some("Channel0 Tampdet EM4 Wakeup Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlem4wuen1",
                    description: Some("Channel1 Tampdet EM4 Wakeup Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("ETAMPDET Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disabling",
                    description: Some("Disablement busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "tampdet0",
                    description: Some("TAMPDET0 interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tampdet1",
                    description: Some("TAMPDET1 interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "tampdet0",
                    description: Some("Tamper0 Detect Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "tampdet1",
                    description: Some("Tamper1 Detect Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP Version ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lockkey",
                description: Some("Configuration Lock Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("Lockkey"),
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "chnlrunning0",
                    description: Some("Channel0 Running Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlrunning1",
                    description: Some("Channel1 Running Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lockstatus",
                    description: Some("Lock Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Syncbusy",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "chnlstart0",
                    description: Some("Synchronizer busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlstop0",
                    description: Some("Synchronizer busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlload0",
                    description: Some("Synchronizer busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlstart1",
                    description: Some("Synchronizer busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlstop1",
                    description: Some("Synchronizer busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chnlload1",
                    description: Some("Synchronizer busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Chnlcmpdlyen0",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "X0",
                    description: Some("Disables 1 clock delay to the TX value used for comparison."),
                    value: 0,
                },
                EnumVariant {
                    name: "X1",
                    description: Some("Enables 1 clock delay to the TX value used for comparison."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Chnlcntmismatchmax0",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "DetectFilterThreshold1",
                    description: Some(
                        "Detect filter raise detect flag after seeing 1 event before reset counter expire.",
                    ),
                    value: 0,
                },
                EnumVariant {
                    name: "DetectFilterThreshold2",
                    description: Some(
                        "Detect filter raise detect flag after seeing 2 events before reset counter expire.",
                    ),
                    value: 1,
                },
                EnumVariant {
                    name: "DetectFilterThreshold3",
                    description: Some(
                        "Detect filter raise detect flag after seeing 3 events before reset counter expire.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "DetectFilterThreshold4",
                    description: Some(
                        "Detect filter raise detect flag after seeing 4 events before reset counter expire.",
                    ),
                    value: 3,
                },
                EnumVariant {
                    name: "DetectFilterThreshold5",
                    description: Some(
                        "Detect filter raise detect flag after seeing 5 events before reset counter expire.",
                    ),
                    value: 4,
                },
                EnumVariant {
                    name: "DetectFilterThreshold6",
                    description: Some(
                        "Detect filter raise detect flag after seeing 6 events before reset counter expire.",
                    ),
                    value: 5,
                },
                EnumVariant {
                    name: "DetectFilterThreshold7",
                    description: Some(
                        "Detect filter raise detect flag after seeing 7 events before reset counter expire.",
                    ),
                    value: 6,
                },
                EnumVariant {
                    name: "DetectFilterThreshold8",
                    description: Some(
                        "Detect filter raise detect flag after seeing 8 events before reset counter expire.",
                    ),
                    value: 7,
                },
            ],
        },
        Enum {
            name: "Chnlcntmismatchmax1",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "DetectFilterThreshold1",
                    description: Some(
                        "Detect filter raise detect flag after seeing 1 event before reset counter expire.",
                    ),
                    value: 0,
                },
                EnumVariant {
                    name: "DetectFilterThreshold2",
                    description: Some(
                        "Detect filter raise detect flag after seeing 2 events before reset counter expire.",
                    ),
                    value: 1,
                },
                EnumVariant {
                    name: "DetectFilterThreshold3",
                    description: Some(
                        "Detect filter raise detect flag after seeing 3 events before reset counter expire.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "DetectFilterThreshold4",
                    description: Some(
                        "Detect filter raise detect flag after seeing 4 events before reset counter expire.",
                    ),
                    value: 3,
                },
                EnumVariant {
                    name: "DetectFilterThreshold5",
                    description: Some(
                        "Detect filter raise detect flag after seeing 5 events before reset counter expire.",
                    ),
                    value: 4,
                },
                EnumVariant {
                    name: "DetectFilterThreshold6",
                    description: Some(
                        "Detect filter raise detect flag after seeing 6 events before reset counter expire.",
                    ),
                    value: 5,
                },
                EnumVariant {
                    name: "DetectFilterThreshold7",
                    description: Some(
                        "Detect filter raise detect flag after seeing 7 events before reset counter expire.",
                    ),
                    value: 6,
                },
                EnumVariant {
                    name: "DetectFilterThreshold8",
                    description: Some(
                        "Detect filter raise detect flag after seeing 8 events before reset counter expire.",
                    ),
                    value: 7,
                },
            ],
        },
        Enum {
            name: "Chnlfiltwinsize0",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "DetectFilterMovingWinSize10",
                    description: Some("Detect filter moving window size is 10."),
                    value: 9,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize11",
                    description: Some("Detect filter moving window size is 11."),
                    value: 10,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize12",
                    description: Some("Detect filter moving window size is 12."),
                    value: 11,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize13",
                    description: Some("Detect filter moving window size is 13."),
                    value: 12,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize14",
                    description: Some("Detect filter moving window size is 14."),
                    value: 13,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize15",
                    description: Some("Detect filter moving window size is 15."),
                    value: 14,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize16",
                    description: Some("Detect filter moving window size is 16."),
                    value: 15,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize2",
                    description: Some("Detect filter moving window size is 2."),
                    value: 1,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize3",
                    description: Some("Detect filter moving window size is 3."),
                    value: 2,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize4",
                    description: Some("Detect filter moving window size is 4."),
                    value: 3,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize5",
                    description: Some("Detect filter moving window size is 5."),
                    value: 4,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize6",
                    description: Some("Detect filter moving window size is 6."),
                    value: 5,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize7",
                    description: Some("Detect filter moving window size is 7."),
                    value: 6,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize8",
                    description: Some("Detect filter moving window size is 8."),
                    value: 7,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize9",
                    description: Some("Detect filter moving window size is 9."),
                    value: 8,
                },
                EnumVariant {
                    name: "Reserved",
                    description: Some("Reserved."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Chnlfiltwinsize1",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "DetectFilterMovingWinSize10",
                    description: Some("Detect filter moving window size is 10."),
                    value: 9,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize11",
                    description: Some("Detect filter moving window size is 11."),
                    value: 10,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize12",
                    description: Some("Detect filter moving window size is 12."),
                    value: 11,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize13",
                    description: Some("Detect filter moving window size is 13."),
                    value: 12,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize14",
                    description: Some("Detect filter moving window size is 14."),
                    value: 13,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize15",
                    description: Some("Detect filter moving window size is 15."),
                    value: 14,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize16",
                    description: Some("Detect filter moving window size is 16."),
                    value: 15,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize2",
                    description: Some("Detect filter moving window size is 2."),
                    value: 1,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize3",
                    description: Some("Detect filter moving window size is 3."),
                    value: 2,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize4",
                    description: Some("Detect filter moving window size is 4."),
                    value: 3,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize5",
                    description: Some("Detect filter moving window size is 5."),
                    value: 4,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize6",
                    description: Some("Detect filter moving window size is 6."),
                    value: 5,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize7",
                    description: Some("Detect filter moving window size is 7."),
                    value: 6,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize8",
                    description: Some("Detect filter moving window size is 8."),
                    value: 7,
                },
                EnumVariant {
                    name: "DetectFilterMovingWinSize9",
                    description: Some("Detect filter moving window size is 9."),
                    value: 8,
                },
                EnumVariant {
                    name: "Reserved",
                    description: Some("Reserved."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Lockkey",
            description: None,
            bit_size: 16,
            variants: &[EnumVariant {
                name: "Unlock",
                description: Some("Write to unlock all BURTC lockable registers."),
                value: 44776,
            }],
        },
        Enum {
            name: "Lowerpresc",
            description: None,
            bit_size: 6,
            variants: &[
                EnumVariant {
                    name: "Bypass",
                    description: Some("Divider is bypassed."),
                    value: 0,
                },
                EnumVariant {
                    name: "DivideBy10",
                    description: Some("Divide by 10."),
                    value: 9,
                },
                EnumVariant {
                    name: "DivideBy11",
                    description: Some("Divide by 11."),
                    value: 10,
                },
                EnumVariant {
                    name: "DivideBy12",
                    description: Some("Divide by 12."),
                    value: 11,
                },
                EnumVariant {
                    name: "DivideBy13",
                    description: Some("Divide by 13."),
                    value: 12,
                },
                EnumVariant {
                    name: "DivideBy14",
                    description: Some("Divide by 14."),
                    value: 13,
                },
                EnumVariant {
                    name: "DivideBy15",
                    description: Some("Divide by 15."),
                    value: 14,
                },
                EnumVariant {
                    name: "DivideBy16",
                    description: Some("Divide by 16."),
                    value: 15,
                },
                EnumVariant {
                    name: "DivideBy17",
                    description: Some("Divide by 17."),
                    value: 16,
                },
                EnumVariant {
                    name: "DivideBy18",
                    description: Some("Divide by 18."),
                    value: 17,
                },
                EnumVariant {
                    name: "DivideBy19",
                    description: Some("Divide by 19."),
                    value: 18,
                },
                EnumVariant {
                    name: "DivideBy2",
                    description: Some("Divide by 2."),
                    value: 1,
                },
                EnumVariant {
                    name: "DivideBy20",
                    description: Some("Divide by 20."),
                    value: 19,
                },
                EnumVariant {
                    name: "DivideBy21",
                    description: Some("Divide by 21."),
                    value: 20,
                },
                EnumVariant {
                    name: "DivideBy22",
                    description: Some("Divide by 22."),
                    value: 21,
                },
                EnumVariant {
                    name: "DivideBy23",
                    description: Some("Divide by 23."),
                    value: 22,
                },
                EnumVariant {
                    name: "DivideBy24",
                    description: Some("Divide by 24."),
                    value: 23,
                },
                EnumVariant {
                    name: "DivideBy25",
                    description: Some("Divide by 25."),
                    value: 24,
                },
                EnumVariant {
                    name: "DivideBy26",
                    description: Some("Divide by 26."),
                    value: 25,
                },
                EnumVariant {
                    name: "DivideBy27",
                    description: Some("Divide by 27."),
                    value: 26,
                },
                EnumVariant {
                    name: "DivideBy28",
                    description: Some("Divide by 28."),
                    value: 27,
                },
                EnumVariant {
                    name: "DivideBy29",
                    description: Some("Divide by 29."),
                    value: 28,
                },
                EnumVariant {
                    name: "DivideBy3",
                    description: Some("Divide by 3."),
                    value: 2,
                },
                EnumVariant {
                    name: "DivideBy30",
                    description: Some("Divide by 30."),
                    value: 29,
                },
                EnumVariant {
                    name: "DivideBy31",
                    description: Some("Divide by 31."),
                    value: 30,
                },
                EnumVariant {
                    name: "DivideBy32",
                    description: Some("Divide by 32."),
                    value: 31,
                },
                EnumVariant {
                    name: "DivideBy33",
                    description: Some("Divide by 33."),
                    value: 32,
                },
                EnumVariant {
                    name: "DivideBy34",
                    description: Some("Divide by 34."),
                    value: 33,
                },
                EnumVariant {
                    name: "DivideBy35",
                    description: Some("Divide by 35."),
                    value: 34,
                },
                EnumVariant {
                    name: "DivideBy36",
                    description: Some("Divide by 36."),
                    value: 35,
                },
                EnumVariant {
                    name: "DivideBy37",
                    description: Some("Divide by 37."),
                    value: 36,
                },
                EnumVariant {
                    name: "DivideBy38",
                    description: Some("Divide by 38."),
                    value: 37,
                },
                EnumVariant {
                    name: "DivideBy39",
                    description: Some("Divide by 39."),
                    value: 38,
                },
                EnumVariant {
                    name: "DivideBy4",
                    description: Some("Divide by 4."),
                    value: 3,
                },
                EnumVariant {
                    name: "DivideBy40",
                    description: Some("Divide by 40."),
                    value: 39,
                },
                EnumVariant {
                    name: "DivideBy41",
                    description: Some("Divide by 41."),
                    value: 40,
                },
                EnumVariant {
                    name: "DivideBy42",
                    description: Some("Divide by 42."),
                    value: 41,
                },
                EnumVariant {
                    name: "DivideBy43",
                    description: Some("Divide by 43."),
                    value: 42,
                },
                EnumVariant {
                    name: "DivideBy44",
                    description: Some("Divide by 44."),
                    value: 43,
                },
                EnumVariant {
                    name: "DivideBy45",
                    description: Some("Divide by 45."),
                    value: 44,
                },
                EnumVariant {
                    name: "DivideBy46",
                    description: Some("Divide by 46."),
                    value: 45,
                },
                EnumVariant {
                    name: "DivideBy47",
                    description: Some("Divide by 47."),
                    value: 46,
                },
                EnumVariant {
                    name: "DivideBy48",
                    description: Some("Divide by 48."),
                    value: 47,
                },
                EnumVariant {
                    name: "DivideBy49",
                    description: Some("Divide by 49."),
                    value: 48,
                },
                EnumVariant {
                    name: "DivideBy5",
                    description: Some("Divide by 5."),
                    value: 4,
                },
                EnumVariant {
                    name: "DivideBy50",
                    description: Some("Divide by 50."),
                    value: 49,
                },
                EnumVariant {
                    name: "DivideBy51",
                    description: Some("Divide by 51."),
                    value: 50,
                },
                EnumVariant {
                    name: "DivideBy52",
                    description: Some("Divide by 52."),
                    value: 51,
                },
                EnumVariant {
                    name: "DivideBy53",
                    description: Some("Divide by 53."),
                    value: 52,
                },
                EnumVariant {
                    name: "DivideBy54",
                    description: Some("Divide by 54."),
                    value: 53,
                },
                EnumVariant {
                    name: "DivideBy55",
                    description: Some("Divide by 55."),
                    value: 54,
                },
                EnumVariant {
                    name: "DivideBy56",
                    description: Some("Divide by 56."),
                    value: 55,
                },
                EnumVariant {
                    name: "DivideBy57",
                    description: Some("Divide by 57."),
                    value: 56,
                },
                EnumVariant {
                    name: "DivideBy58",
                    description: Some("Divide by 58."),
                    value: 57,
                },
                EnumVariant {
                    name: "DivideBy59",
                    description: Some("Divide by 59."),
                    value: 58,
                },
                EnumVariant {
                    name: "DivideBy6",
                    description: Some("Divide by 6."),
                    value: 5,
                },
                EnumVariant {
                    name: "DivideBy60",
                    description: Some("Divide by 60."),
                    value: 59,
                },
                EnumVariant {
                    name: "DivideBy61",
                    description: Some("Divide by 61."),
                    value: 60,
                },
                EnumVariant {
                    name: "DivideBy62",
                    description: Some("Divide by 62."),
                    value: 61,
                },
                EnumVariant {
                    name: "DivideBy63",
                    description: Some("Divide by 63."),
                    value: 62,
                },
                EnumVariant {
                    name: "DivideBy64",
                    description: Some("Divide by 64."),
                    value: 63,
                },
                EnumVariant {
                    name: "DivideBy7",
                    description: Some("Divide by 7."),
                    value: 6,
                },
                EnumVariant {
                    name: "DivideBy8",
                    description: Some("Divide by 8."),
                    value: 7,
                },
                EnumVariant {
                    name: "DivideBy9",
                    description: Some("Divide by 9."),
                    value: 8,
                },
            ],
        },
        Enum {
            name: "Upperpresc",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Bypass",
                    description: Some("Ripple counter divider is bypassed."),
                    value: 0,
                },
                EnumVariant {
                    name: "DivideBy16",
                    description: Some("Divide by 16."),
                    value: 4,
                },
                EnumVariant {
                    name: "DivideBy2",
                    description: Some("Divide by 2."),
                    value: 1,
                },
                EnumVariant {
                    name: "DivideBy32",
                    description: Some("Divide by 32."),
                    value: 5,
                },
                EnumVariant {
                    name: "DivideBy4",
                    description: Some("Divide by 4."),
                    value: 2,
                },
                EnumVariant {
                    name: "DivideBy64",
                    description: Some("Divide by 64."),
                    value: 6,
                },
                EnumVariant {
                    name: "DivideBy8",
                    description: Some("Divide by 8."),
                    value: 3,
                },
                EnumVariant {
                    name: "Reserved",
                    description: Some("Reserved, programing to this value is equal to programing 0x0."),
                    value: 7,
                },
            ],
        },
    ],
};
