use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Euart",
        extends: None,
        description: Some("EUART peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "cfg0",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg0"),
                }),
            },
            BlockItem {
                name: "cfg1",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg1"),
                }),
            },
            BlockItem {
                name: "framecfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Framecfg"),
                }),
            },
            BlockItem {
                name: "irhfcfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Irhfcfg"),
                }),
            },
            BlockItem {
                name: "irlfcfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Irlfcfg"),
                }),
            },
            BlockItem {
                name: "timingcfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Timingcfg"),
                }),
            },
            BlockItem {
                name: "startframecfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Startframecfg"),
                }),
            },
            BlockItem {
                name: "sigframecfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Sigframecfg"),
                }),
            },
            BlockItem {
                name: "clkdiv",
                description: Some("No Description."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Clkdiv"),
                }),
            },
            BlockItem {
                name: "trigctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 44,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Trigctrl"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 48,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "rxdata",
                description: Some("No Description."),
                array: None,
                byte_offset: 52,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Rxdata"),
                }),
            },
            BlockItem {
                name: "rxdatap",
                description: Some("No Description."),
                array: None,
                byte_offset: 56,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Rxdatap"),
                }),
            },
            BlockItem {
                name: "txdata",
                description: Some("No Description."),
                array: None,
                byte_offset: 60,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Txdata"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 64,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 68,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 72,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "syncbusy",
                description: Some("No Description."),
                array: None,
                byte_offset: 76,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Syncbusy"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfg0",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "loopbk",
                    description: Some("Loopback Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ccen",
                    description: Some("Collision Check Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mpm",
                    description: Some("Multi-Processor Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mpab",
                    description: Some("Multi-Processor Address-Bit."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ovs",
                    description: Some("Oversampling."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Ovs"),
                },
                Field {
                    name: "msbf",
                    description: Some("Most Significant Bit First."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxinv",
                    description: Some("Receiver Input Invert."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txinv",
                    description: Some("Transmitter output Invert."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "autotri",
                    description: Some("Automatic TX Tristate."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "skipperrf",
                    description: Some("Skip Parity Error Frames."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "errsdma",
                    description: Some("Halt DMA Read On Error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "errsrx",
                    description: Some("Disable RX On Error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "errstx",
                    description: Some("Disable TX On Error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mvdis",
                    description: Some("Majority Vote Disable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "autobauden",
                    description: Some("AUTOBAUD detection enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cfg1",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "dbghalt",
                    description: Some("Debug halt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ctsinv",
                    description: Some("Clear-to-send Invert Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ctsen",
                    description: Some("Clear-to-send Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rtsinv",
                    description: Some("Request-to-send Invert Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txdmawu",
                    description: Some("Transmitter DMA Wakeup."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxdmawu",
                    description: Some("Receiver DMA Wakeup."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sfubrx",
                    description: Some("Start Frame Unblock Receiver."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxprsen",
                    description: Some("PRS RX Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txfiw",
                    description: Some("TX FIFO Interrupt Watermark."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Txfiw"),
                },
                Field {
                    name: "rxfiw",
                    description: Some("RX FIFO Interrupt Watermark."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Rxfiw"),
                },
                Field {
                    name: "rtsrxfw",
                    description: Some("Request-to-send RX FIFO Watermark."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Rtsrxfw"),
                },
            ],
        },
        FieldSet {
            name: "Clkdiv",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "div",
                description: Some("Fractional Clock Divider."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                bit_size: 20,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rxen",
                    description: Some("Receiver Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxdis",
                    description: Some("Receiver Disable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txen",
                    description: Some("Transmitter Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txdis",
                    description: Some("Transmitter Disable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxblocken",
                    description: Some("Receiver Block Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxblockdis",
                    description: Some("Receiver Block Disable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txtrien",
                    description: Some("Transmitter Tristate Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txtridis",
                    description: Some("Transmitter Tristate Disable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cleartx",
                    description: Some("Clear TX FIFO."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "en",
                description: Some("Module enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Framecfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "databits",
                    description: Some("Data-Bit Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Databits"),
                },
                Field {
                    name: "parity",
                    description: Some("Parity-Bit Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Parity"),
                },
                Field {
                    name: "stopbits",
                    description: Some("Stop-Bit Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Stopbits"),
                },
            ],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "txc",
                    description: Some("TX Complete IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txfl",
                    description: Some("TX FIFO Level IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxfl",
                    description: Some("RX FIFO Level IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxfull",
                    description: Some("RX FIFO Full IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxof",
                    description: Some("RX FIFO Overflow IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxuf",
                    description: Some("RX FIFO Underflow IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txof",
                    description: Some("TX FIFO Overflow IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "perr",
                    description: Some("Parity Error IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ferr",
                    description: Some("Framing Error IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mpaf",
                    description: Some("Multi-Processor Addr Frame IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ccf",
                    description: Some("Collision Check Fail IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txidle",
                    description: Some("TX IDLE IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "startf",
                    description: Some("Start Frame IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sigf",
                    description: Some("Signal Frame IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "autobauddone",
                    description: Some("Auto Baud Complete IEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "txc",
                    description: Some("TX Complete Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txfl",
                    description: Some("TX FIFO Level Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxfl",
                    description: Some("RX FIFO Level Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxfull",
                    description: Some("RX FIFO Full Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxof",
                    description: Some("RX FIFO Overflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxuf",
                    description: Some("RX FIFO Underflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txof",
                    description: Some("TX FIFO Overflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "perr",
                    description: Some("Parity Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ferr",
                    description: Some("Framing Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mpaf",
                    description: Some("Multi-Processor Address Frame Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ccf",
                    description: Some("Collision Check Fail Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txidle",
                    description: Some("TX Idle Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "startf",
                    description: Some("Start Frame Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sigf",
                    description: Some("Signal Frame Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "autobauddone",
                    description: Some("Auto Baud Complete Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP version ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Irhfcfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "irhfen",
                    description: Some("Enable IrDA Module."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "irhfpw",
                    description: Some("IrDA TX Pulse Width."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Irhfpw"),
                },
                Field {
                    name: "irhffilt",
                    description: Some("IrDA RX Filter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Irlfcfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "irlfen",
                description: Some("Pulse Generator/Extender Enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Rxdata",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rxdata",
                    description: Some("RX Data."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "perr",
                    description: Some("Parity Error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ferr",
                    description: Some("Framing Error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rxdatap",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rxdatap",
                    description: Some("RX Data Peek."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "perrp",
                    description: Some("Parity Error Peek."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ferrp",
                    description: Some("Framing Error Peek."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Sigframecfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "sigframe",
                description: Some("Signal Frame Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 9,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Startframecfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "startframe",
                description: Some("Start Frame."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 9,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rxens",
                    description: Some("Receiver Enable Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txens",
                    description: Some("Transmitter Enable Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxblock",
                    description: Some("Block Incoming Data."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txtri",
                    description: Some("Transmitter Tristated."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txc",
                    description: Some("TX Complete."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txfl",
                    description: Some("TX FIFO Level."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxfl",
                    description: Some("RX FIFO Level."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxfull",
                    description: Some("RX FIFO Full."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxidle",
                    description: Some("RX Idle."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txidle",
                    description: Some("TX Idle."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txfcnt",
                    description: Some("Valid entries in TX FIFO."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cleartxbusy",
                    description: Some("TX FIFO Clear Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "autobauddone",
                    description: Some("Auto Baud Rate Detection Completed."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Syncbusy",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "div",
                    description: Some("SYNCBUSY for DIV in CLKDIV."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxten",
                    description: Some("SYNCBUSY for RXTEN in TRIGCTRL."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txten",
                    description: Some("SYNCBUSY for TXTEN in TRIGCTRL."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxen",
                    description: Some("SYNCBUSY for RXEN in CMD."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxdis",
                    description: Some("SYNCBUSY for RXDIS in CMD."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txen",
                    description: Some("SYNCBUSY for TXEN in CMD."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txdis",
                    description: Some("SYNCBUSY for TXDIS in CMD."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxblocken",
                    description: Some("SYNCBUSY for RXBLOCKEN in CMD."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxblockdis",
                    description: Some("SYNCBUSY for RXBLOCKDIS in CMD."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txtrien",
                    description: Some("SYNCBUSY for TXTRIEN in CMD."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txtridis",
                    description: Some("SYNCBUSY in TXTRIDIS in CMD."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Timingcfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "txdelay",
                description: Some("TX Delay Transmission."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("Txdelay"),
            }],
        },
        FieldSet {
            name: "Trigctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rxten",
                    description: Some("Receive Trigger Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txten",
                    description: Some("Transmit Trigger Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Txdata",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "txdata",
                    description: Some("TX Data."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ubrxat",
                    description: Some("Unblock RX After Transmission."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txtriat",
                    description: Some("Set TXTRI After Transmisssion."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txbreak",
                    description: Some("Transit Data as Break."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txdisat",
                    description: Some("Clear TXEN After Transmission."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxenat",
                    description: Some("Enable RXEN After Transmission."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Databits",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Eight",
                    description: Some("Each frame contains 8 data bits."),
                    value: 2,
                },
                EnumVariant {
                    name: "Nine",
                    description: Some("Each frame contains 9 data bits."),
                    value: 3,
                },
                EnumVariant {
                    name: "Seven",
                    description: Some("Each frame contains 7 data bits."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Irhfpw",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Four",
                    description: Some("IrDA pulse width is 4/16 for OVS=0 and 4/8 for OVS=1."),
                    value: 3,
                },
                EnumVariant {
                    name: "One",
                    description: Some("IrDA pulse width is 1/16 for OVS=0 and 1/8 for OVS=1."),
                    value: 0,
                },
                EnumVariant {
                    name: "Three",
                    description: Some("IrDA pulse width is 3/16 for OVS=0 and 3/8 for OVS=1."),
                    value: 2,
                },
                EnumVariant {
                    name: "Two",
                    description: Some("IrDA pulse width is 2/16 for OVS=0 and 2/8 for OVS=1."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Ovs",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Disable",
                    description: Some("Disable oversampling (for LF operation)."),
                    value: 4,
                },
                EnumVariant {
                    name: "X16",
                    description: Some("16X oversampling."),
                    value: 0,
                },
                EnumVariant {
                    name: "X4",
                    description: Some("4X oversampling."),
                    value: 3,
                },
                EnumVariant {
                    name: "X6",
                    description: Some("6X oversampling."),
                    value: 2,
                },
                EnumVariant {
                    name: "X8",
                    description: Some("8X oversampling."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Parity",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Even",
                    description: Some(
                        "Even parity are used. Parity bits are automatically generated and checked by hardware.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "None",
                    description: Some("Parity bits are not used."),
                    value: 0,
                },
                EnumVariant {
                    name: "Odd",
                    description: Some(
                        "Odd parity is used. Parity bits are automatically generated and checked by hardware.",
                    ),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Rtsrxfw",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Fourframes",
                    description: Some("RTS is set if there is space for four more frames in the RX FIFO."),
                    value: 3,
                },
                EnumVariant {
                    name: "Oneframe",
                    description: Some("RTS is set if there is space for at least one more frame in the RX FIFO."),
                    value: 0,
                },
                EnumVariant {
                    name: "Threeframes",
                    description: Some("RTS is set if there is space for at least three more frames in the RX FIFO."),
                    value: 2,
                },
                EnumVariant {
                    name: "Twoframes",
                    description: Some("RTS is set if there is space for at least two more frames in the RX FIFO."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Rxfiw",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Fourframes",
                    description: Some("RXFL status flag and IF are set when the RX FIFO has four frames in it."),
                    value: 3,
                },
                EnumVariant {
                    name: "Oneframe",
                    description: Some("RXFL status flag and IF are set when the RX FIFO has at least one frame in it."),
                    value: 0,
                },
                EnumVariant {
                    name: "Threeframes",
                    description: Some(
                        "RXFL status flag and IF are set when the RX FIFO has at least three frames in it.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "Twoframes",
                    description: Some(
                        "RXFL status flag and IF are set when the RX FIFO has at least two frames in it.",
                    ),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Stopbits",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Half",
                    description: Some(
                        "The transmitter generates a half stop bit. Stop-bits are not verified by receiver.",
                    ),
                    value: 0,
                },
                EnumVariant {
                    name: "One",
                    description: Some("One stop bit is generated and verified."),
                    value: 1,
                },
                EnumVariant {
                    name: "Oneandahalf",
                    description: Some(
                        "The transmitter generates one and a half stop bit. The receiver verifies the first stop bit.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "Two",
                    description: Some(
                        "The transmitter generates two stop bits. The receiver checks the first stop-bit only.",
                    ),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Txdelay",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Double",
                    description: Some("Transmission of new frames is delayed by a two bit periods."),
                    value: 2,
                },
                EnumVariant {
                    name: "None",
                    description: Some("Frames are transmitted immediately."),
                    value: 0,
                },
                EnumVariant {
                    name: "Single",
                    description: Some("Transmission of new frames is delayed by a single bit period."),
                    value: 1,
                },
                EnumVariant {
                    name: "Tripple",
                    description: Some("Transmission of new frames is delayed by a three bit periods."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Txfiw",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Fourframes",
                    description: Some(
                        "TXFL status flag and IF are set when the TX FIFO has space for at least four more frames.",
                    ),
                    value: 3,
                },
                EnumVariant {
                    name: "Oneframe",
                    description: Some(
                        "TXFL status flag and IF are set when the TX FIFO has space for at least one more frame.",
                    ),
                    value: 0,
                },
                EnumVariant {
                    name: "Threeframes",
                    description: Some(
                        "TXFL status flag and IF are set when the TX FIFO has space for at least three more frames.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "Twoframes",
                    description: Some(
                        "TXFL status flag and IF are set when the TX FIFO has space for at least two more frames.",
                    ),
                    value: 1,
                },
            ],
        },
    ],
};
