use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Hfxo",
        extends: None,
        description: Some("HFXO peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "xtalcfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Xtalcfg"),
                }),
            },
            BlockItem {
                name: "xtalctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Xtalctrl"),
                }),
            },
            BlockItem {
                name: "cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "bufouttrim",
                description: Some("No Description."),
                array: None,
                byte_offset: 64,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Bufouttrim"),
                }),
            },
            BlockItem {
                name: "bufoutctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 68,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Bufoutctrl"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 80,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 88,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 112,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 116,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("No Description."),
                array: None,
                byte_offset: 128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "xtalcfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Xtalcfg"),
                }),
            },
            BlockItem {
                name: "xtalcfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Xtalcfg"),
                }),
            },
            BlockItem {
                name: "xtalcfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Xtalcfg"),
                }),
            },
            BlockItem {
                name: "xtalctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Xtalctrl"),
                }),
            },
            BlockItem {
                name: "xtalctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Xtalctrl"),
                }),
            },
            BlockItem {
                name: "xtalctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Xtalctrl"),
                }),
            },
            BlockItem {
                name: "cfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "ctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4136,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8232,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12328,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "bufouttrim_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4160,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bufouttrim"),
                }),
            },
            BlockItem {
                name: "bufouttrim_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8256,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bufouttrim"),
                }),
            },
            BlockItem {
                name: "bufouttrim_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12352,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bufouttrim"),
                }),
            },
            BlockItem {
                name: "bufoutctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4164,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bufoutctrl"),
                }),
            },
            BlockItem {
                name: "bufoutctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8260,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bufoutctrl"),
                }),
            },
            BlockItem {
                name: "bufoutctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12356,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bufoutctrl"),
                }),
            },
            BlockItem {
                name: "cmd_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4176,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8272,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12368,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12400,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12404,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "lock_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12416,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Bufoutctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "xoutbiasana",
                    description: Some("Driver Bias Current."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "xoutcfana",
                    description: Some("Buffer Gain."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "xoutgmana",
                    description: Some("No Description."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "peakdetthresana",
                    description: Some("Peak Detector Threshold for XOUT."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timeoutctune",
                    description: Some("Tuning Cap Change Timeout."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Timeoutctune"),
                },
                Field {
                    name: "timeoutstartup",
                    description: Some("Oscillator Startup Timeout."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Timeoutstartup"),
                },
                Field {
                    name: "minimumstartupdelay",
                    description: Some("Minimum Startup Delay."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Bufouttrim",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "vtrtrimana",
                description: Some("BUFOUT Reference Trim."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 4,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mode",
                    description: Some("Crystal Oscillator Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Mode"),
                },
                Field {
                    name: "enxidcbiasana",
                    description: Some("Enable XI Internal DC Bias."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sqbufschtrgana",
                    description: Some("Squaring Buffer Schmitt Trigger."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcelftimeout",
                    description: Some("Force Low Frequency Timeout."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "corebiasopt",
                description: Some("Core Bias Optimizaton."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "bufoutfreeze",
                    description: Some("Freeze BUFOUT Controls."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keepwarm",
                    description: Some("Keep Warm."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "em23ondemand",
                    description: Some("On-demand During EM23."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcexi2gndana",
                    description: Some("Force XI Pin to Ground."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcexo2gndana",
                    description: Some("Force XO Pin to Ground."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forcectunemax",
                    description: Some("Force Tuning Cap to Max Value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prsstatussel0",
                    description: Some("PRS Status 0 Output Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Prsstatussel0"),
                },
                Field {
                    name: "prsstatussel1",
                    description: Some("PRS Status 1 Output Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Prsstatussel1"),
                },
                Field {
                    name: "forceen",
                    description: Some("Force Digital Clock Request."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forceenprs",
                    description: Some("Force PRS Oscillator Request."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "forceenbufout",
                    description: Some("Force BUFOUT Request."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disondemand",
                    description: Some("Disable On-demand For Digital Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disondemandprs",
                    description: Some("Disable On-demand For PRS."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disondemandbufout",
                    description: Some("Disable On-demand For BUFOUT."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rdy",
                    description: Some("Digital Clock Ready Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "corebiasoptrdy",
                    description: Some("Core Bias Optimization Ready Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prsrdy",
                    description: Some("PRS Ready Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutrdy",
                    description: Some("BUFOUT Ready Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutfrozen",
                    description: Some("BUFOUT FROZEN Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prserr",
                    description: Some("PRS Requset Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufouterr",
                    description: Some("BUFOUT Request Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutfreezeerr",
                    description: Some("BUFOUT Freeze Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutdnserr",
                    description: Some("BUFOUT Did Not Start Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dnserr",
                    description: Some("Did Not Start Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lftimeouterr",
                    description: Some("Low Frequency Timeout Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "corebiasopterr",
                    description: Some("Core Bias Optimization Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rdy",
                    description: Some("Digital Clock Ready Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "corebiasoptrdy",
                    description: Some("Core Bias Optimization Ready Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prsrdy",
                    description: Some("PRS Ready Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutrdy",
                    description: Some("BUFOUT Ready Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutfrozen",
                    description: Some("BUFOUT FROZEN Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prserr",
                    description: Some("PRS Requset Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufouterr",
                    description: Some("BUFOUT Request Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutfreezeerr",
                    description: Some("BUFOUT Freeze Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutdnserr",
                    description: Some("BUFOUT Did Not Start Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dnserr",
                    description: Some("Did Not Start Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lftimeouterr",
                    description: Some("Low Frequency Timeout Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "corebiasopterr",
                    description: Some("Core Bias Optimization Error Interrupt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP Version ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lockkey",
                description: Some("Configuration Lock Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("Lockkey"),
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rdy",
                    description: Some("Ready Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "corebiasoptrdy",
                    description: Some("Core Bias Optimization Ready."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prsrdy",
                    description: Some("PRS Ready Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutrdy",
                    description: Some("BUFOUT Ready Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufoutfrozen",
                    description: Some("BUFOUT Frozen."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ens",
                    description: Some("Enabled Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hwreq",
                    description: Some("Oscillator Requested by Digital Clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iswarm",
                    description: Some("Oscillator Is Kept Warm."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prshwreq",
                    description: Some("Oscillator Requested by PRS Request."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufouthwreq",
                    description: Some("Oscillator Requested by BUFOUT Request."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syncbusy",
                    description: Some("Sync Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lock",
                    description: Some("Configuration Lock Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Xtalcfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "corebiasstartupi",
                    description: Some("Intermediate Startup Core Bias Current."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "corebiasstartup",
                    description: Some("Startup Core Bias Current."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ctunexistartup",
                    description: Some("Startup Tuning Capacitance on XI."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ctunexostartup",
                    description: Some("Startup Tuning Capacitance on XO."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timeoutsteady",
                    description: Some("Steady State Timeout."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Timeoutsteady"),
                },
                Field {
                    name: "timeoutcblsb",
                    description: Some("Core Bias LSB Change Timeout."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Timeoutcblsb"),
                },
            ],
        },
        FieldSet {
            name: "Xtalctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "corebiasana",
                    description: Some("Core Bias Current."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ctunexiana",
                    description: Some("Tuning Capacitance on XI."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ctunexoana",
                    description: Some("Tuning Capacitance on XO."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ctunefixana",
                    description: Some("Fixed Tuning Capacitance."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Ctunefixana"),
                },
                Field {
                    name: "coredgenana",
                    description: Some("Core Degeneration."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Coredgenana"),
                },
                Field {
                    name: "skipcorebiasopt",
                    description: Some("Skip Core Bias Optimization."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Coredgenana",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Dgen100",
                    description: Some("Apply 100 ohm core degeneration resistence."),
                    value: 3,
                },
                EnumVariant {
                    name: "Dgen33",
                    description: Some("Apply 33 ohm core degeneration resistence."),
                    value: 1,
                },
                EnumVariant {
                    name: "Dgen50",
                    description: Some("Apply 50 ohm core degeneration resistence."),
                    value: 2,
                },
                EnumVariant {
                    name: "None",
                    description: Some("Do not apply core degeneration resistence."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Ctunefixana",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Both",
                    description: Some("Adds fixed capacitance on both XI and XO nodes."),
                    value: 3,
                },
                EnumVariant {
                    name: "None",
                    description: Some("Remove fixed capacitance on XI and XO nodes."),
                    value: 0,
                },
                EnumVariant {
                    name: "Xi",
                    description: Some("Adds fixed capacitance on XI node."),
                    value: 1,
                },
                EnumVariant {
                    name: "Xo",
                    description: Some("Adds fixed capacitance on XO node."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Lockkey",
            description: None,
            bit_size: 16,
            variants: &[EnumVariant {
                name: "Unlock",
                description: Some("Write this value to unlock."),
                value: 22542,
            }],
        },
        Enum {
            name: "Mode",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Extclk",
                    description: Some("external sinusoidal clock can be supplied on XI pin."),
                    value: 1,
                },
                EnumVariant {
                    name: "Extclkpkdet",
                    description: Some("external sinusoidal clock can be supplied on XI pin (peak detector used)."),
                    value: 2,
                },
                EnumVariant {
                    name: "Xtal",
                    description: Some("crystal oscillator."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Prsstatussel0",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Bufouthwreq",
                    description: Some("PRS mux outputs oscillator requested by BUFOUT request status."),
                    value: 10,
                },
                EnumVariant {
                    name: "Bufoutrdy",
                    description: Some("PRS mux outputs BUFOUT ready status."),
                    value: 5,
                },
                EnumVariant {
                    name: "Corebiasoptrdy",
                    description: Some("PRS mux outputs core bias optimization ready status."),
                    value: 2,
                },
                EnumVariant {
                    name: "Disabled",
                    description: Some("PRS mux outputs 0."),
                    value: 0,
                },
                EnumVariant {
                    name: "Ens",
                    description: Some("PRS mux outputs enabled status."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hwreq",
                    description: Some("PRS mux outputs oscillator requested by digital clock status."),
                    value: 8,
                },
                EnumVariant {
                    name: "Prshwreq",
                    description: Some("PRS mux outputs oscillator requested by PRS request status."),
                    value: 9,
                },
                EnumVariant {
                    name: "Prsrdy",
                    description: Some("PRS mux outputs PRS ready status."),
                    value: 4,
                },
                EnumVariant {
                    name: "Rdy",
                    description: Some("PRS mux outputs ready status."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Prsstatussel1",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Bufouthwreq",
                    description: Some("PRS mux outputs oscillator requested by BUFOUT request status."),
                    value: 10,
                },
                EnumVariant {
                    name: "Bufoutrdy",
                    description: Some("PRS mux outputs BUFOUT ready status."),
                    value: 5,
                },
                EnumVariant {
                    name: "Corebiasoptrdy",
                    description: Some("PRS mux outputs core bias optimization ready status."),
                    value: 2,
                },
                EnumVariant {
                    name: "Disabled",
                    description: Some("PRS mux outputs 0."),
                    value: 0,
                },
                EnumVariant {
                    name: "Ens",
                    description: Some("PRS mux outputs enabled status."),
                    value: 1,
                },
                EnumVariant {
                    name: "Hwreq",
                    description: Some("PRS mux outputs oscillator requested by digital clock status."),
                    value: 8,
                },
                EnumVariant {
                    name: "Prshwreq",
                    description: Some("PRS mux outputs oscillator requested by PRS request status."),
                    value: 9,
                },
                EnumVariant {
                    name: "Prsrdy",
                    description: Some("PRS mux outputs PRS ready status."),
                    value: 4,
                },
                EnumVariant {
                    name: "Rdy",
                    description: Some("PRS mux outputs ready status."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Timeoutcblsb",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "T104us",
                    description: Some(
                        "The core bias LSB change timeout is set to 104 us minimum. The maximum can be +40%.",
                    ),
                    value: 5,
                },
                EnumVariant {
                    name: "T1250us",
                    description: Some(
                        "The core bias LSB change timeout is set to 1250 us minimum. The maximum can be +40%.",
                    ),
                    value: 13,
                },
                EnumVariant {
                    name: "T125us",
                    description: Some(
                        "The core bias LSB change timeout is set to 125 us minimum. The maximum can be +40%.",
                    ),
                    value: 6,
                },
                EnumVariant {
                    name: "T166us",
                    description: Some(
                        "The core bias LSB change timeout is set to 166 us minimum. The maximum can be +40%.",
                    ),
                    value: 7,
                },
                EnumVariant {
                    name: "T2083us",
                    description: Some(
                        "The core bias LSB change timeout is set to 2083 us minimum. The maximum can be +40%.",
                    ),
                    value: 14,
                },
                EnumVariant {
                    name: "T208us",
                    description: Some(
                        "The core bias LSB change timeout is set to 208 us minimum. The maximum can be +40%.",
                    ),
                    value: 8,
                },
                EnumVariant {
                    name: "T20us",
                    description: Some(
                        "The core bias LSB change timeout is set to 20 us minimum. The maximum can be +40%.",
                    ),
                    value: 1,
                },
                EnumVariant {
                    name: "T250us",
                    description: Some(
                        "The core bias LSB change timeout is set to 250 us minimum. The maximum can be +40%.",
                    ),
                    value: 9,
                },
                EnumVariant {
                    name: "T333us",
                    description: Some(
                        "The core bias LSB change timeout is set to 333 us minimum. The maximum can be +40%.",
                    ),
                    value: 10,
                },
                EnumVariant {
                    name: "T3750us",
                    description: Some(
                        "The core bias LSB change timeout is set to 3750 us minimum. The maximum can be +40%.",
                    ),
                    value: 15,
                },
                EnumVariant {
                    name: "T416us",
                    description: Some(
                        "The core bias LSB change timeout is set to 416 us minimum. The maximum can be +40%.",
                    ),
                    value: 11,
                },
                EnumVariant {
                    name: "T41us",
                    description: Some(
                        "The core bias LSB change timeout is set to 41 us minimum. The maximum can be +40%.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "T62us",
                    description: Some(
                        "The core bias LSB change timeout is set to 62 us minimum. The maximum can be +40%.",
                    ),
                    value: 3,
                },
                EnumVariant {
                    name: "T833us",
                    description: Some(
                        "The core bias LSB change timeout is set to 833 us minimum. The maximum can be +40%.",
                    ),
                    value: 12,
                },
                EnumVariant {
                    name: "T83us",
                    description: Some(
                        "The core bias LSB change timeout is set to 83 us minimum. The maximum can be +40%.",
                    ),
                    value: 4,
                },
                EnumVariant {
                    name: "T8us",
                    description: Some(
                        "The core bias LSB change timeout is set to 8 us minimum. The maximum can be +40%.",
                    ),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Timeoutctune",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "T104us",
                    description: Some(
                        "The tuning cap change timeout is set to 104 us minimum. The maximum can be +40%.",
                    ),
                    value: 11,
                },
                EnumVariant {
                    name: "T10us",
                    description: Some(
                        "The tuning cap change timeout is set to 10 us minimum. The maximum can be +40%.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "T16us",
                    description: Some(
                        "The tuning cap change timeout is set to 16 us minimum. The maximum can be +40%.",
                    ),
                    value: 3,
                },
                EnumVariant {
                    name: "T208us",
                    description: Some(
                        "The tuning cap change timeout is set to 208 us minimum. The maximum can be +40%.",
                    ),
                    value: 12,
                },
                EnumVariant {
                    name: "T21us",
                    description: Some(
                        "The tuning cap change timeout is set to 21 us minimum. The maximum can be +40%.",
                    ),
                    value: 4,
                },
                EnumVariant {
                    name: "T26us",
                    description: Some(
                        "The tuning cap change timeout is set to 26 us minimum. The maximum can be +40%.",
                    ),
                    value: 5,
                },
                EnumVariant {
                    name: "T2us",
                    description: Some("The tuning cap change timeout is set to 2 us minimum. The maximum can be +40%."),
                    value: 0,
                },
                EnumVariant {
                    name: "T313us",
                    description: Some(
                        "The tuning cap change timeout is set to 313 us minimum. The maximum can be +40%.",
                    ),
                    value: 13,
                },
                EnumVariant {
                    name: "T31us",
                    description: Some(
                        "The tuning cap change timeout is set to 31 us minimum. The maximum can be +40%.",
                    ),
                    value: 6,
                },
                EnumVariant {
                    name: "T42us",
                    description: Some(
                        "The tuning cap change timeout is set to 42 us minimum. The maximum can be +40%.",
                    ),
                    value: 7,
                },
                EnumVariant {
                    name: "T521us",
                    description: Some(
                        "The tuning cap change timeout is set to 521 us minimum. The maximum can be +40%.",
                    ),
                    value: 14,
                },
                EnumVariant {
                    name: "T52us",
                    description: Some(
                        "The tuning cap change timeout is set to 52 us minimum. The maximum can be +40%.",
                    ),
                    value: 8,
                },
                EnumVariant {
                    name: "T5us",
                    description: Some("The tuning cap change timeout is set to 5 us minimum. The maximum can be +40%."),
                    value: 1,
                },
                EnumVariant {
                    name: "T63us",
                    description: Some(
                        "The tuning cap change timeout is set to 63 us minimum. The maximum can be +40%.",
                    ),
                    value: 9,
                },
                EnumVariant {
                    name: "T83us",
                    description: Some(
                        "The tuning cap change timeout is set to 83 us minimum. The maximum can be +40%.",
                    ),
                    value: 10,
                },
                EnumVariant {
                    name: "T938us",
                    description: Some(
                        "The tuning cap change timeout is set to 938 us minimum. The maximum can be +40%.",
                    ),
                    value: 15,
                },
            ],
        },
        Enum {
            name: "Timeoutstartup",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "T108us",
                    description: Some(
                        "The oscillator startup timeout is set to 108 us minimum. The maximum can be +40%.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "T133us",
                    description: Some(
                        "The oscillator startup timeout is set to 133 us minimum. The maximum can be +40%.",
                    ),
                    value: 3,
                },
                EnumVariant {
                    name: "T158us",
                    description: Some(
                        "The oscillator startup timeout is set to 158 us minimum. The maximum can be +40%.",
                    ),
                    value: 4,
                },
                EnumVariant {
                    name: "T183us",
                    description: Some(
                        "The oscillator startup timeout is set to 183 us minimum. The maximum can be +40%.",
                    ),
                    value: 5,
                },
                EnumVariant {
                    name: "T208us",
                    description: Some(
                        "The oscillator startup timeout is set to 208 us minimum. The maximum can be +40%.",
                    ),
                    value: 6,
                },
                EnumVariant {
                    name: "T233us",
                    description: Some(
                        "The oscillator startup timeout is set to 233 us minimum. The maximum can be +40%.",
                    ),
                    value: 7,
                },
                EnumVariant {
                    name: "T258us",
                    description: Some(
                        "The oscillator startup timeout is set to 258 us minimum. The maximum can be +40%.",
                    ),
                    value: 8,
                },
                EnumVariant {
                    name: "T283us",
                    description: Some(
                        "The oscillator startup timeout is set to 283 us minimum. The maximum can be +40%.",
                    ),
                    value: 9,
                },
                EnumVariant {
                    name: "T333us",
                    description: Some(
                        "The oscillator startup timeout is set to 333 us minimum. The maximum can be +40%.",
                    ),
                    value: 10,
                },
                EnumVariant {
                    name: "T375us",
                    description: Some(
                        "The oscillator startup timeout is set to 375 us minimum. The maximum can be +40%.",
                    ),
                    value: 11,
                },
                EnumVariant {
                    name: "T417us",
                    description: Some(
                        "The oscillator startup timeout is set to 417 us minimum. The maximum can be +40%.",
                    ),
                    value: 12,
                },
                EnumVariant {
                    name: "T42us",
                    description: Some(
                        "The oscillator startup timeout is set to 42 us minimum. The maximum can be +40%.",
                    ),
                    value: 0,
                },
                EnumVariant {
                    name: "T458us",
                    description: Some(
                        "The oscillator startup timeout is set to 458 us minimum. The maximum can be +40%.",
                    ),
                    value: 13,
                },
                EnumVariant {
                    name: "T500us",
                    description: Some(
                        "The oscillator startup timeout is set to 500 us minimum. The maximum can be +40%.",
                    ),
                    value: 14,
                },
                EnumVariant {
                    name: "T667us",
                    description: Some(
                        "The oscillator startup timeout is set to 667 us minimum. The maximum can be +40%.",
                    ),
                    value: 15,
                },
                EnumVariant {
                    name: "T83us",
                    description: Some(
                        "The oscillator startup timeout is set to 83 us minimum. The maximum can be +40%.",
                    ),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Timeoutsteady",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "T125us",
                    description: Some("The steady state timeout is set to 125 us minimum. The maximum can be +40%."),
                    value: 4,
                },
                EnumVariant {
                    name: "T1666us",
                    description: Some("The steady state timeout is set to 1666 us minimum. The maximum can be +40%."),
                    value: 13,
                },
                EnumVariant {
                    name: "T166us",
                    description: Some("The steady state timeout is set to 166 us minimum. The maximum can be +40%."),
                    value: 5,
                },
                EnumVariant {
                    name: "T16us",
                    description: Some("The steady state timeout is set to 16 us minimum. The maximum can be +40%."),
                    value: 1,
                },
                EnumVariant {
                    name: "T208us",
                    description: Some("The steady state timeout is set to 208 us minimum. The maximum can be +40%."),
                    value: 6,
                },
                EnumVariant {
                    name: "T2500us",
                    description: Some("The steady state timeout is set to 2500 us minimum. The maximum can be +40%."),
                    value: 14,
                },
                EnumVariant {
                    name: "T250us",
                    description: Some("The steady state timeout is set to 250 us minimum. The maximum can be +40%."),
                    value: 7,
                },
                EnumVariant {
                    name: "T333us",
                    description: Some("The steady state timeout is set to 333 us minimum. The maximum can be +40%."),
                    value: 8,
                },
                EnumVariant {
                    name: "T4166us",
                    description: Some("The steady state timeout is set to 4166 us minimum. The maximum can be +40%."),
                    value: 15,
                },
                EnumVariant {
                    name: "T416us",
                    description: Some("The steady state timeout is set to 416 us minimum. The maximum can be +40%."),
                    value: 9,
                },
                EnumVariant {
                    name: "T41us",
                    description: Some("The steady state timeout is set to 41 us minimum. The maximum can be +40%."),
                    value: 2,
                },
                EnumVariant {
                    name: "T4us",
                    description: Some("The steady state timeout is set to 4 us minimum. The maximum can be +40%."),
                    value: 0,
                },
                EnumVariant {
                    name: "T500us",
                    description: Some("The steady state timeout is set to 500 us minimum. The maximum can be +40%."),
                    value: 10,
                },
                EnumVariant {
                    name: "T666us",
                    description: Some("The steady state timeout is set to 666 us minimum. The maximum can be +40%."),
                    value: 11,
                },
                EnumVariant {
                    name: "T833us",
                    description: Some("The steady state timeout is set to 833 us minimum. The maximum can be +40%."),
                    value: 12,
                },
                EnumVariant {
                    name: "T83us",
                    description: Some("The steady state timeout is set to 83 us minimum. The maximum can be +40%."),
                    value: 3,
                },
            ],
        },
    ],
};
