use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Keyscan",
        extends: None,
        description: Some("KEYSCAN peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("IPVERSION."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("Enable."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst",
                description: Some("Software Reset."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "cfg",
                description: Some("Config."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("Command."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "delay",
                description: Some("Delay."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Delay"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("Status."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("Interrupt Flags."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("Interrupt Enables."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "en_set",
                description: Some("Enable. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_clr",
                description: Some("Enable. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_tgl",
                description: Some("Enable. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst_set",
                description: Some("Software Reset. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_clr",
                description: Some("Software Reset. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_tgl",
                description: Some("Software Reset. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "cfg_set",
                description: Some("Config. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_clr",
                description: Some("Config. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_tgl",
                description: Some("Config. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cmd_set",
                description: Some("Command. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_clr",
                description: Some("Command. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_tgl",
                description: Some("Command. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "delay_set",
                description: Some("Delay. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Delay"),
                }),
            },
            BlockItem {
                name: "delay_clr",
                description: Some("Delay. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Delay"),
                }),
            },
            BlockItem {
                name: "delay_tgl",
                description: Some("Delay. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Delay"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("Interrupt Flags. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4124,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("Interrupt Flags. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8220,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("Interrupt Flags. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12316,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("Interrupt Enables. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("Interrupt Enables. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("Interrupt Enables. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfg",
            extends: None,
            description: Some("Config."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "clkdiv",
                    description: Some("Clock Divider."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 18,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "singlepress",
                    description: Some("Single Press."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Singlepress"),
                },
                Field {
                    name: "autostart",
                    description: Some("Automatically Start."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "numrows",
                    description: Some("Number of Rows."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Numrows"),
                },
                Field {
                    name: "numcols",
                    description: Some("Number of Columns."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("Command."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "keyscanstart",
                    description: Some("Keyscan Start."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keyscanstop",
                    description: Some("Keyscan Stop."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Delay",
            extends: None,
            description: Some("Delay."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "scandly",
                    description: Some("Scan Delay."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Scandly"),
                },
                Field {
                    name: "debdly",
                    description: Some("Debounce Delay."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Debdly"),
                },
                Field {
                    name: "stabdly",
                    description: Some("Row stable Delay."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Stabdly"),
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("Enable."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disabling",
                    description: Some("Disablement busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("Interrupt Enables."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "nokey",
                    description: Some("No Key was pressed."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "key",
                    description: Some("A Key was pressed."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "scanned",
                    description: Some("Completed Scanning."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wakeup",
                    description: Some("Wake up."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("Interrupt Flags."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "nokey",
                    description: Some("No key was pressed."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "key",
                    description: Some("A key was pressed."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "scanned",
                    description: Some("Completed scan."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wakeup",
                    description: Some("Wake up."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("IPVERSION."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IPVERSION."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("Status."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "row",
                    description: Some("Row detection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "running",
                    description: Some("Running."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "col",
                    description: Some("Column Latched."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "nokey",
                    description: Some("No Key pressed status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syncbusy",
                    description: Some("Sync Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Swrst",
            extends: None,
            description: Some("Software Reset."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "swrst",
                    description: Some("Software reset command."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "resetting",
                    description: Some("Software reset busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Debdly",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Debdly10",
                    description: Some("10ms Debounce Delay."),
                    value: 4,
                },
                EnumVariant {
                    name: "Debdly12",
                    description: Some("12ms Debounce Delay."),
                    value: 5,
                },
                EnumVariant {
                    name: "Debdly14",
                    description: Some("14ms Debounce Delay."),
                    value: 6,
                },
                EnumVariant {
                    name: "Debdly16",
                    description: Some("16ms Debounce Delay."),
                    value: 7,
                },
                EnumVariant {
                    name: "Debdly18",
                    description: Some("18ms Debounce Delay."),
                    value: 8,
                },
                EnumVariant {
                    name: "Debdly2",
                    description: Some("2ms Debounce Delay."),
                    value: 0,
                },
                EnumVariant {
                    name: "Debdly20",
                    description: Some("20ms Debounce Delay."),
                    value: 9,
                },
                EnumVariant {
                    name: "Debdly22",
                    description: Some("22ms Debounce Delay."),
                    value: 10,
                },
                EnumVariant {
                    name: "Debdly24",
                    description: Some("24ms Debounce Delay."),
                    value: 11,
                },
                EnumVariant {
                    name: "Debdly26",
                    description: Some("26ms Debounce Delay."),
                    value: 12,
                },
                EnumVariant {
                    name: "Debdly28",
                    description: Some("28ms Debounce Delay."),
                    value: 13,
                },
                EnumVariant {
                    name: "Debdly30",
                    description: Some("30ms Debounce Delay."),
                    value: 14,
                },
                EnumVariant {
                    name: "Debdly32",
                    description: Some("32ms Debounce Delay."),
                    value: 15,
                },
                EnumVariant {
                    name: "Debdly4",
                    description: Some("4ms Debounce Delay."),
                    value: 1,
                },
                EnumVariant {
                    name: "Debdly6",
                    description: Some("6ms Debounce Delay."),
                    value: 2,
                },
                EnumVariant {
                    name: "Debdly8",
                    description: Some("8ms Debounce Delay."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Numrows",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Row3",
                    description: Some("3 Rows."),
                    value: 2,
                },
                EnumVariant {
                    name: "Row4",
                    description: Some("4 Rows."),
                    value: 3,
                },
                EnumVariant {
                    name: "Row5",
                    description: Some("5 Rows."),
                    value: 4,
                },
                EnumVariant {
                    name: "Row6",
                    description: Some("6 Rows."),
                    value: 5,
                },
                EnumVariant {
                    name: "Rsv1",
                    description: Some("1 Row is not supported; defaults to 3 instead."),
                    value: 0,
                },
                EnumVariant {
                    name: "Rsv2",
                    description: Some("2 Rows are not supported; defaults to 3 instead."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Scandly",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Scandly10",
                    description: Some("10ms Scan Delay."),
                    value: 4,
                },
                EnumVariant {
                    name: "Scandly12",
                    description: Some("12ms Scan Delay."),
                    value: 5,
                },
                EnumVariant {
                    name: "Scandly14",
                    description: Some("14ms Scan Delay."),
                    value: 6,
                },
                EnumVariant {
                    name: "Scandly16",
                    description: Some("16ms Scan Delay."),
                    value: 7,
                },
                EnumVariant {
                    name: "Scandly18",
                    description: Some("18ms Scan Delay."),
                    value: 8,
                },
                EnumVariant {
                    name: "Scandly2",
                    description: Some("2ms Scan Delay."),
                    value: 0,
                },
                EnumVariant {
                    name: "Scandly20",
                    description: Some("20ms Scan Delay."),
                    value: 9,
                },
                EnumVariant {
                    name: "Scandly22",
                    description: Some("22ms Scan Delay."),
                    value: 10,
                },
                EnumVariant {
                    name: "Scandly24",
                    description: Some("24ms Scan Delay."),
                    value: 11,
                },
                EnumVariant {
                    name: "Scandly26",
                    description: Some("26ms Scan Delay."),
                    value: 12,
                },
                EnumVariant {
                    name: "Scandly28",
                    description: Some("28ms Scan Delay."),
                    value: 13,
                },
                EnumVariant {
                    name: "Scandly30",
                    description: Some("30ms Scan Delay."),
                    value: 14,
                },
                EnumVariant {
                    name: "Scandly32",
                    description: Some("32ms Scan Delay."),
                    value: 15,
                },
                EnumVariant {
                    name: "Scandly4",
                    description: Some("4ms Scan Delay."),
                    value: 1,
                },
                EnumVariant {
                    name: "Scandly6",
                    description: Some("6ms Scan Delay."),
                    value: 2,
                },
                EnumVariant {
                    name: "Scandly8",
                    description: Some("8ms Scan Delay."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Singlepress",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Multipress",
                    description: Some(
                        "After KEYIF is set and then cleared, scanning will continue. This can give multiple interrupts for the same key press, but allow multiple key presses to be detected. To use this mode for multi-key detection, the ISR should update a section of memory of COLNUM bytes on each interrupt, until key release is detected. After key release, the section of memory where key presses are recorded can be processed.",
                    ),
                    value: 0,
                },
                EnumVariant {
                    name: "Singlepress",
                    description: Some(
                        "After KEYIF has been set and cleared, it will not set again until no key press is detected. This allows faster response since the ISR can start processing data as soon as the KEYIF is set.",
                    ),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Stabdly",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Stabdly10",
                    description: Some("10ms Row Stable Delay."),
                    value: 4,
                },
                EnumVariant {
                    name: "Stabdly12",
                    description: Some("12ms Row Stable Delay."),
                    value: 5,
                },
                EnumVariant {
                    name: "Stabdly14",
                    description: Some("14ms Row Stable Delay."),
                    value: 6,
                },
                EnumVariant {
                    name: "Stabdly16",
                    description: Some("16ms Row Stable Delay."),
                    value: 7,
                },
                EnumVariant {
                    name: "Stabdly18",
                    description: Some("18ms Row Stable Delay."),
                    value: 8,
                },
                EnumVariant {
                    name: "Stabdly2",
                    description: Some("2ms Row Stable Delay."),
                    value: 0,
                },
                EnumVariant {
                    name: "Stabdly20",
                    description: Some("20ms Row Stable Delay."),
                    value: 9,
                },
                EnumVariant {
                    name: "Stabdly22",
                    description: Some("22ms Row Stable Delay."),
                    value: 10,
                },
                EnumVariant {
                    name: "Stabdly24",
                    description: Some("24ms Row Stable Delay."),
                    value: 11,
                },
                EnumVariant {
                    name: "Stabdly26",
                    description: Some("26ms Row Stable Delay."),
                    value: 12,
                },
                EnumVariant {
                    name: "Stabdly28",
                    description: Some("28ms Row Stable Delay."),
                    value: 13,
                },
                EnumVariant {
                    name: "Stabdly30",
                    description: Some("30ms Row Stable Delay."),
                    value: 14,
                },
                EnumVariant {
                    name: "Stabdly32",
                    description: Some("32ms Row Stable Delay."),
                    value: 15,
                },
                EnumVariant {
                    name: "Stabdly4",
                    description: Some("4ms Row Stable Delay."),
                    value: 1,
                },
                EnumVariant {
                    name: "Stabdly6",
                    description: Some("6ms Row Stable Delay."),
                    value: 2,
                },
                EnumVariant {
                    name: "Stabdly8",
                    description: Some("8ms Row Stable Delay."),
                    value: 3,
                },
            ],
        },
    ],
};
