use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Lcd",
        extends: None,
        description: Some("LCD peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "dispctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dispctrl"),
                }),
            },
            BlockItem {
                name: "bacfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Bacfg"),
                }),
            },
            BlockItem {
                name: "bactrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Bactrl"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "arega",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Arega"),
                }),
            },
            BlockItem {
                name: "aregb",
                description: Some("No Description."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Aregb"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 44,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 48,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "biasctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 52,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Biasctrl"),
                }),
            },
            BlockItem {
                name: "dispctrlx",
                description: Some("No Description."),
                array: None,
                byte_offset: 56,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dispctrlx"),
                }),
            },
            BlockItem {
                name: "segd0",
                description: Some("SEGD0 - Register for Segments 31:0."),
                array: None,
                byte_offset: 64,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd0"),
                }),
            },
            BlockItem {
                name: "segd0h",
                description: Some("SEGD0H - Register for Segments 39:32."),
                array: None,
                byte_offset: 68,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd0h"),
                }),
            },
            BlockItem {
                name: "segd1",
                description: Some("SEGD1 - Register for Segments 31:0."),
                array: None,
                byte_offset: 72,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd1"),
                }),
            },
            BlockItem {
                name: "segd1h",
                description: Some("SEGD1H - Register for Segments 39:32."),
                array: None,
                byte_offset: 76,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd1h"),
                }),
            },
            BlockItem {
                name: "segd2",
                description: Some("SEGD2 - Register for Segments 31:0."),
                array: None,
                byte_offset: 80,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd2"),
                }),
            },
            BlockItem {
                name: "segd2h",
                description: Some("SEGD2H - Register for Segments 39:32."),
                array: None,
                byte_offset: 84,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd2h"),
                }),
            },
            BlockItem {
                name: "segd3",
                description: Some("SEGD3 - Register for Segments 31:0."),
                array: None,
                byte_offset: 88,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd3"),
                }),
            },
            BlockItem {
                name: "segd3h",
                description: Some("SEGD3H - Register for Segments 39:32."),
                array: None,
                byte_offset: 92,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd3h"),
                }),
            },
            BlockItem {
                name: "segd4",
                description: Some("SEGD4 - Register for Segments 31:0."),
                array: None,
                byte_offset: 96,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd4"),
                }),
            },
            BlockItem {
                name: "segd4h",
                description: Some("SEGD4H - Register for Segments 39:32."),
                array: None,
                byte_offset: 100,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd4h"),
                }),
            },
            BlockItem {
                name: "segd5",
                description: Some("SEGD5 - Register for Segments 31:0."),
                array: None,
                byte_offset: 104,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd5"),
                }),
            },
            BlockItem {
                name: "segd5h",
                description: Some("SEGD5H - Register for Segments 39:32."),
                array: None,
                byte_offset: 108,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd5h"),
                }),
            },
            BlockItem {
                name: "segd6",
                description: Some("SEGD6 - Register for Segments 31:0."),
                array: None,
                byte_offset: 112,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd6"),
                }),
            },
            BlockItem {
                name: "segd6h",
                description: Some("SEGD6H - Register for Segments 39:32."),
                array: None,
                byte_offset: 116,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd6h"),
                }),
            },
            BlockItem {
                name: "segd7",
                description: Some("SEGD7 - Register for Segments 31:0."),
                array: None,
                byte_offset: 120,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd7"),
                }),
            },
            BlockItem {
                name: "segd7h",
                description: Some("SEGD7H - Register for Segments 39:32."),
                array: None,
                byte_offset: 124,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Segd7h"),
                }),
            },
            BlockItem {
                name: "updatectrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 192,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Updatectrl"),
                }),
            },
            BlockItem {
                name: "framerate",
                description: Some("No Description."),
                array: None,
                byte_offset: 240,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Framerate"),
                }),
            },
            BlockItem {
                name: "en_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "ctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "cmd_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "dispctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dispctrl"),
                }),
            },
            BlockItem {
                name: "dispctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dispctrl"),
                }),
            },
            BlockItem {
                name: "dispctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dispctrl"),
                }),
            },
            BlockItem {
                name: "bacfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bacfg"),
                }),
            },
            BlockItem {
                name: "bacfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bacfg"),
                }),
            },
            BlockItem {
                name: "bacfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bacfg"),
                }),
            },
            BlockItem {
                name: "bactrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4124,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bactrl"),
                }),
            },
            BlockItem {
                name: "bactrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8220,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bactrl"),
                }),
            },
            BlockItem {
                name: "bactrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12316,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bactrl"),
                }),
            },
            BlockItem {
                name: "arega_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4132,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Arega"),
                }),
            },
            BlockItem {
                name: "arega_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8228,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Arega"),
                }),
            },
            BlockItem {
                name: "arega_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12324,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Arega"),
                }),
            },
            BlockItem {
                name: "aregb_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4136,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Aregb"),
                }),
            },
            BlockItem {
                name: "aregb_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8232,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Aregb"),
                }),
            },
            BlockItem {
                name: "aregb_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12328,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Aregb"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4140,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8236,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12332,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4144,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8240,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12336,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "biasctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4148,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Biasctrl"),
                }),
            },
            BlockItem {
                name: "biasctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8244,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Biasctrl"),
                }),
            },
            BlockItem {
                name: "biasctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12340,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Biasctrl"),
                }),
            },
            BlockItem {
                name: "dispctrlx_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4152,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dispctrlx"),
                }),
            },
            BlockItem {
                name: "dispctrlx_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8248,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dispctrlx"),
                }),
            },
            BlockItem {
                name: "dispctrlx_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12344,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dispctrlx"),
                }),
            },
            BlockItem {
                name: "segd0_set",
                description: Some("SEGD0 - Register for Segments 31:0. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4160,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd0"),
                }),
            },
            BlockItem {
                name: "segd0_clr",
                description: Some("SEGD0 - Register for Segments 31:0. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8256,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd0"),
                }),
            },
            BlockItem {
                name: "segd0_tgl",
                description: Some("SEGD0 - Register for Segments 31:0. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12352,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd0"),
                }),
            },
            BlockItem {
                name: "segd0h_set",
                description: Some("SEGD0H - Register for Segments 39:32. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4164,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd0h"),
                }),
            },
            BlockItem {
                name: "segd0h_clr",
                description: Some("SEGD0H - Register for Segments 39:32. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8260,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd0h"),
                }),
            },
            BlockItem {
                name: "segd0h_tgl",
                description: Some("SEGD0H - Register for Segments 39:32. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12356,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd0h"),
                }),
            },
            BlockItem {
                name: "segd1_set",
                description: Some("SEGD1 - Register for Segments 31:0. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4168,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd1"),
                }),
            },
            BlockItem {
                name: "segd1_clr",
                description: Some("SEGD1 - Register for Segments 31:0. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8264,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd1"),
                }),
            },
            BlockItem {
                name: "segd1_tgl",
                description: Some("SEGD1 - Register for Segments 31:0. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12360,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd1"),
                }),
            },
            BlockItem {
                name: "segd1h_set",
                description: Some("SEGD1H - Register for Segments 39:32. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4172,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd1h"),
                }),
            },
            BlockItem {
                name: "segd1h_clr",
                description: Some("SEGD1H - Register for Segments 39:32. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8268,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd1h"),
                }),
            },
            BlockItem {
                name: "segd1h_tgl",
                description: Some("SEGD1H - Register for Segments 39:32. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12364,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd1h"),
                }),
            },
            BlockItem {
                name: "segd2_set",
                description: Some("SEGD2 - Register for Segments 31:0. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4176,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd2"),
                }),
            },
            BlockItem {
                name: "segd2_clr",
                description: Some("SEGD2 - Register for Segments 31:0. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8272,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd2"),
                }),
            },
            BlockItem {
                name: "segd2_tgl",
                description: Some("SEGD2 - Register for Segments 31:0. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12368,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd2"),
                }),
            },
            BlockItem {
                name: "segd2h_set",
                description: Some("SEGD2H - Register for Segments 39:32. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4180,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd2h"),
                }),
            },
            BlockItem {
                name: "segd2h_clr",
                description: Some("SEGD2H - Register for Segments 39:32. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8276,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd2h"),
                }),
            },
            BlockItem {
                name: "segd2h_tgl",
                description: Some("SEGD2H - Register for Segments 39:32. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12372,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd2h"),
                }),
            },
            BlockItem {
                name: "segd3_set",
                description: Some("SEGD3 - Register for Segments 31:0. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4184,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd3"),
                }),
            },
            BlockItem {
                name: "segd3_clr",
                description: Some("SEGD3 - Register for Segments 31:0. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8280,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd3"),
                }),
            },
            BlockItem {
                name: "segd3_tgl",
                description: Some("SEGD3 - Register for Segments 31:0. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12376,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd3"),
                }),
            },
            BlockItem {
                name: "segd3h_set",
                description: Some("SEGD3H - Register for Segments 39:32. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4188,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd3h"),
                }),
            },
            BlockItem {
                name: "segd3h_clr",
                description: Some("SEGD3H - Register for Segments 39:32. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8284,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd3h"),
                }),
            },
            BlockItem {
                name: "segd3h_tgl",
                description: Some("SEGD3H - Register for Segments 39:32. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12380,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd3h"),
                }),
            },
            BlockItem {
                name: "segd4_set",
                description: Some("SEGD4 - Register for Segments 31:0. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4192,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd4"),
                }),
            },
            BlockItem {
                name: "segd4_clr",
                description: Some("SEGD4 - Register for Segments 31:0. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8288,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd4"),
                }),
            },
            BlockItem {
                name: "segd4_tgl",
                description: Some("SEGD4 - Register for Segments 31:0. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12384,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd4"),
                }),
            },
            BlockItem {
                name: "segd4h_set",
                description: Some("SEGD4H - Register for Segments 39:32. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd4h"),
                }),
            },
            BlockItem {
                name: "segd4h_clr",
                description: Some("SEGD4H - Register for Segments 39:32. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd4h"),
                }),
            },
            BlockItem {
                name: "segd4h_tgl",
                description: Some("SEGD4H - Register for Segments 39:32. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12388,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd4h"),
                }),
            },
            BlockItem {
                name: "segd5_set",
                description: Some("SEGD5 - Register for Segments 31:0. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd5"),
                }),
            },
            BlockItem {
                name: "segd5_clr",
                description: Some("SEGD5 - Register for Segments 31:0. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd5"),
                }),
            },
            BlockItem {
                name: "segd5_tgl",
                description: Some("SEGD5 - Register for Segments 31:0. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12392,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd5"),
                }),
            },
            BlockItem {
                name: "segd5h_set",
                description: Some("SEGD5H - Register for Segments 39:32. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd5h"),
                }),
            },
            BlockItem {
                name: "segd5h_clr",
                description: Some("SEGD5H - Register for Segments 39:32. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd5h"),
                }),
            },
            BlockItem {
                name: "segd5h_tgl",
                description: Some("SEGD5H - Register for Segments 39:32. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12396,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd5h"),
                }),
            },
            BlockItem {
                name: "segd6_set",
                description: Some("SEGD6 - Register for Segments 31:0. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd6"),
                }),
            },
            BlockItem {
                name: "segd6_clr",
                description: Some("SEGD6 - Register for Segments 31:0. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd6"),
                }),
            },
            BlockItem {
                name: "segd6_tgl",
                description: Some("SEGD6 - Register for Segments 31:0. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12400,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd6"),
                }),
            },
            BlockItem {
                name: "segd6h_set",
                description: Some("SEGD6H - Register for Segments 39:32. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd6h"),
                }),
            },
            BlockItem {
                name: "segd6h_clr",
                description: Some("SEGD6H - Register for Segments 39:32. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd6h"),
                }),
            },
            BlockItem {
                name: "segd6h_tgl",
                description: Some("SEGD6H - Register for Segments 39:32. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12404,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd6h"),
                }),
            },
            BlockItem {
                name: "segd7_set",
                description: Some("SEGD7 - Register for Segments 31:0. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd7"),
                }),
            },
            BlockItem {
                name: "segd7_clr",
                description: Some("SEGD7 - Register for Segments 31:0. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd7"),
                }),
            },
            BlockItem {
                name: "segd7_tgl",
                description: Some("SEGD7 - Register for Segments 31:0. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12408,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd7"),
                }),
            },
            BlockItem {
                name: "segd7h_set",
                description: Some("SEGD7H - Register for Segments 39:32. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4220,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd7h"),
                }),
            },
            BlockItem {
                name: "segd7h_clr",
                description: Some("SEGD7H - Register for Segments 39:32. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8316,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd7h"),
                }),
            },
            BlockItem {
                name: "segd7h_tgl",
                description: Some("SEGD7H - Register for Segments 39:32. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12412,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Segd7h"),
                }),
            },
            BlockItem {
                name: "updatectrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4288,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Updatectrl"),
                }),
            },
            BlockItem {
                name: "updatectrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8384,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Updatectrl"),
                }),
            },
            BlockItem {
                name: "updatectrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12480,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Updatectrl"),
                }),
            },
            BlockItem {
                name: "framerate_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4336,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Framerate"),
                }),
            },
            BlockItem {
                name: "framerate_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8432,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Framerate"),
                }),
            },
            BlockItem {
                name: "framerate_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12528,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Framerate"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Arega",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "arega",
                description: Some("Animation Register A Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Aregb",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "aregb",
                description: Some("Animation Register B Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Bacfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "astatetop",
                    description: Some("ASTATE top cnt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fcpresc",
                    description: Some("Frame Counter Prescaler."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Fcpresc"),
                },
                Field {
                    name: "fctop",
                    description: Some("Frame Counter Top."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Bactrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "blinken",
                    description: Some("Blink Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "blank",
                    description: Some("Blank Display."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "aen",
                    description: Some("Animation Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "aregasc",
                    description: Some("Animate Register A Shift Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Aregasc"),
                },
                Field {
                    name: "aregbsc",
                    description: Some("Animate Register B Shift Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Aregbsc"),
                },
                Field {
                    name: "alogsel",
                    description: Some("Animate Logic Function Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Alogsel"),
                },
                Field {
                    name: "fcen",
                    description: Some("Frame Counter Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "displaycnten",
                    description: Some("Display Counter Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "aloc",
                    description: Some("Animation Location."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Aloc"),
                },
            ],
        },
        FieldSet {
            name: "Biasctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "resistor",
                    description: Some("Resistor strength."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufdrv",
                    description: Some("Buffer Drive Strength."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bufbias",
                    description: Some("Buffer Bias Setting."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mode",
                    description: Some("Mode Setting."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Mode"),
                },
                Field {
                    name: "vlcd",
                    description: Some("VLCD voltage level."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 5,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vddxsel",
                    description: Some("VDDX select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Vddxsel"),
                },
                Field {
                    name: "lcdgate",
                    description: Some("LCD Gate."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dmamode",
                    description: Some("DMA Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Dmamode"),
                },
            ],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "load",
                    description: Some("Load command."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "clear",
                    description: Some("Clear command."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "udctrl",
                    description: Some("Update Data Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Udctrl"),
                },
                Field {
                    name: "dsc",
                    description: Some("Direct Segment Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "warmupdly",
                    description: Some("Warmup Delay."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Warmupdly"),
                },
                Field {
                    name: "prescale",
                    description: Some("Presclae."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 7,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Dispctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mux",
                    description: Some("Mux Configuration."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Mux"),
                },
                Field {
                    name: "wave",
                    description: Some("Waveform Selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Wave"),
                },
                Field {
                    name: "chgrdst",
                    description: Some("Charge Redistribution Cycles."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Chgrdst"),
                },
                Field {
                    name: "bias",
                    description: Some("Bias Configuration."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Bias"),
                },
            ],
        },
        FieldSet {
            name: "Dispctrlx",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "displaydiv",
                description: Some("Display Divider."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 10,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disabling",
                    description: Some("Disablement busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Framerate",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "frdiv",
                description: Some("Frame Rate Divider."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 9,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fc",
                    description: Some("Frame Counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "display",
                    description: Some("Display Update Event."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syncbusydone",
                    description: Some("Sync Busy Done."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "fc",
                    description: Some("Frame Counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "display",
                    description: Some("Display Update Event."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syncbusydone",
                    description: Some("Synchronization is Done."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IPVERSION."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd0",
            extends: None,
            description: Some("SEGD0 - Register for Segments 31:0."),
            bit_size: 32,
            fields: &[Field {
                name: "segd0",
                description: Some("COM0 Segment Data Low."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd0h",
            extends: None,
            description: Some("SEGD0H - Register for Segments 39:32."),
            bit_size: 32,
            fields: &[Field {
                name: "segd0h",
                description: Some("COM0 Segment Data High."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd1",
            extends: None,
            description: Some("SEGD1 - Register for Segments 31:0."),
            bit_size: 32,
            fields: &[Field {
                name: "segd1",
                description: Some("COM1 Segment Data Low."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd1h",
            extends: None,
            description: Some("SEGD1H - Register for Segments 39:32."),
            bit_size: 32,
            fields: &[Field {
                name: "segd1h",
                description: Some("COM1 Segment Data High."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd2",
            extends: None,
            description: Some("SEGD2 - Register for Segments 31:0."),
            bit_size: 32,
            fields: &[Field {
                name: "segd2",
                description: Some("COM2 Segment Data Low."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd2h",
            extends: None,
            description: Some("SEGD2H - Register for Segments 39:32."),
            bit_size: 32,
            fields: &[Field {
                name: "segd2h",
                description: Some("COM2 Segment Data High."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd3",
            extends: None,
            description: Some("SEGD3 - Register for Segments 31:0."),
            bit_size: 32,
            fields: &[Field {
                name: "segd3",
                description: Some("COM3 Segment Data Low."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd3h",
            extends: None,
            description: Some("SEGD3H - Register for Segments 39:32."),
            bit_size: 32,
            fields: &[Field {
                name: "segd3h",
                description: Some("COM3 Segment Data High."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd4",
            extends: None,
            description: Some("SEGD4 - Register for Segments 31:0."),
            bit_size: 32,
            fields: &[Field {
                name: "segd4",
                description: Some("COM4 Segment Data Low."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd4h",
            extends: None,
            description: Some("SEGD4H - Register for Segments 39:32."),
            bit_size: 32,
            fields: &[Field {
                name: "segd4h",
                description: Some("COM4 Segment Data High."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd5",
            extends: None,
            description: Some("SEGD5 - Register for Segments 31:0."),
            bit_size: 32,
            fields: &[Field {
                name: "segd5",
                description: Some("COM5 Segment Data Low."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd5h",
            extends: None,
            description: Some("SEGD5H - Register for Segments 39:32."),
            bit_size: 32,
            fields: &[Field {
                name: "segd5h",
                description: Some("COM5 Segment Data High."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd6",
            extends: None,
            description: Some("SEGD6 - Register for Segments 31:0."),
            bit_size: 32,
            fields: &[Field {
                name: "segd6",
                description: Some("COM6 Segment Data Low."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd6h",
            extends: None,
            description: Some("SEGD6H - Register for Segments 39:32."),
            bit_size: 32,
            fields: &[Field {
                name: "segd6h",
                description: Some("COM6 Segment Data High."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd7",
            extends: None,
            description: Some("SEGD7 - Register for Segments 31:0."),
            bit_size: 32,
            fields: &[Field {
                name: "segd7",
                description: Some("COM7 Segment Data Low."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Segd7h",
            extends: None,
            description: Some("SEGD7H - Register for Segments 39:32."),
            bit_size: 32,
            fields: &[Field {
                name: "segd7h",
                description: Some("COM7 Segment Data High."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "astate",
                    description: Some("Current Animation State."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "blink",
                    description: Some("Blink State."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "loadbusy",
                    description: Some("Load Synchronization is busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Swrst",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "swrst",
                    description: Some("Software reset command."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "resetting",
                    description: Some("Software reset busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Updatectrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "autoload",
                    description: Some("Auto Load."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Autoload"),
                },
                Field {
                    name: "loadaddr",
                    description: Some("Load Address."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 5,
                    array: None,
                    enumm: Some("Loadaddr"),
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Aloc",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Seg0to7",
                    description: Some("Animation appears on segments 0 to 7."),
                    value: 0,
                },
                EnumVariant {
                    name: "Seg8to15",
                    description: Some("Animation appears on segments 8 to 15."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Alogsel",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "And",
                    description: Some("AREGA and AREGB AND'ed."),
                    value: 0,
                },
                EnumVariant {
                    name: "Or",
                    description: Some("AREGA and AREGB OR'ed."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Aregasc",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Noshift",
                    description: Some("No Shift operation on Animation Register A."),
                    value: 0,
                },
                EnumVariant {
                    name: "Shiftleft",
                    description: Some("Animation Register A is shifted left."),
                    value: 1,
                },
                EnumVariant {
                    name: "Shiftright",
                    description: Some("Animation Register A is shifted right."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Aregbsc",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Noshift",
                    description: Some("No Shift operation on Animation Register B."),
                    value: 0,
                },
                EnumVariant {
                    name: "Shiftleft",
                    description: Some("Animation Register B is shifted left."),
                    value: 1,
                },
                EnumVariant {
                    name: "Shiftright",
                    description: Some("Animation Register B is shifted right."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Autoload",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Auto",
                    description: Some(
                        "CLK_BUS register to CLK_PER register loads will be started automatically after a write to the register in UPDATECTRL.LOADADDR is detected.",
                    ),
                    value: 1,
                },
                EnumVariant {
                    name: "Manual",
                    description: Some(
                        "CLK_BUS register to CLK_PER register loads must be done manually with a write to CMD.LOAD.",
                    ),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Bias",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Onefourth",
                    description: Some("1/4 Bias."),
                    value: 3,
                },
                EnumVariant {
                    name: "Onehalf",
                    description: Some("1/2 Bias."),
                    value: 1,
                },
                EnumVariant {
                    name: "Onethird",
                    description: Some("1/3 Bias."),
                    value: 2,
                },
                EnumVariant {
                    name: "Static",
                    description: Some("Static."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Chgrdst",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Disable",
                    description: Some("Disable charge redistribution."),
                    value: 0,
                },
                EnumVariant {
                    name: "Four",
                    description: Some("Use 4 prescaled low frequency clock cycles for charge redistribution."),
                    value: 4,
                },
                EnumVariant {
                    name: "One",
                    description: Some("Use 1 prescaled low frequency clock cycle for charge redistribution."),
                    value: 1,
                },
                EnumVariant {
                    name: "Three",
                    description: Some("Use 3 prescaled low frequency clock cycles for charge redistribution."),
                    value: 3,
                },
                EnumVariant {
                    name: "Two",
                    description: Some("Use 2 prescaled low frequency clock cycles for charge redistribution."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Dmamode",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Dmadisable",
                    description: Some("No DMA requests are generated."),
                    value: 0,
                },
                EnumVariant {
                    name: "Dmadisplay",
                    description: Some(
                        "DMA request on display counter event. This will also start a DMA transfer during EM23.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "Dmafc",
                    description: Some(
                        "DMA request on frame counter event. This will also start a DMA transfer during EM23.",
                    ),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Fcpresc",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Div1",
                    description: Some("every frame clock."),
                    value: 0,
                },
                EnumVariant {
                    name: "Div2",
                    description: Some("every 2nd frame clock."),
                    value: 1,
                },
                EnumVariant {
                    name: "Div4",
                    description: Some("every 4th frame clock."),
                    value: 2,
                },
                EnumVariant {
                    name: "Div8",
                    description: Some("every 8th frame clock."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Loadaddr",
            description: None,
            bit_size: 5,
            variants: &[
                EnumVariant {
                    name: "Aregawr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to AREGA. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 1,
                },
                EnumVariant {
                    name: "Aregbwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to AREGB. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 2,
                },
                EnumVariant {
                    name: "Bactrlwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to BACTRL. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 0,
                },
                EnumVariant {
                    name: "Segd0hwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD0H. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 11,
                },
                EnumVariant {
                    name: "Segd0wr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD0. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 3,
                },
                EnumVariant {
                    name: "Segd1hwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD1H. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 12,
                },
                EnumVariant {
                    name: "Segd1wr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD1. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 4,
                },
                EnumVariant {
                    name: "Segd2hwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD2H. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 13,
                },
                EnumVariant {
                    name: "Segd2wr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD2. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 5,
                },
                EnumVariant {
                    name: "Segd3hwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD3H. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 14,
                },
                EnumVariant {
                    name: "Segd3wr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD3. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 6,
                },
                EnumVariant {
                    name: "Segd4hwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD4H. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 15,
                },
                EnumVariant {
                    name: "Segd4wr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD4. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 7,
                },
                EnumVariant {
                    name: "Segd5hwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD5H. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 16,
                },
                EnumVariant {
                    name: "Segd5wr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD5. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 8,
                },
                EnumVariant {
                    name: "Segd6hwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD6H. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 17,
                },
                EnumVariant {
                    name: "Segd6wr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD6. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 9,
                },
                EnumVariant {
                    name: "Segd7hwr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD7H. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 18,
                },
                EnumVariant {
                    name: "Segd7wr",
                    description: Some(
                        "Starts synchronizing registers from CLK_BUS to CLK_PER after a write to SEGD7. Use with UPDATECTRL.AUTOLOAD.",
                    ),
                    value: 10,
                },
            ],
        },
        Enum {
            name: "Mode",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Chargepump",
                    description: Some("Use the charge pump to pump VLCD above VDDX."),
                    value: 1,
                },
                EnumVariant {
                    name: "Stepdown",
                    description: Some(
                        "Use step down control with VLCD less than VDDX. Use VLCD[4:0] to control VLCD level, and use SPEED to adjust VLCD drive strength.",
                    ),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Mux",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Duplex",
                    description: Some("Duplex."),
                    value: 1,
                },
                EnumVariant {
                    name: "Octaplex",
                    description: Some("Octaplex."),
                    value: 7,
                },
                EnumVariant {
                    name: "Quadruplex",
                    description: Some("Quadruplex."),
                    value: 3,
                },
                EnumVariant {
                    name: "Sextaplex",
                    description: Some("Sextaplex."),
                    value: 5,
                },
                EnumVariant {
                    name: "Static",
                    description: Some("Static."),
                    value: 0,
                },
                EnumVariant {
                    name: "Triplex",
                    description: Some("Triplex."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Udctrl",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Displayevent",
                    description: Some("The data transfer is done at the next Display Counter event."),
                    value: 3,
                },
                EnumVariant {
                    name: "Fcevent",
                    description: Some("The data transfer is done at the next Frame Counter event."),
                    value: 2,
                },
                EnumVariant {
                    name: "Framestart",
                    description: Some("Data is loaded continuously at every frame start."),
                    value: 1,
                },
                EnumVariant {
                    name: "Regular",
                    description: Some(
                        "The data transfer is controlled by SW. Transfer is performed as soon as possible on the next CTRL.PRESCALE clock. This is primarily available for debug only since only some of the new SEGMENT data may be ready by the time of the UPDATE. This should not be used with interrupts since partially updating SEGMENT data may have indeterminant results.",
                    ),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Vddxsel",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Avdd",
                    description: Some("Connect charge pump to analog AVDD supply."),
                    value: 1,
                },
                EnumVariant {
                    name: "Dvdd",
                    description: Some("Connect charge pump to digital DVDD supply."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Warmupdly",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Warmup1",
                    description: Some("1mswarm up."),
                    value: 0,
                },
                EnumVariant {
                    name: "Warmup1000",
                    description: Some("1000ms warm up."),
                    value: 6,
                },
                EnumVariant {
                    name: "Warmup125",
                    description: Some("125ms warm up."),
                    value: 3,
                },
                EnumVariant {
                    name: "Warmup2000",
                    description: Some("2000ms warm up."),
                    value: 7,
                },
                EnumVariant {
                    name: "Warmup250",
                    description: Some("250ms warm up."),
                    value: 4,
                },
                EnumVariant {
                    name: "Warmup31",
                    description: Some("31ms warm up."),
                    value: 1,
                },
                EnumVariant {
                    name: "Warmup500",
                    description: Some("500ms warm up."),
                    value: 5,
                },
                EnumVariant {
                    name: "Warmup63",
                    description: Some("62ms warm up."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Wave",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Typea",
                    description: Some("Type A waveform."),
                    value: 1,
                },
                EnumVariant {
                    name: "Typeb",
                    description: Some("Type B waveform."),
                    value: 0,
                },
            ],
        },
    ],
};
