use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Lfrco",
        extends: None,
        description: Some("LFRCO peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("Contains the LFRCO ip version."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("Status register."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "cal",
                description: Some("Calibration register."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cal"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("Interrupt flag register."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("Interrupt enable register."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "syncbusy",
                description: Some("Synchronization busy register."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Syncbusy"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("Configuration lock register. Locks/unlocks access to cofiguration registers."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "cal_set",
                description: Some("Calibration register. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cal"),
                }),
            },
            BlockItem {
                name: "cal_clr",
                description: Some("Calibration register. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cal"),
                }),
            },
            BlockItem {
                name: "cal_tgl",
                description: Some("Calibration register. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cal"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("Interrupt flag register. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("Interrupt flag register. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("Interrupt flag register. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("Interrupt enable register. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("Interrupt enable register. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("Interrupt enable register. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "lock_set",
                description: Some(
                    "Configuration lock register. Locks/unlocks access to cofiguration registers. (write-1-to-set alias)",
                ),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_clr",
                description: Some(
                    "Configuration lock register. Locks/unlocks access to cofiguration registers. (write-1-to-clr alias)",
                ),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_tgl",
                description: Some(
                    "Configuration lock register. Locks/unlocks access to cofiguration registers. (write-1-to-tgl alias)",
                ),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cal",
            extends: None,
            description: Some("Calibration register."),
            bit_size: 32,
            fields: &[Field {
                name: "freqtrim",
                description: Some("Frequency Trim."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("Interrupt enable register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rdy",
                    description: Some("Ready Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "posedge",
                    description: Some("Rising Edge Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "negedge",
                    description: Some("Falling Edge Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("Interrupt flag register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rdy",
                    description: Some("Ready Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "posedge",
                    description: Some("Rising Edge Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "negedge",
                    description: Some("Falling Edge Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("Contains the LFRCO ip version."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP version ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("Configuration lock register. Locks/unlocks access to cofiguration registers."),
            bit_size: 32,
            fields: &[Field {
                name: "lockkey",
                description: Some("Lock Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("Lockkey"),
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("Status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rdy",
                    description: Some("Ready Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ens",
                    description: Some("Enabled Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lock",
                    description: Some("Lock Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Syncbusy",
            extends: None,
            description: Some("Synchronization busy register."),
            bit_size: 32,
            fields: &[Field {
                name: "cal",
                description: Some("CAL Busy."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[Enum {
        name: "Lockkey",
        description: None,
        bit_size: 16,
        variants: &[
            EnumVariant {
                name: "Lock",
                description: Some("Lock Configuration Registers."),
                value: 0,
            },
            EnumVariant {
                name: "Unlock",
                description: Some("Unlock Configuaration Registers."),
                value: 9731,
            },
        ],
    }],
};
