use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Pcnt",
        extends: None,
        description: Some("PCNT peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "cnt",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Cnt"),
                }),
            },
            BlockItem {
                name: "auxcnt",
                description: Some("No Description."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Auxcnt"),
                }),
            },
            BlockItem {
                name: "top",
                description: Some("No Description."),
                array: None,
                byte_offset: 44,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Top"),
                }),
            },
            BlockItem {
                name: "topb",
                description: Some("No Description."),
                array: None,
                byte_offset: 48,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Topb"),
                }),
            },
            BlockItem {
                name: "ovsctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 52,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ovsctrl"),
                }),
            },
            BlockItem {
                name: "syncbusy",
                description: Some("No Description."),
                array: None,
                byte_offset: 56,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Syncbusy"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("No Description."),
                array: None,
                byte_offset: 60,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "en_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "cfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "ctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "cmd_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4124,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8220,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12316,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "top_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4140,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Top"),
                }),
            },
            BlockItem {
                name: "top_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8236,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Top"),
                }),
            },
            BlockItem {
                name: "top_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12332,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Top"),
                }),
            },
            BlockItem {
                name: "topb_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4144,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Topb"),
                }),
            },
            BlockItem {
                name: "topb_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8240,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Topb"),
                }),
            },
            BlockItem {
                name: "topb_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12336,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Topb"),
                }),
            },
            BlockItem {
                name: "ovsctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4148,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ovsctrl"),
                }),
            },
            BlockItem {
                name: "ovsctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8244,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ovsctrl"),
                }),
            },
            BlockItem {
                name: "ovsctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12340,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ovsctrl"),
                }),
            },
            BlockItem {
                name: "lock_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4156,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8252,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12348,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Auxcnt",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "auxcnt",
                description: Some("Auxiliary Counter Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mode",
                    description: Some("Mode Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Mode"),
                },
                Field {
                    name: "debughalt",
                    description: Some("Debug Mode Halt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "filten",
                    description: Some("Enable Digital Pulse Width Filter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hyst",
                    description: Some("Enable Hysteresis."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "s0prsen",
                    description: Some("S0IN PRS Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "s1prsen",
                    description: Some("S1IN PRS Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "corerst",
                    description: Some("PCNT Clock Domain Reset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cntrst",
                    description: Some("CNT Reset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "auxcntrst",
                    description: Some("AUXCNT Reset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lcntim",
                    description: Some("Load CNT Immediately."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "startcnt",
                    description: Some("Start Main Counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "startauxcnt",
                    description: Some("Start Aux Counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "stopcnt",
                    description: Some("Stop Main Counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "stopauxcnt",
                    description: Some("Stop Aux Counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cnt",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "cnt",
                description: Some("Counter Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "s1cdir",
                    description: Some("Count Direction Determined By S1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cntdir",
                    description: Some("Non-Quadrature Mode Counter Direction Co."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Cntdir"),
                },
                Field {
                    name: "edge",
                    description: Some("Edge Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Edge"),
                },
                Field {
                    name: "cntev",
                    description: Some("Controls When the Counter Counts."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Cntev"),
                },
                Field {
                    name: "auxcntev",
                    description: Some("Controls When the Aux Counter Counts."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Auxcntev"),
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("PCNT Module Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disabling",
                    description: Some("Disablement busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "uf",
                    description: Some("Underflow Interrupt Read Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "of",
                    description: Some("Overflow Interrupt Read Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dircng",
                    description: Some("Direction Change Detect Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "auxof",
                    description: Some("Auxiliary Overflow Interrupt Read Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "oqsterr",
                    description: Some("Oversampling Quad State Err Int Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "uf",
                    description: Some("Underflow Interrupt Read Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "of",
                    description: Some("Overflow Interrupt Read Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dircng",
                    description: Some("Direction Change Detect Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "auxof",
                    description: Some("Auxiliary Overflow Interrupt Read Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "oqsterr",
                    description: Some("Oversampling Quad State Err Int Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP VERSION."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "pcntlockkey",
                description: Some("Configuration Lock Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("Pcntlockkey"),
            }],
        },
        FieldSet {
            name: "Ovsctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "filtlen",
                    description: Some("Configure Filter Length for Inputs S0IN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "flutterrm",
                    description: Some("Flutter Remove."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "dir",
                    description: Some("Current Counter Direction."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Dir"),
                },
                Field {
                    name: "topbv",
                    description: Some("TOP Buffer Valid."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pcntlockstatus",
                    description: Some("Lock Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cntrunning",
                    description: Some("Main Counter running status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "auxcntrunning",
                    description: Some("Aux Counter running status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Swrst",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "swrst",
                    description: Some("Software reset command."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "resetting",
                    description: Some("Software reset busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Syncbusy",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ctrl",
                    description: Some("CTRL Register Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cmd",
                    description: Some("CMD Register Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "top",
                    description: Some("TOP Register Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "topb",
                    description: Some("TOPB Register Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ovsctrl",
                    description: Some("OVSCTRL Register Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Top",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "top",
                description: Some("Counter Top Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Topb",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "topb",
                description: Some("Counter Top Buffer Register."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[
        Enum {
            name: "Auxcntev",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Both",
                    description: Some("Counts up on both up-count and down-count events."),
                    value: 0,
                },
                EnumVariant {
                    name: "Down",
                    description: Some("Counts up on down-count events."),
                    value: 2,
                },
                EnumVariant {
                    name: "Up",
                    description: Some("Counts up on up-count events."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Cntdir",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Down",
                    description: Some("Down counter mode."),
                    value: 1,
                },
                EnumVariant {
                    name: "Up",
                    description: Some("Up counter mode."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Cntev",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Both",
                    description: Some("Counts up on up-count and down on down-count events."),
                    value: 0,
                },
                EnumVariant {
                    name: "Down",
                    description: Some("Only counts down on down-count events."),
                    value: 2,
                },
                EnumVariant {
                    name: "Up",
                    description: Some("Only counts up on up-count events."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Dir",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Down",
                    description: Some("Down counter mode."),
                    value: 1,
                },
                EnumVariant {
                    name: "Up",
                    description: Some(
                        "Up counter mode (clockwise in EXTCLKQUAD mode with the EDGE bit in PCNTn_CTRL set to 0).",
                    ),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Edge",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Neg",
                    description: Some(
                        "Negative edges on the PCNTn_S0IN inputs are counted in OVSSINGLE mode. Inverts the PCNTn_S1IN input in OVSSINGLE and EXTCLKSINGLE modes.",
                    ),
                    value: 1,
                },
                EnumVariant {
                    name: "Pos",
                    description: Some(
                        "Positive edges on the PCNTn_S0IN inputs are counted in OVSSINGLE mode. Does not invert PCNTn_S1IN input in OVSSINGLE and EXTCLKSINGLE modes.",
                    ),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Mode",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Extclkquad",
                    description: Some("Externally clocked quadrature decoder mode (available in EM0-EM3)."),
                    value: 2,
                },
                EnumVariant {
                    name: "Extclksingle",
                    description: Some("Externally clocked single input counter mode (available in EM0-EM3)."),
                    value: 1,
                },
                EnumVariant {
                    name: "Ovsquad1x",
                    description: Some("EM23GRPACLK oversampling quadrature decoder 1X mode (available in EM0-EM3)."),
                    value: 3,
                },
                EnumVariant {
                    name: "Ovsquad2x",
                    description: Some("EM23GRPACLK oversampling quadrature decoder 2X mode (available in EM0-EM3)."),
                    value: 4,
                },
                EnumVariant {
                    name: "Ovsquad4x",
                    description: Some("EM23GRPACLK oversampling quadrature decoder 4X mode (available in EM0-EM3)."),
                    value: 5,
                },
                EnumVariant {
                    name: "Ovssingle",
                    description: Some("Single input EM23GRPACLK oversampling mode (available in EM0-EM3)."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Pcntlockkey",
            description: None,
            bit_size: 16,
            variants: &[EnumVariant {
                name: "Unlock",
                description: Some("Write to unock PCNT lockable registers."),
                value: 42976,
            }],
        },
    ],
};
