use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Pfmxpprf",
        extends: None,
        description: Some("PFMXPPRF peripheral."),
        items: &[
            BlockItem {
                name: "rfimdcdcctrl0",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl0"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl1",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl1"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl2",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl2"),
                }),
            },
            BlockItem {
                name: "rfimdcdcstatus",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcstatus"),
                }),
            },
            BlockItem {
                name: "rpuratd0",
                description: Some(
                    "Protected register address = (RPURATD register index X 32 + RPURATD bit index) X 4.",
                ),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rpuratd0"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl0_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4096,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl0"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl0_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8192,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl0"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl0_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12288,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl0"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl1_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl1"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl1_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl1"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl1_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl1"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl2_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl2"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl2_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl2"),
                }),
            },
            BlockItem {
                name: "rfimdcdcctrl2_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rfimdcdcctrl2"),
                }),
            },
            BlockItem {
                name: "rpuratd0_set",
                description: Some(
                    "Protected register address = (RPURATD register index X 32 + RPURATD bit index) X 4. (write-1-to-set alias)",
                ),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rpuratd0"),
                }),
            },
            BlockItem {
                name: "rpuratd0_clr",
                description: Some(
                    "Protected register address = (RPURATD register index X 32 + RPURATD bit index) X 4. (write-1-to-clr alias)",
                ),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rpuratd0"),
                }),
            },
            BlockItem {
                name: "rpuratd0_tgl",
                description: Some(
                    "Protected register address = (RPURATD register index X 32 + RPURATD bit index) X 4. (write-1-to-tgl alias)",
                ),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rpuratd0"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Rfimdcdcctrl0",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "txmaxreq",
                    description: Some("TX Max Req."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxppreq",
                    description: Some("RX PP Req."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rfimdcdcctrl1",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "dcdcdiven",
                    description: Some("DCDC DIV Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dcdcdivinven",
                    description: Some("DCDC DIV Inverter Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dcdcdivratio",
                    description: Some("DCDC DIV Ratio."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Dcdcdivratio"),
                },
            ],
        },
        FieldSet {
            name: "Rfimdcdcctrl2",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "pptmax",
                    description: Some("Pulse Pairing Time Max."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pptmin",
                    description: Some("Pulse Pairing Time Min."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ppnd",
                    description: Some("Pulse Pairing Period."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ppcalen",
                    description: Some("Pulse Pairing Calibration Loop Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ppsynconly",
                    description: Some("Pulse Pairing Sync Only."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rfimdcdcstatus",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "dcdcen",
                    description: Some("DCDC Enable Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txmaxstatus",
                    description: Some("TX MAX Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxppstatus",
                    description: Some("RX PP Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wno1",
                    description: Some("Cal Loop WNO1 value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 9,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rpuratd0",
            extends: None,
            description: Some("Protected register address = (RPURATD register index X 32 + RPURATD bit index) X 4."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ratdrfimdcdcctrl0",
                    description: Some("RFIMDCDCCTRL0 Protection Bit."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ratdrfimdcdcctrl1",
                    description: Some("RFIMDCDCCTRL1 Protection Bit."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ratdrfimdcdcctrl2",
                    description: Some("RFIMDCDCCTRL2 Protection Bit."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[Enum {
        name: "Dcdcdivratio",
        description: None,
        bit_size: 4,
        variants: &[
            EnumVariant {
                name: "Divratio10",
                description: Some("Dividing master_rf clk by 10, D=40%."),
                value: 2,
            },
            EnumVariant {
                name: "Divratio11",
                description: Some("Dividing master_rf clk by 11, D=36.4%."),
                value: 3,
            },
            EnumVariant {
                name: "Divratio12",
                description: Some("Dividing master_rf clk by 12, D=50%."),
                value: 4,
            },
            EnumVariant {
                name: "Divratio13",
                description: Some("Dividing master_rf clk by 13, D=46.2%."),
                value: 5,
            },
            EnumVariant {
                name: "Divratio14",
                description: Some("Dividing master_rf clk by 14, D=42.9%."),
                value: 6,
            },
            EnumVariant {
                name: "Divratio15",
                description: Some("Dividing master_rf clk by 15, D=40%."),
                value: 7,
            },
            EnumVariant {
                name: "Divratio16",
                description: Some("Dividing master_rf clk by 16, D=50%."),
                value: 8,
            },
            EnumVariant {
                name: "Divratio17",
                description: Some("Dividing master_rf clk by 17, D=47.1%."),
                value: 9,
            },
            EnumVariant {
                name: "Divratio18",
                description: Some("Dividing master_rf clk by 18, D=44.4%."),
                value: 10,
            },
            EnumVariant {
                name: "Divratio19",
                description: Some("Dividing master_rf clk by 19, D=42.1%."),
                value: 11,
            },
            EnumVariant {
                name: "Divratio20",
                description: Some("Dividing master_rf clk by 20, D=60%."),
                value: 12,
            },
            EnumVariant {
                name: "Divratio21",
                description: Some("Dividing master_rf clk by 21, D=57.1%."),
                value: 13,
            },
            EnumVariant {
                name: "Divratio22",
                description: Some("Dividing master_rf clk by 22, D=54.5%."),
                value: 14,
            },
            EnumVariant {
                name: "Divratio23",
                description: Some("Dividing master_rf clk by 23, D=52.2%."),
                value: 15,
            },
            EnumVariant {
                name: "Divratio8",
                description: Some("Dividing master_rf clk by 8, D=50%."),
                value: 0,
            },
            EnumVariant {
                name: "Divratio9",
                description: Some("Dividing master_rf clk by 9, D=44.4%."),
                value: 1,
            },
        ],
    }],
};
