use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Prortc",
        extends: None,
        description: Some("PRORTC peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "precnt",
                description: Some("No Description."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Precnt"),
                }),
            },
            BlockItem {
                name: "cnt",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cnt"),
                }),
            },
            BlockItem {
                name: "combcnt",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Combcnt"),
                }),
            },
            BlockItem {
                name: "syncbusy",
                description: Some("No Description."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Syncbusy"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("No Description."),
                array: None,
                byte_offset: 44,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "cc0_ctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 48,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc0Ctrl"),
                }),
            },
            BlockItem {
                name: "cc0_ocvalue",
                description: Some("No Description."),
                array: None,
                byte_offset: 52,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc0Ocvalue"),
                }),
            },
            BlockItem {
                name: "cc0_icvalue",
                description: Some("No Description."),
                array: None,
                byte_offset: 56,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Cc0Icvalue"),
                }),
            },
            BlockItem {
                name: "cc1_ctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 60,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc1Ctrl"),
                }),
            },
            BlockItem {
                name: "cc1_ocvalue",
                description: Some("No Description."),
                array: None,
                byte_offset: 64,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cc1Ocvalue"),
                }),
            },
            BlockItem {
                name: "cc1_icvalue",
                description: Some("No Description."),
                array: None,
                byte_offset: 68,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Cc1Icvalue"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cc0Ctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mode",
                    description: Some("CC Channel Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Cc0CtrlMode"),
                },
                Field {
                    name: "cmoa",
                    description: Some("Compare Match Output Action."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Cc0CtrlCmoa"),
                },
                Field {
                    name: "compbase",
                    description: Some("Capture compare channel comparison base."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Cc0CtrlCompbase"),
                },
                Field {
                    name: "icedge",
                    description: Some("Input Capture Edge Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Cc0CtrlIcedge"),
                },
            ],
        },
        FieldSet {
            name: "Cc0Icvalue",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ic",
                description: Some("Input Capture Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cc0Ocvalue",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "oc",
                description: Some("Output Compare Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cc1Ctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mode",
                    description: Some("CC Channel Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Cc1CtrlMode"),
                },
                Field {
                    name: "cmoa",
                    description: Some("Compare Match Output Action."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Cc1CtrlCmoa"),
                },
                Field {
                    name: "compbase",
                    description: Some("Capture compare channel comparison base."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Cc1CtrlCompbase"),
                },
                Field {
                    name: "icedge",
                    description: Some("Input Capture Edge Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Cc1CtrlIcedge"),
                },
            ],
        },
        FieldSet {
            name: "Cc1Icvalue",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ic",
                description: Some("Input Capture Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cc1Ocvalue",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "oc",
                description: Some("Output Compare Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "debugrun",
                    description: Some("Debug Mode Run Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Debugrun"),
                },
                Field {
                    name: "precntccv0top",
                    description: Some("Pre-counter CCV0 top value enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cntccv1top",
                    description: Some("CCV1 top value enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cnttick",
                    description: Some("Counter prescaler mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Cnttick"),
                },
                Field {
                    name: "cntpresc",
                    description: Some("Counter prescaler value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Cntpresc"),
                },
            ],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "start",
                    description: Some("Start RTCC main counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "stop",
                    description: Some("Stop RTCC main counter."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Cnt",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "cnt",
                description: Some("Counter Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Combcnt",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "precnt",
                    description: Some("Pre-Counter Value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 15,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cntlsb",
                    description: Some("Counter Value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 17,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "en",
                description: Some("RTCC Enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "of",
                    description: Some("OF Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cnttick",
                    description: Some("CNTTICK Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cc0",
                    description: Some("CC Channel n Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cc1",
                    description: Some("CC Channel n Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "of",
                    description: Some("Overflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cnttick",
                    description: Some("Main counter tick."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cc0",
                    description: Some("CC Channel n Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cc1",
                    description: Some("CC Channel n Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP VERSION."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lockkey",
                description: Some("Configuration Lock Key."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("Lockkey"),
            }],
        },
        FieldSet {
            name: "Precnt",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "precnt",
                description: Some("Pre-Counter Value."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 15,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "running",
                    description: Some("RTCC running status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rtcclockstatus",
                    description: Some("Lock Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Syncbusy",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "start",
                    description: Some("Sync busy for START."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "stop",
                    description: Some("Sync busy for STOP."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "precnt",
                    description: Some("Sync busy for PRECNT."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cnt",
                    description: Some("Sync busy for CNT."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Cc0CtrlCmoa",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Clear",
                    description: Some("Clear output on compare match."),
                    value: 2,
                },
                EnumVariant {
                    name: "Pulse",
                    description: Some("A single clock cycle pulse is generated on output."),
                    value: 0,
                },
                EnumVariant {
                    name: "Set",
                    description: Some("Set output on compare match."),
                    value: 3,
                },
                EnumVariant {
                    name: "Toggle",
                    description: Some("Toggle output on compare match."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Cc0CtrlCompbase",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Cnt",
                    description: Some("RTCC_CCx_ICVALUE/OCVALUE is compared with CNT register."),
                    value: 0,
                },
                EnumVariant {
                    name: "Precnt",
                    description: Some("Least significant bits of RTCC_CCx_ICVALUE/OCVALUE are compared with COMBCNT."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Cc0CtrlIcedge",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Both",
                    description: Some("Both edges detected."),
                    value: 2,
                },
                EnumVariant {
                    name: "Falling",
                    description: Some("Falling edges detected."),
                    value: 1,
                },
                EnumVariant {
                    name: "None",
                    description: Some("No edge detection, signal is left as it is."),
                    value: 3,
                },
                EnumVariant {
                    name: "Rising",
                    description: Some("Rising edges detected."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Cc0CtrlMode",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Inputcapture",
                    description: Some("Input capture."),
                    value: 1,
                },
                EnumVariant {
                    name: "Off",
                    description: Some("Compare/Capture channel turned off."),
                    value: 0,
                },
                EnumVariant {
                    name: "Outputcompare",
                    description: Some("Output compare."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Cc1CtrlCmoa",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Clear",
                    description: Some("Clear output on compare match."),
                    value: 2,
                },
                EnumVariant {
                    name: "Pulse",
                    description: Some("A single clock cycle pulse is generated on output."),
                    value: 0,
                },
                EnumVariant {
                    name: "Set",
                    description: Some("Set output on compare match."),
                    value: 3,
                },
                EnumVariant {
                    name: "Toggle",
                    description: Some("Toggle output on compare match."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Cc1CtrlCompbase",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Cnt",
                    description: Some("RTCC_CCx_ICVALUE/OCVALUE is compared with CNT register."),
                    value: 0,
                },
                EnumVariant {
                    name: "Precnt",
                    description: Some("Least significant bits of RTCC_CCx_ICVALUE/OCVALUE are compared with COMBCNT."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Cc1CtrlIcedge",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Both",
                    description: Some("Both edges detected."),
                    value: 2,
                },
                EnumVariant {
                    name: "Falling",
                    description: Some("Falling edges detected."),
                    value: 1,
                },
                EnumVariant {
                    name: "None",
                    description: Some("No edge detection, signal is left as it is."),
                    value: 3,
                },
                EnumVariant {
                    name: "Rising",
                    description: Some("Rising edges detected."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Cc1CtrlMode",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Inputcapture",
                    description: Some("Input capture."),
                    value: 1,
                },
                EnumVariant {
                    name: "Off",
                    description: Some("Compare/Capture channel turned off."),
                    value: 0,
                },
                EnumVariant {
                    name: "Outputcompare",
                    description: Some("Output compare."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Cntpresc",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Div1",
                    description: Some("CLK_CNT = (RTCC LF CLK)/1."),
                    value: 0,
                },
                EnumVariant {
                    name: "Div1024",
                    description: Some("CLK_CNT = (RTCC LF CLK)/1024."),
                    value: 10,
                },
                EnumVariant {
                    name: "Div128",
                    description: Some("CLK_CNT = (RTCC LF CLK)/128."),
                    value: 7,
                },
                EnumVariant {
                    name: "Div16",
                    description: Some("CLK_CNT = (RTCC LF CLK)/16."),
                    value: 4,
                },
                EnumVariant {
                    name: "Div16384",
                    description: Some("CLK_CNT = (RTCC LF CLK)/16384."),
                    value: 14,
                },
                EnumVariant {
                    name: "Div2",
                    description: Some("CLK_CNT = (RTCC LF CLK)/2."),
                    value: 1,
                },
                EnumVariant {
                    name: "Div2048",
                    description: Some("CLK_CNT = (RTCC LF CLK)/2048."),
                    value: 11,
                },
                EnumVariant {
                    name: "Div256",
                    description: Some("CLK_CNT = (RTCC LF CLK)/256."),
                    value: 8,
                },
                EnumVariant {
                    name: "Div32",
                    description: Some("CLK_CNT = (RTCC LF CLK)/32."),
                    value: 5,
                },
                EnumVariant {
                    name: "Div32768",
                    description: Some("CLK_CNT = (RTCC LF CLK)/32768."),
                    value: 15,
                },
                EnumVariant {
                    name: "Div4",
                    description: Some("CLK_CNT = (RTCC LF CLK)/4."),
                    value: 2,
                },
                EnumVariant {
                    name: "Div4096",
                    description: Some("CLK_CNT = (RTCC LF CLK)/4096."),
                    value: 12,
                },
                EnumVariant {
                    name: "Div512",
                    description: Some("CLK_CNT = (RTCC LF CLK)/512."),
                    value: 9,
                },
                EnumVariant {
                    name: "Div64",
                    description: Some("CLK_CNT = (RTCC LF CLK)/64."),
                    value: 6,
                },
                EnumVariant {
                    name: "Div8",
                    description: Some("CLK_CNT = (RTCC LF CLK)/8."),
                    value: 3,
                },
                EnumVariant {
                    name: "Div8192",
                    description: Some("CLK_CNT = (RTCC LF CLK)/8192."),
                    value: 13,
                },
            ],
        },
        Enum {
            name: "Cnttick",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Ccv0match",
                    description: Some("CNT register ticks when PRECNT matches RTCC_CC0_OC[14:0]."),
                    value: 1,
                },
                EnumVariant {
                    name: "Presc",
                    description: Some("CNT register ticks according to configuration in CNTPRESC."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Debugrun",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "X0",
                    description: Some("RTCC is frozen in debug mode."),
                    value: 0,
                },
                EnumVariant {
                    name: "X1",
                    description: Some("RTCC is running in debug mode."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Lockkey",
            description: None,
            bit_size: 16,
            variants: &[EnumVariant {
                name: "Unlock",
                description: Some("Write to unlock RTCC lockable registers."),
                value: 44776,
            }],
        },
    ],
};
