use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "SemailboxNsHost",
        extends: None,
        description: Some("SEMAILBOX_NS_HOST peripheral."),
        items: &[
            BlockItem {
                name: "fifo",
                description: Some(
                    "A write access to any address in this area will be mapped to the TX FIFO (only for the payload). A read access to any address in this area will be mapped to the RX FIFO (only for the payload). Using an address range (16 x 32-bit) rather than one single address mapped to the FIFO allows using incremental bursts.",
                ),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Fifo"),
                }),
            },
            BlockItem {
                name: "tx_status",
                description: Some("TX Status register."),
                array: None,
                byte_offset: 64,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("TxStatus"),
                }),
            },
            BlockItem {
                name: "rx_status",
                description: Some("RX Status register."),
                array: None,
                byte_offset: 68,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("RxStatus"),
                }),
            },
            BlockItem {
                name: "tx_prot",
                description: Some("TX Protection register."),
                array: None,
                byte_offset: 72,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("TxProt"),
                }),
            },
            BlockItem {
                name: "rx_prot",
                description: Some("RX Protection register."),
                array: None,
                byte_offset: 76,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("RxProt"),
                }),
            },
            BlockItem {
                name: "tx_header",
                description: Some("A write access to this register will be mapped to the TX FIFO (only for header)."),
                array: None,
                byte_offset: 80,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("TxHeader"),
                }),
            },
            BlockItem {
                name: "rx_header",
                description: Some(
                    "A read access to this register will be mapped to the RX FIFO (only for the header).",
                ),
                array: None,
                byte_offset: 84,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("RxHeader"),
                }),
            },
            BlockItem {
                name: "configuration",
                description: Some("Configuration register."),
                array: None,
                byte_offset: 88,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Configuration"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Configuration",
            extends: None,
            description: Some("Configuration register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "txinten",
                    description: Some("TXINTEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxinten",
                    description: Some("RXINTEN."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Fifo",
            extends: None,
            description: Some(
                "A write access to any address in this area will be mapped to the TX FIFO (only for the payload). A read access to any address in this area will be mapped to the RX FIFO (only for the payload). Using an address range (16 x 32-bit) rather than one single address mapped to the FIFO allows using incremental bursts.",
            ),
            bit_size: 32,
            fields: &[Field {
                name: "fifo",
                description: Some("FIFO."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "RxHeader",
            extends: None,
            description: Some("A read access to this register will be mapped to the RX FIFO (only for the header)."),
            bit_size: 32,
            fields: &[Field {
                name: "rxheader",
                description: Some("RXHEADER."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "RxProt",
            extends: None,
            description: Some("RX Protection register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "unprotected",
                    description: Some("UNPROTECTED."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "privileged",
                    description: Some("PRIVILEGED."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "nonsecure",
                    description: Some("NONSECURE."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "user",
                    description: Some("USER."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "RxStatus",
            extends: None,
            description: Some("RX Status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rembytes",
                    description: Some("REMBYTES."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "msginfo",
                    description: Some("MSGINFO."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxint",
                    description: Some("RXINT."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxempty",
                    description: Some("RXEMPTY."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxhdr",
                    description: Some("RXHDR."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rxerror",
                    description: Some("RXERROR."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "TxHeader",
            extends: None,
            description: Some("A write access to this register will be mapped to the TX FIFO (only for header)."),
            bit_size: 32,
            fields: &[Field {
                name: "txheader",
                description: Some("TXHEADER."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "TxProt",
            extends: None,
            description: Some("TX Protection register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "unprotected",
                    description: Some("UNPROTECTED."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "privileged",
                    description: Some("PRIVILEGED."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "nonsecure",
                    description: Some("NONSECURE."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "user",
                    description: Some("USER."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "TxStatus",
            extends: None,
            description: Some("TX Status register."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rembytes",
                    description: Some("REMBYTES."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 16,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "msginfo",
                    description: Some("MSGINFO."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txint",
                    description: Some("TXINT."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txfull",
                    description: Some("TXFULL."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "txerror",
                    description: Some("TXERROR."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[],
};
