use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Smu",
        extends: None,
        description: Some("SMU peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "m33ctrl",
                description: Some("Holds the M33 control settings."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("M33ctrl"),
                }),
            },
            BlockItem {
                name: "ppupatd0",
                description: Some("Set peripheral bits to 1 to mark as privileged access only."),
                array: None,
                byte_offset: 64,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ppupatd0"),
                }),
            },
            BlockItem {
                name: "ppupatd1",
                description: Some("Set peripheral bits to 1 to mark as privileged access only."),
                array: None,
                byte_offset: 68,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ppupatd1"),
                }),
            },
            BlockItem {
                name: "ppusatd0",
                description: Some("Set peripheral bits to 1 to mark as secure access only."),
                array: None,
                byte_offset: 96,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ppusatd0"),
                }),
            },
            BlockItem {
                name: "ppusatd1",
                description: Some("Set peripheral bits to 1 to mark as secure access only."),
                array: None,
                byte_offset: 100,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ppusatd1"),
                }),
            },
            BlockItem {
                name: "ppufs",
                description: Some("No Description."),
                array: None,
                byte_offset: 320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ppufs"),
                }),
            },
            BlockItem {
                name: "bmpupatd0",
                description: Some("Set master bits to 1 to mark as a privileged master."),
                array: None,
                byte_offset: 336,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Bmpupatd0"),
                }),
            },
            BlockItem {
                name: "bmpusatd0",
                description: Some("Set master bits to 1 to mark as a secure master."),
                array: None,
                byte_offset: 368,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Bmpusatd0"),
                }),
            },
            BlockItem {
                name: "bmpufs",
                description: Some("No Description."),
                array: None,
                byte_offset: 592,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Bmpufs"),
                }),
            },
            BlockItem {
                name: "bmpufsaddr",
                description: Some("No Description."),
                array: None,
                byte_offset: 596,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Bmpufsaddr"),
                }),
            },
            BlockItem {
                name: "esaurtypes0",
                description: Some("No Description."),
                array: None,
                byte_offset: 608,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Esaurtypes0"),
                }),
            },
            BlockItem {
                name: "esaurtypes1",
                description: Some("No Description."),
                array: None,
                byte_offset: 612,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Esaurtypes1"),
                }),
            },
            BlockItem {
                name: "esaumrb01",
                description: Some("No Description."),
                array: None,
                byte_offset: 624,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Esaumrb01"),
                }),
            },
            BlockItem {
                name: "esaumrb12",
                description: Some("No Description."),
                array: None,
                byte_offset: 628,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Esaumrb12"),
                }),
            },
            BlockItem {
                name: "esaumrb45",
                description: Some("No Description."),
                array: None,
                byte_offset: 640,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Esaumrb45"),
                }),
            },
            BlockItem {
                name: "esaumrb56",
                description: Some("No Description."),
                array: None,
                byte_offset: 644,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Esaumrb56"),
                }),
            },
            BlockItem {
                name: "lock_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "m33ctrl_set",
                description: Some("Holds the M33 control settings. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("M33ctrl"),
                }),
            },
            BlockItem {
                name: "m33ctrl_clr",
                description: Some("Holds the M33 control settings. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("M33ctrl"),
                }),
            },
            BlockItem {
                name: "m33ctrl_tgl",
                description: Some("Holds the M33 control settings. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("M33ctrl"),
                }),
            },
            BlockItem {
                name: "ppupatd0_set",
                description: Some("Set peripheral bits to 1 to mark as privileged access only. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4160,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppupatd0"),
                }),
            },
            BlockItem {
                name: "ppupatd0_clr",
                description: Some("Set peripheral bits to 1 to mark as privileged access only. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8256,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppupatd0"),
                }),
            },
            BlockItem {
                name: "ppupatd0_tgl",
                description: Some("Set peripheral bits to 1 to mark as privileged access only. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12352,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppupatd0"),
                }),
            },
            BlockItem {
                name: "ppupatd1_set",
                description: Some("Set peripheral bits to 1 to mark as privileged access only. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4164,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppupatd1"),
                }),
            },
            BlockItem {
                name: "ppupatd1_clr",
                description: Some("Set peripheral bits to 1 to mark as privileged access only. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8260,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppupatd1"),
                }),
            },
            BlockItem {
                name: "ppupatd1_tgl",
                description: Some("Set peripheral bits to 1 to mark as privileged access only. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12356,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppupatd1"),
                }),
            },
            BlockItem {
                name: "ppusatd0_set",
                description: Some("Set peripheral bits to 1 to mark as secure access only. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4192,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppusatd0"),
                }),
            },
            BlockItem {
                name: "ppusatd0_clr",
                description: Some("Set peripheral bits to 1 to mark as secure access only. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8288,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppusatd0"),
                }),
            },
            BlockItem {
                name: "ppusatd0_tgl",
                description: Some("Set peripheral bits to 1 to mark as secure access only. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12384,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppusatd0"),
                }),
            },
            BlockItem {
                name: "ppusatd1_set",
                description: Some("Set peripheral bits to 1 to mark as secure access only. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppusatd1"),
                }),
            },
            BlockItem {
                name: "ppusatd1_clr",
                description: Some("Set peripheral bits to 1 to mark as secure access only. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppusatd1"),
                }),
            },
            BlockItem {
                name: "ppusatd1_tgl",
                description: Some("Set peripheral bits to 1 to mark as secure access only. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12388,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ppusatd1"),
                }),
            },
            BlockItem {
                name: "bmpupatd0_set",
                description: Some("Set master bits to 1 to mark as a privileged master. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4432,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bmpupatd0"),
                }),
            },
            BlockItem {
                name: "bmpupatd0_clr",
                description: Some("Set master bits to 1 to mark as a privileged master. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8528,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bmpupatd0"),
                }),
            },
            BlockItem {
                name: "bmpupatd0_tgl",
                description: Some("Set master bits to 1 to mark as a privileged master. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12624,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bmpupatd0"),
                }),
            },
            BlockItem {
                name: "bmpusatd0_set",
                description: Some("Set master bits to 1 to mark as a secure master. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4464,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bmpusatd0"),
                }),
            },
            BlockItem {
                name: "bmpusatd0_clr",
                description: Some("Set master bits to 1 to mark as a secure master. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8560,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bmpusatd0"),
                }),
            },
            BlockItem {
                name: "bmpusatd0_tgl",
                description: Some("Set master bits to 1 to mark as a secure master. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12656,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Bmpusatd0"),
                }),
            },
            BlockItem {
                name: "esaurtypes0_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4704,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaurtypes0"),
                }),
            },
            BlockItem {
                name: "esaurtypes0_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8800,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaurtypes0"),
                }),
            },
            BlockItem {
                name: "esaurtypes0_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12896,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaurtypes0"),
                }),
            },
            BlockItem {
                name: "esaurtypes1_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4708,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaurtypes1"),
                }),
            },
            BlockItem {
                name: "esaurtypes1_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8804,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaurtypes1"),
                }),
            },
            BlockItem {
                name: "esaurtypes1_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12900,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaurtypes1"),
                }),
            },
            BlockItem {
                name: "esaumrb01_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4720,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb01"),
                }),
            },
            BlockItem {
                name: "esaumrb01_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8816,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb01"),
                }),
            },
            BlockItem {
                name: "esaumrb01_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12912,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb01"),
                }),
            },
            BlockItem {
                name: "esaumrb12_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4724,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb12"),
                }),
            },
            BlockItem {
                name: "esaumrb12_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8820,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb12"),
                }),
            },
            BlockItem {
                name: "esaumrb12_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12916,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb12"),
                }),
            },
            BlockItem {
                name: "esaumrb45_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4736,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb45"),
                }),
            },
            BlockItem {
                name: "esaumrb45_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8832,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb45"),
                }),
            },
            BlockItem {
                name: "esaumrb45_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12928,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb45"),
                }),
            },
            BlockItem {
                name: "esaumrb56_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4740,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb56"),
                }),
            },
            BlockItem {
                name: "esaumrb56_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8836,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb56"),
                }),
            },
            BlockItem {
                name: "esaumrb56_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12932,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Esaumrb56"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Bmpufs",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "bmpufsmasterid",
                description: Some("Bus Manager ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Bmpufsaddr",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "bmpufsaddr",
                description: Some("Fault Address."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Bmpupatd0",
            extends: None,
            description: Some("Set master bits to 1 to mark as a privileged master."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "radioaes",
                    description: Some("RADIO AES DMA privileged mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "radiosubsystem",
                    description: Some("RADIO subsystem manager privileged mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ldma",
                    description: Some("MCU LDMA privileged mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rfeca0",
                    description: Some("RFECA0 privileged mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rfeca1",
                    description: Some("RFECA1 privileged mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seextdma",
                    description: Some("SEEXTDMA privileged mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Bmpusatd0",
            extends: None,
            description: Some("Set master bits to 1 to mark as a secure master."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "radioaes",
                    description: Some("RADIOAES DMA secure mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "radiosubsystem",
                    description: Some("RADIO subsystem manager secure mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ldma",
                    description: Some("MCU LDMA secure mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rfeca0",
                    description: Some("RFECA0 secure mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rfeca1",
                    description: Some("RFECA1 secure mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seextdma",
                    description: Some("SEEXTDMA secure mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Esaumrb01",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "esaumrb01",
                description: Some("Moveable Region Boundary."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Esaumrb12",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "esaumrb12",
                description: Some("Moveable Region Boundary."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Esaumrb45",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "esaumrb45",
                description: Some("Moveable Region Boundary."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Esaumrb56",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "esaumrb56",
                description: Some("Moveable Region Boundary."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 16,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Esaurtypes0",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "esaur3ns",
                description: Some("Region 3 Non-Secure."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Esaurtypes1",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "esaur11ns",
                description: Some("Region 11 Non-Secure."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ppupriv",
                    description: Some("PPU Privilege Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ppuinst",
                    description: Some("PPU Instruction Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ppusec",
                    description: Some("PPU Security Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bmpusec",
                    description: Some("BMPU Security Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ppupriv",
                    description: Some("PPU Privilege Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ppuinst",
                    description: Some("PPU Instruction Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ppusec",
                    description: Some("PPU Security Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bmpusec",
                    description: Some("BMPU Security Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP Version."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "smulockkey",
                description: Some("No Description."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 24,
                array: None,
                enumm: Some("Smulockkey"),
            }],
        },
        FieldSet {
            name: "M33ctrl",
            extends: None,
            description: Some("Holds the M33 control settings."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "locksvtaircr",
                    description: Some("New BitField."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "locknsvtor",
                    description: Some("New BitField."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "locksmpu",
                    description: Some("New BitField."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "locknsmpu",
                    description: Some("New BitField."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "locksau",
                    description: Some("New BitField."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ppufs",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ppufsperiphid",
                description: Some("Peripheral ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 8,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ppupatd0",
            extends: None,
            description: Some("Set peripheral bits to 1 to mark as privileged access only."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "emu",
                    description: Some("EMU Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cmu",
                    description: Some("CMU Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hfrco0",
                    description: Some("HFRCO0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fsrco",
                    description: Some("FSRCO Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dpll0",
                    description: Some("DPLL0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lfxo",
                    description: Some("LFXO Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lfrco",
                    description: Some("LFRCO Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ulfrco",
                    description: Some("ULFRCO Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "msc",
                    description: Some("MSC Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "icache0",
                    description: Some("ICACHE0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prs",
                    description: Some("PRS Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "gpio",
                    description: Some("GPIO Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ldma",
                    description: Some("LDMA Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ldmaxbar",
                    description: Some("LDMAXBAR Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer0",
                    description: Some("TIMER0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer1",
                    description: Some("TIMER1 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer2",
                    description: Some("TIMER2 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer3",
                    description: Some("TIMER3 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer4",
                    description: Some("TIMER4 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "usart0",
                    description: Some("USART0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "burtc",
                    description: Some("BURTC Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i2c1",
                    description: Some("I2C1 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chiptestctrl",
                    description: Some("CHIPTESTCTRL Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syscfgcfgns",
                    description: Some("SYSCFGCFGNS Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syscfg",
                    description: Some("SYSCFG Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "buram",
                    description: Some("BURAM Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "gpcrc",
                    description: Some("GPCRC Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dcdc",
                    description: Some("DCDC Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hostmailbox",
                    description: Some("HOSTMAILBOX Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "eusart1",
                    description: Some("EUSART1 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sysrtc",
                    description: Some("SYSRTC Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ppupatd1",
            extends: None,
            description: Some("Set peripheral bits to 1 to mark as privileged access only."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "keyscan",
                    description: Some("KEYSCAN Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dmem",
                    description: Some("DMEM Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "radioaes",
                    description: Some("RADIOAES Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "smu",
                    description: Some("SMU Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "smucfgns",
                    description: Some("SMUCFGNS Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "letimer0",
                    description: Some("LETIMER0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iadc0",
                    description: Some("IADC0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "acmp0",
                    description: Some("ACMP0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "acmp1",
                    description: Some("ACMP1 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "amuxcp0",
                    description: Some("AMUXCP0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vdac0",
                    description: Some("VDAC0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vdac1",
                    description: Some("VDAC1 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pcnt",
                    description: Some("PCNT Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hfrco1",
                    description: Some("HFRCO1 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hfxo0",
                    description: Some("HFXO0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i2c0",
                    description: Some("I2C0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wdog0",
                    description: Some("WDOG0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wdog1",
                    description: Some("WDOG1 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "eusart0",
                    description: Some("EUSART0 Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "semailbox",
                    description: Some("SEMAILBOX Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ahbradio",
                    description: Some("AHBRADIO Privileged Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ppusatd0",
            extends: None,
            description: Some("Set peripheral bits to 1 to mark as secure access only."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "emu",
                    description: Some("EMU Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "cmu",
                    description: Some("CMU Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hfrco0",
                    description: Some("HFRCO0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fsrco",
                    description: Some("FSRCO Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dpll0",
                    description: Some("DPLL0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lfxo",
                    description: Some("LFXO Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "lfrco",
                    description: Some("LFRCO Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ulfrco",
                    description: Some("ULFRCO Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "msc",
                    description: Some("MSC Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "icache0",
                    description: Some("ICACHE0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prs",
                    description: Some("PRS Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "gpio",
                    description: Some("GPIO Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ldma",
                    description: Some("LDMA Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ldmaxbar",
                    description: Some("LDMAXBAR Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer0",
                    description: Some("TIMER0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer1",
                    description: Some("TIMER1 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer2",
                    description: Some("TIMER2 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer3",
                    description: Some("TIMER3 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timer4",
                    description: Some("TIMER4 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "usart0",
                    description: Some("USART0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "burtc",
                    description: Some("BURTC Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i2c1",
                    description: Some("I2C1 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "chiptestctrl",
                    description: Some("CHIPTESTCTRL Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syscfgcfgns",
                    description: Some("SYSCFGCFGNS Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syscfg",
                    description: Some("SYSCFG Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "buram",
                    description: Some("BURAM Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "gpcrc",
                    description: Some("GPCRC Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dcdc",
                    description: Some("DCDC Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hostmailbox",
                    description: Some("HOSTMAILBOX Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "eusart1",
                    description: Some("EUSART1 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sysrtc",
                    description: Some("SYSRTC Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ppusatd1",
            extends: None,
            description: Some("Set peripheral bits to 1 to mark as secure access only."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "keyscan",
                    description: Some("KEYSCAN Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dmem",
                    description: Some("DMEM Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "radioaes",
                    description: Some("RADIOAES Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "smu",
                    description: Some("SMU Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "smucfgns",
                    description: Some("SMUCFGNS Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "letimer0",
                    description: Some("LETIMER0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "iadc0",
                    description: Some("IADC0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "acmp0",
                    description: Some("ACMP0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "acmp1",
                    description: Some("ACMP1 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "amuxcp0",
                    description: Some("AMUXCP0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vdac0",
                    description: Some("VDAC0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vdac1",
                    description: Some("VDAC1 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pcnt",
                    description: Some("PCNT Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hfrco1",
                    description: Some("HFRCO1 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "hfxo0",
                    description: Some("HFXO0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "i2c0",
                    description: Some("I2C0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wdog0",
                    description: Some("WDOG0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wdog1",
                    description: Some("WDOG1 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "eusart0",
                    description: Some("EUSART0 Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "semailbox",
                    description: Some("SEMAILBOX Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ahbradio",
                    description: Some("AHBRADIO Secure Access."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "smulock",
                    description: Some("SMU Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "smuprgerr",
                    description: Some("SMU Programming Error."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[Enum {
        name: "Smulockkey",
        description: None,
        bit_size: 24,
        variants: &[EnumVariant {
            name: "Unlock",
            description: Some("Unlocks Registers."),
            value: 11325013,
        }],
    }],
};
