use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Syscfg",
        extends: None,
        description: Some("SYSCFG peripheral."),
        items: &[
            BlockItem {
                name: "if_",
                description: Some("Read to get system status."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("Write to enable interrupts."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "chiprevhw",
                description: Some("Read to get the hard-wired chip revision."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Chiprevhw"),
                }),
            },
            BlockItem {
                name: "chiprev",
                description: Some("Read to get the chip revision programmed by feature configuration."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Chiprev"),
                }),
            },
            BlockItem {
                name: "cfgsystic",
                description: Some("Configure the source of the system tick for the M33."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfgsystic"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("Configure to provide general RAM configuration."),
                array: None,
                byte_offset: 512,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "dmem0retnctrl",
                description: Some("Configure to provide general RAM retention configuration."),
                array: None,
                byte_offset: 520,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dmem0retnctrl"),
                }),
            },
            BlockItem {
                name: "dmem0eccaddr",
                description: Some("Read to get status of the DMEM0 ECC error address."),
                array: None,
                byte_offset: 528,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Dmem0eccaddr"),
                }),
            },
            BlockItem {
                name: "dmem0eccctrl",
                description: Some("Configure to set RAM ECC control."),
                array: None,
                byte_offset: 532,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dmem0eccctrl"),
                }),
            },
            BlockItem {
                name: "radioramretnctrl",
                description: Some("Configure SEQRAM Retention controls."),
                array: None,
                byte_offset: 1024,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Radioramretnctrl"),
                }),
            },
            BlockItem {
                name: "radioeccctrl",
                description: Some("Configure to set RAM ECC control."),
                array: None,
                byte_offset: 1032,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Radioeccctrl"),
                }),
            },
            BlockItem {
                name: "seqrameccaddr",
                description: Some("Read to get status of the SEQRAM ECC error address."),
                array: None,
                byte_offset: 1040,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Seqrameccaddr"),
                }),
            },
            BlockItem {
                name: "frcrameccaddr",
                description: Some("Read to get status of the FRCRAM ECC error address."),
                array: None,
                byte_offset: 1044,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Frcrameccaddr"),
                }),
            },
            BlockItem {
                name: "rootdata0",
                description: Some("Data in this register is passed to the trusted root firmware upon reset."),
                array: None,
                byte_offset: 1536,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rootdata0"),
                }),
            },
            BlockItem {
                name: "rootdata1",
                description: Some("Data in this register is passed to the trusted root firmware upon reset."),
                array: None,
                byte_offset: 1540,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rootdata1"),
                }),
            },
            BlockItem {
                name: "rootlockstatus",
                description: Some("This register returns the status of the SE managed locks."),
                array: None,
                byte_offset: 1544,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Rootlockstatus"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("Read to get system status. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4096,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("Read to get system status. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8192,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("Read to get system status. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12288,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("Write to enable interrupts. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("Write to enable interrupts. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("Write to enable interrupts. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "chiprevhw_set",
                description: Some("Read to get the hard-wired chip revision. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4112,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprevhw"),
                }),
            },
            BlockItem {
                name: "chiprevhw_clr",
                description: Some("Read to get the hard-wired chip revision. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8208,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprevhw"),
                }),
            },
            BlockItem {
                name: "chiprevhw_tgl",
                description: Some("Read to get the hard-wired chip revision. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12304,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprevhw"),
                }),
            },
            BlockItem {
                name: "chiprev_set",
                description: Some(
                    "Read to get the chip revision programmed by feature configuration. (write-1-to-set alias)",
                ),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprev"),
                }),
            },
            BlockItem {
                name: "chiprev_clr",
                description: Some(
                    "Read to get the chip revision programmed by feature configuration. (write-1-to-clr alias)",
                ),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprev"),
                }),
            },
            BlockItem {
                name: "chiprev_tgl",
                description: Some(
                    "Read to get the chip revision programmed by feature configuration. (write-1-to-tgl alias)",
                ),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprev"),
                }),
            },
            BlockItem {
                name: "cfgsystic_set",
                description: Some("Configure the source of the system tick for the M33. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfgsystic"),
                }),
            },
            BlockItem {
                name: "cfgsystic_clr",
                description: Some("Configure the source of the system tick for the M33. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfgsystic"),
                }),
            },
            BlockItem {
                name: "cfgsystic_tgl",
                description: Some("Configure the source of the system tick for the M33. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfgsystic"),
                }),
            },
            BlockItem {
                name: "ctrl_set",
                description: Some("Configure to provide general RAM configuration. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4608,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_clr",
                description: Some("Configure to provide general RAM configuration. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8704,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_tgl",
                description: Some("Configure to provide general RAM configuration. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12800,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "dmem0retnctrl_set",
                description: Some("Configure to provide general RAM retention configuration. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4616,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0retnctrl"),
                }),
            },
            BlockItem {
                name: "dmem0retnctrl_clr",
                description: Some("Configure to provide general RAM retention configuration. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8712,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0retnctrl"),
                }),
            },
            BlockItem {
                name: "dmem0retnctrl_tgl",
                description: Some("Configure to provide general RAM retention configuration. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12808,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0retnctrl"),
                }),
            },
            BlockItem {
                name: "dmem0eccctrl_set",
                description: Some("Configure to set RAM ECC control. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4628,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0eccctrl"),
                }),
            },
            BlockItem {
                name: "dmem0eccctrl_clr",
                description: Some("Configure to set RAM ECC control. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8724,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0eccctrl"),
                }),
            },
            BlockItem {
                name: "dmem0eccctrl_tgl",
                description: Some("Configure to set RAM ECC control. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12820,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0eccctrl"),
                }),
            },
            BlockItem {
                name: "radioramretnctrl_set",
                description: Some("Configure SEQRAM Retention controls. (write-1-to-set alias)"),
                array: None,
                byte_offset: 5120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioramretnctrl"),
                }),
            },
            BlockItem {
                name: "radioramretnctrl_clr",
                description: Some("Configure SEQRAM Retention controls. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 9216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioramretnctrl"),
                }),
            },
            BlockItem {
                name: "radioramretnctrl_tgl",
                description: Some("Configure SEQRAM Retention controls. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 13312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioramretnctrl"),
                }),
            },
            BlockItem {
                name: "radioeccctrl_set",
                description: Some("Configure to set RAM ECC control. (write-1-to-set alias)"),
                array: None,
                byte_offset: 5128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioeccctrl"),
                }),
            },
            BlockItem {
                name: "radioeccctrl_clr",
                description: Some("Configure to set RAM ECC control. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 9224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioeccctrl"),
                }),
            },
            BlockItem {
                name: "radioeccctrl_tgl",
                description: Some("Configure to set RAM ECC control. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 13320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioeccctrl"),
                }),
            },
            BlockItem {
                name: "rootdata0_set",
                description: Some(
                    "Data in this register is passed to the trusted root firmware upon reset. (write-1-to-set alias)",
                ),
                array: None,
                byte_offset: 5632,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata0"),
                }),
            },
            BlockItem {
                name: "rootdata0_clr",
                description: Some(
                    "Data in this register is passed to the trusted root firmware upon reset. (write-1-to-clr alias)",
                ),
                array: None,
                byte_offset: 9728,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata0"),
                }),
            },
            BlockItem {
                name: "rootdata0_tgl",
                description: Some(
                    "Data in this register is passed to the trusted root firmware upon reset. (write-1-to-tgl alias)",
                ),
                array: None,
                byte_offset: 13824,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata0"),
                }),
            },
            BlockItem {
                name: "rootdata1_set",
                description: Some(
                    "Data in this register is passed to the trusted root firmware upon reset. (write-1-to-set alias)",
                ),
                array: None,
                byte_offset: 5636,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata1"),
                }),
            },
            BlockItem {
                name: "rootdata1_clr",
                description: Some(
                    "Data in this register is passed to the trusted root firmware upon reset. (write-1-to-clr alias)",
                ),
                array: None,
                byte_offset: 9732,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata1"),
                }),
            },
            BlockItem {
                name: "rootdata1_tgl",
                description: Some(
                    "Data in this register is passed to the trusted root firmware upon reset. (write-1-to-tgl alias)",
                ),
                array: None,
                byte_offset: 13828,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata1"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfgsystic",
            extends: None,
            description: Some("Configure the source of the system tick for the M33."),
            bit_size: 32,
            fields: &[Field {
                name: "systicextclken",
                description: Some("SysTick External Clock Enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Chiprev",
            extends: None,
            description: Some("Read to get the chip revision programmed by feature configuration."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "major",
                    description: Some("Chip Revision Major value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "family",
                    description: Some("Chip Family value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 6,
                    array: None,
                    enumm: Some("Family"),
                },
                Field {
                    name: "minor",
                    description: Some("Chip Revision Minor value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Chiprevhw",
            extends: None,
            description: Some("Read to get the hard-wired chip revision."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "major",
                    description: Some("Hardwired Chip Major value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "family",
                    description: Some("Hardwired Chip Family value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "minor",
                    description: Some("Hardwired Chip Minor value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("Configure to provide general RAM configuration."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "addrfaulten",
                    description: Some("Invalid Address Bus Fault Response Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rameccerrfaulten",
                    description: Some("Two bit ECC Error Bus Fault Response Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Dmem0eccaddr",
            extends: None,
            description: Some("Read to get status of the DMEM0 ECC error address."),
            bit_size: 32,
            fields: &[Field {
                name: "dmem0eccaddr",
                description: Some("DMEM0 RAM ECC Error Address."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Dmem0eccctrl",
            extends: None,
            description: Some("Configure to set RAM ECC control."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "rameccen",
                    description: Some("RAM ECC Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rameccewen",
                    description: Some("RAM ECC Error Writeback Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Dmem0retnctrl",
            extends: None,
            description: Some("Configure to provide general RAM retention configuration."),
            bit_size: 32,
            fields: &[Field {
                name: "ramretnctrl",
                description: Some("DMEM0 blockset retention control."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 2,
                array: None,
                enumm: Some("Ramretnctrl"),
            }],
        },
        FieldSet {
            name: "Frcrameccaddr",
            extends: None,
            description: Some("Read to get status of the FRCRAM ECC error address."),
            bit_size: 32,
            fields: &[Field {
                name: "frcrameccaddr",
                description: Some("FRCRAM ECC Error Address."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("Write to enable interrupts."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "sw0",
                    description: Some("Software interrupt 0."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw1",
                    description: Some("Software interrupt 1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw2",
                    description: Some("Software interrupt 2."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw3",
                    description: Some("Software interrupt 3."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ramerr1b",
                    description: Some("RAM 1-bit Error Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ramerr2b",
                    description: Some("RAM 2-bit Error Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqramerr1b",
                    description: Some("SEQRAM 1-bit Error Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqramerr2b",
                    description: Some("SEQRAM 2-bit Error Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcramerr1b",
                    description: Some("FRCRAM 1-bit Error Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcramerr2b",
                    description: Some("FRCRAM 2-bit Error Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("Read to get system status."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "sw0",
                    description: Some("Software Interrupt 0."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw1",
                    description: Some("Software Interrupt 1."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw2",
                    description: Some("Software Interrupt 2."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw3",
                    description: Some("Software Interrupt 3."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ramerr1b",
                    description: Some("RAM 1-Bit Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ramerr2b",
                    description: Some("RAM 2-Bit Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqramerr1b",
                    description: Some("SEQRAM 1-Bit Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqramerr2b",
                    description: Some("SEQRAM 2-Bit Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcramerr1b",
                    description: Some("FRCRAM 1-Bit Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcramerr2b",
                    description: Some("FRCRAM 2-Bit Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Radioeccctrl",
            extends: None,
            description: Some("Configure to set RAM ECC control."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "seqrameccen",
                    description: Some("SEQRAM ECC Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqrameccewen",
                    description: Some("SEQRAM ECC Error Writeback Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcrameccen",
                    description: Some("FRCRAM ECC Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcrameccewen",
                    description: Some("FRCRAM ECC Error Writeback Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Radioramretnctrl",
            extends: None,
            description: Some("Configure SEQRAM Retention controls."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "seqramretnctrl",
                    description: Some("SEQRAM Retention Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Seqramretnctrl"),
                },
                Field {
                    name: "frcramretnctrl",
                    description: Some("FRCRAM Retention Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rootdata0",
            extends: None,
            description: Some("Data in this register is passed to the trusted root firmware upon reset."),
            bit_size: 32,
            fields: &[Field {
                name: "data",
                description: Some("Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Rootdata1",
            extends: None,
            description: Some("Data in this register is passed to the trusted root firmware upon reset."),
            bit_size: 32,
            fields: &[Field {
                name: "data",
                description: Some("Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Rootlockstatus",
            extends: None,
            description: Some("This register returns the status of the SE managed locks."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "buslock",
                    description: Some("Bus Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "reglock",
                    description: Some("Register Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mfrlock",
                    description: Some("Manufacture Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rootmodelock",
                    description: Some("Root Mode Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rootdbglock",
                    description: Some("Root Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "userdbglock",
                    description: Some("User Invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "usernidlock",
                    description: Some("User Non-invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "userspidlock",
                    description: Some("User Secure Invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "userspnidlock",
                    description: Some("User Secure Non-invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "userdbgaplock",
                    description: Some("User Debug Access Port Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "radiodbglock",
                    description: Some("Radio Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Seqrameccaddr",
            extends: None,
            description: Some("Read to get status of the SEQRAM ECC error address."),
            bit_size: 32,
            fields: &[Field {
                name: "seqrameccaddr",
                description: Some("SEQRAM ECC Address."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[
        Enum {
            name: "Family",
            description: None,
            bit_size: 6,
            variants: &[
                EnumVariant {
                    name: "Bg22",
                    description: Some("Product is in BG22 family."),
                    value: 53,
                },
                EnumVariant {
                    name: "Fg22",
                    description: Some("Product is in FG22 family."),
                    value: 55,
                },
                EnumVariant {
                    name: "Mg22",
                    description: Some("Product is in MG22 family."),
                    value: 52,
                },
                EnumVariant {
                    name: "Pg22",
                    description: Some("Product is in PG22 family."),
                    value: 24,
                },
            ],
        },
        Enum {
            name: "Ramretnctrl",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Allon",
                    description: Some("None of the RAM blocks powered down."),
                    value: 0,
                },
                EnumVariant {
                    name: "Blk0",
                    description: Some("Power down RAM block 0."),
                    value: 1,
                },
                EnumVariant {
                    name: "Blk1",
                    description: Some("Power down RAM block 1."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Seqramretnctrl",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Alloff",
                    description: Some("Power down all SEQRAM blocks."),
                    value: 3,
                },
                EnumVariant {
                    name: "Allon",
                    description: Some("SEQRAM not powered down."),
                    value: 0,
                },
                EnumVariant {
                    name: "Blk0",
                    description: Some("Power down SEQRAM block 0."),
                    value: 1,
                },
                EnumVariant {
                    name: "Blk1",
                    description: Some("Power down SEQRAM block 1."),
                    value: 2,
                },
            ],
        },
    ],
};
