use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Syscfg",
        extends: None,
        description: Some("SYSCFG peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("Read to get system status."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("Write to enable interrupts."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "chiprevhw",
                description: Some("Read to get the hard-wired chip revision."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Chiprevhw"),
                }),
            },
            BlockItem {
                name: "chiprev",
                description: Some("Read to get the chip revision programmed by feature configuration."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Chiprev"),
                }),
            },
            BlockItem {
                name: "cfgsystic",
                description: Some("Configure the source of the system tick for the M33."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfgsystic"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("Configure to provide general RAM configuration."),
                array: None,
                byte_offset: 512,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "dmem0retnctrl",
                description: Some("Configure to provide general RAM retention configuration."),
                array: None,
                byte_offset: 520,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dmem0retnctrl"),
                }),
            },
            BlockItem {
                name: "rambiasconf",
                description: Some("Configure RAM bias configure bits."),
                array: None,
                byte_offset: 780,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rambiasconf"),
                }),
            },
            BlockItem {
                name: "radioramretnctrl",
                description: Some("Configure SEQRAM Retention controls."),
                array: None,
                byte_offset: 1024,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Radioramretnctrl"),
                }),
            },
            BlockItem {
                name: "radioeccctrl",
                description: Some("Configure to set RAM ECC control."),
                array: None,
                byte_offset: 1032,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Radioeccctrl"),
                }),
            },
            BlockItem {
                name: "seqrameccaddr",
                description: Some("Read to get status of the SEQRAM ECC error address."),
                array: None,
                byte_offset: 1040,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Seqrameccaddr"),
                }),
            },
            BlockItem {
                name: "frcrameccaddr",
                description: Some("Read to get status of the FRCRAM ECC error address."),
                array: None,
                byte_offset: 1044,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Frcrameccaddr"),
                }),
            },
            BlockItem {
                name: "icacheramretnctrl",
                description: Some("Configure Host ICACHERAM retention configuration."),
                array: None,
                byte_offset: 1048,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Icacheramretnctrl"),
                }),
            },
            BlockItem {
                name: "dmem0portmapsel",
                description: Some("Configure DMEM0 port remap selection."),
                array: None,
                byte_offset: 1052,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Dmem0portmapsel"),
                }),
            },
            BlockItem {
                name: "rootdata0",
                description: Some("Generic data space for user to pass to root, e.g., address of struct in mem."),
                array: None,
                byte_offset: 1536,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rootdata0"),
                }),
            },
            BlockItem {
                name: "rootdata1",
                description: Some("Generic data space for user to pass to root, e.g., address of struct in mem."),
                array: None,
                byte_offset: 1540,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rootdata1"),
                }),
            },
            BlockItem {
                name: "rootlockstatus",
                description: Some("This register returns the status of the SE managed locks."),
                array: None,
                byte_offset: 1544,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Rootlockstatus"),
                }),
            },
            BlockItem {
                name: "rootseswversion",
                description: Some("SE Software version."),
                array: None,
                byte_offset: 1548,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Rootseswversion"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("Read to get system status. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("Read to get system status. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("Read to get system status. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("Write to enable interrupts. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("Write to enable interrupts. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("Write to enable interrupts. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "chiprevhw_set",
                description: Some("Read to get the hard-wired chip revision. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprevhw"),
                }),
            },
            BlockItem {
                name: "chiprevhw_clr",
                description: Some("Read to get the hard-wired chip revision. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprevhw"),
                }),
            },
            BlockItem {
                name: "chiprevhw_tgl",
                description: Some("Read to get the hard-wired chip revision. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprevhw"),
                }),
            },
            BlockItem {
                name: "chiprev_set",
                description: Some(
                    "Read to get the chip revision programmed by feature configuration. (write-1-to-set alias)",
                ),
                array: None,
                byte_offset: 4120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprev"),
                }),
            },
            BlockItem {
                name: "chiprev_clr",
                description: Some(
                    "Read to get the chip revision programmed by feature configuration. (write-1-to-clr alias)",
                ),
                array: None,
                byte_offset: 8216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprev"),
                }),
            },
            BlockItem {
                name: "chiprev_tgl",
                description: Some(
                    "Read to get the chip revision programmed by feature configuration. (write-1-to-tgl alias)",
                ),
                array: None,
                byte_offset: 12312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Chiprev"),
                }),
            },
            BlockItem {
                name: "cfgsystic_set",
                description: Some("Configure the source of the system tick for the M33. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4132,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfgsystic"),
                }),
            },
            BlockItem {
                name: "cfgsystic_clr",
                description: Some("Configure the source of the system tick for the M33. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8228,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfgsystic"),
                }),
            },
            BlockItem {
                name: "cfgsystic_tgl",
                description: Some("Configure the source of the system tick for the M33. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12324,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfgsystic"),
                }),
            },
            BlockItem {
                name: "ctrl_set",
                description: Some("Configure to provide general RAM configuration. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4608,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_clr",
                description: Some("Configure to provide general RAM configuration. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8704,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "ctrl_tgl",
                description: Some("Configure to provide general RAM configuration. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12800,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "dmem0retnctrl_set",
                description: Some("Configure to provide general RAM retention configuration. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4616,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0retnctrl"),
                }),
            },
            BlockItem {
                name: "dmem0retnctrl_clr",
                description: Some("Configure to provide general RAM retention configuration. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8712,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0retnctrl"),
                }),
            },
            BlockItem {
                name: "dmem0retnctrl_tgl",
                description: Some("Configure to provide general RAM retention configuration. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12808,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0retnctrl"),
                }),
            },
            BlockItem {
                name: "rambiasconf_set",
                description: Some("Configure RAM bias configure bits. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4876,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rambiasconf"),
                }),
            },
            BlockItem {
                name: "rambiasconf_clr",
                description: Some("Configure RAM bias configure bits. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8972,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rambiasconf"),
                }),
            },
            BlockItem {
                name: "rambiasconf_tgl",
                description: Some("Configure RAM bias configure bits. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 13068,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rambiasconf"),
                }),
            },
            BlockItem {
                name: "radioramretnctrl_set",
                description: Some("Configure SEQRAM Retention controls. (write-1-to-set alias)"),
                array: None,
                byte_offset: 5120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioramretnctrl"),
                }),
            },
            BlockItem {
                name: "radioramretnctrl_clr",
                description: Some("Configure SEQRAM Retention controls. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 9216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioramretnctrl"),
                }),
            },
            BlockItem {
                name: "radioramretnctrl_tgl",
                description: Some("Configure SEQRAM Retention controls. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 13312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioramretnctrl"),
                }),
            },
            BlockItem {
                name: "radioeccctrl_set",
                description: Some("Configure to set RAM ECC control. (write-1-to-set alias)"),
                array: None,
                byte_offset: 5128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioeccctrl"),
                }),
            },
            BlockItem {
                name: "radioeccctrl_clr",
                description: Some("Configure to set RAM ECC control. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 9224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioeccctrl"),
                }),
            },
            BlockItem {
                name: "radioeccctrl_tgl",
                description: Some("Configure to set RAM ECC control. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 13320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Radioeccctrl"),
                }),
            },
            BlockItem {
                name: "icacheramretnctrl_set",
                description: Some("Configure Host ICACHERAM retention configuration. (write-1-to-set alias)"),
                array: None,
                byte_offset: 5144,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Icacheramretnctrl"),
                }),
            },
            BlockItem {
                name: "icacheramretnctrl_clr",
                description: Some("Configure Host ICACHERAM retention configuration. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 9240,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Icacheramretnctrl"),
                }),
            },
            BlockItem {
                name: "icacheramretnctrl_tgl",
                description: Some("Configure Host ICACHERAM retention configuration. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 13336,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Icacheramretnctrl"),
                }),
            },
            BlockItem {
                name: "dmem0portmapsel_set",
                description: Some("Configure DMEM0 port remap selection. (write-1-to-set alias)"),
                array: None,
                byte_offset: 5148,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0portmapsel"),
                }),
            },
            BlockItem {
                name: "dmem0portmapsel_clr",
                description: Some("Configure DMEM0 port remap selection. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 9244,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0portmapsel"),
                }),
            },
            BlockItem {
                name: "dmem0portmapsel_tgl",
                description: Some("Configure DMEM0 port remap selection. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 13340,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Dmem0portmapsel"),
                }),
            },
            BlockItem {
                name: "rootdata0_set",
                description: Some(
                    "Generic data space for user to pass to root, e.g., address of struct in mem. (write-1-to-set alias)",
                ),
                array: None,
                byte_offset: 5632,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata0"),
                }),
            },
            BlockItem {
                name: "rootdata0_clr",
                description: Some(
                    "Generic data space for user to pass to root, e.g., address of struct in mem. (write-1-to-clr alias)",
                ),
                array: None,
                byte_offset: 9728,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata0"),
                }),
            },
            BlockItem {
                name: "rootdata0_tgl",
                description: Some(
                    "Generic data space for user to pass to root, e.g., address of struct in mem. (write-1-to-tgl alias)",
                ),
                array: None,
                byte_offset: 13824,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata0"),
                }),
            },
            BlockItem {
                name: "rootdata1_set",
                description: Some(
                    "Generic data space for user to pass to root, e.g., address of struct in mem. (write-1-to-set alias)",
                ),
                array: None,
                byte_offset: 5636,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata1"),
                }),
            },
            BlockItem {
                name: "rootdata1_clr",
                description: Some(
                    "Generic data space for user to pass to root, e.g., address of struct in mem. (write-1-to-clr alias)",
                ),
                array: None,
                byte_offset: 9732,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata1"),
                }),
            },
            BlockItem {
                name: "rootdata1_tgl",
                description: Some(
                    "Generic data space for user to pass to root, e.g., address of struct in mem. (write-1-to-tgl alias)",
                ),
                array: None,
                byte_offset: 13828,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootdata1"),
                }),
            },
            BlockItem {
                name: "rootseswversion_set",
                description: Some("SE Software version. (write-1-to-set alias)"),
                array: None,
                byte_offset: 5644,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootseswversion"),
                }),
            },
            BlockItem {
                name: "rootseswversion_clr",
                description: Some("SE Software version. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 9740,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootseswversion"),
                }),
            },
            BlockItem {
                name: "rootseswversion_tgl",
                description: Some("SE Software version. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 13836,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Rootseswversion"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfgsystic",
            extends: None,
            description: Some("Configure the source of the system tick for the M33."),
            bit_size: 32,
            fields: &[Field {
                name: "systicextclken",
                description: Some("SysTick External Clock Enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Chiprev",
            extends: None,
            description: Some("Read to get the chip revision programmed by feature configuration."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "major",
                    description: Some("Chip Revision Major value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "family",
                    description: Some("Chip Family value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 6,
                    array: None,
                    enumm: Some("Family"),
                },
                Field {
                    name: "minor",
                    description: Some("Chip Revision Minor value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Chiprevhw",
            extends: None,
            description: Some("Read to get the hard-wired chip revision."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "major",
                    description: Some("Hardwired Chip Revision Major value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "family",
                    description: Some("Hardwired Chip Family value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "minor",
                    description: Some("Hardwired Chip Revision Minor value."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 8,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("Configure to provide general RAM configuration."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "addrfaulten",
                    description: Some("Invalid Address Bus Fault Response Enabl."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "clkdisfaulten",
                    description: Some("Disabled Clkbus Bus Fault Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rameccerrfaulten",
                    description: Some("Two bit ECC error bus fault response ena."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Dmem0portmapsel",
            extends: None,
            description: Some("Configure DMEM0 port remap selection."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ldmaportsel",
                    description: Some("LDMA portmap selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "srwaesportsel",
                    description: Some("SRWAES portmap selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ahbsrwportsel",
                    description: Some("AHBSRW portmap selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "srweca0portsel",
                    description: Some("SRWECA0 portmap selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 6 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "srweca1portsel",
                    description: Some("SRWECA1 portmap selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Dmem0retnctrl",
            extends: None,
            description: Some("Configure to provide general RAM retention configuration."),
            bit_size: 32,
            fields: &[Field {
                name: "ramretnctrl",
                description: Some("DMEM0 blockset retention control."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 15,
                array: None,
                enumm: Some("Dmem0retnctrlRamretnctrl"),
            }],
        },
        FieldSet {
            name: "Frcrameccaddr",
            extends: None,
            description: Some("Read to get status of the FRCRAM ECC error address."),
            bit_size: 32,
            fields: &[Field {
                name: "frcrameccaddr",
                description: Some("FRCRAM ECC Error Address."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Icacheramretnctrl",
            extends: None,
            description: Some("Configure Host ICACHERAM retention configuration."),
            bit_size: 32,
            fields: &[Field {
                name: "ramretnctrl",
                description: Some("ICACHERAM Retention control."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("Write to enable interrupts."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "sw0",
                    description: Some("Software Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw1",
                    description: Some("Software Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw2",
                    description: Some("Software Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw3",
                    description: Some("Software Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpioc",
                    description: Some("FPU Invalid Operation Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpdzc",
                    description: Some("FPU Divide by zero Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpufc",
                    description: Some("FPU Underflow Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpofc",
                    description: Some("FPU Overflow Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpidc",
                    description: Some("FPU Input denormal Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpixc",
                    description: Some("FPU Inexact Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "host2srwbuserr",
                    description: Some("HOST2SRWBUSERRIEN Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "srw2hostbuserr",
                    description: Some("SRW2HOSTBUSERRIEN Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqramerr1b",
                    description: Some("SEQRAM Error 1-bit Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqramerr2b",
                    description: Some("SEQRAM Error 2-bit Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcramerr1b",
                    description: Some("FRCRAM Error 1-bit Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcramerr2b",
                    description: Some("FRCRAM Error 2-bit Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("Read to get system status."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "sw0",
                    description: Some("Software Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw1",
                    description: Some("Software Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw2",
                    description: Some("Software Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sw3",
                    description: Some("Software Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpioc",
                    description: Some("FPU Invalid Operation interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpdzc",
                    description: Some("FPU Divide by zero interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpufc",
                    description: Some("FPU Underflow interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpofc",
                    description: Some("FPU Overflow interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpidc",
                    description: Some("FPU Input denormal interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fpixc",
                    description: Some("FPU Inexact interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 13 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "host2srwbuserr",
                    description: Some("HOST2SRWBUSERRIF Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "srw2hostbuserr",
                    description: Some("SRW2HOSTBUSERRIF Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqramerr1b",
                    description: Some("SEQRAM Error 1-bit Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqramerr2b",
                    description: Some("SEQRAM Error 2-bit Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcramerr1b",
                    description: Some("FRCRAM Error 1-bit Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcramerr2b",
                    description: Some("FRCRAM Error 2-bit Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("New BitField."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Radioeccctrl",
            extends: None,
            description: Some("Configure to set RAM ECC control."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "seqrameccen",
                    description: Some("SEQRAM ECC Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "seqrameccewen",
                    description: Some("SEQRAM ECC Error Writeback Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcrameccen",
                    description: Some("FRCRAM ECC Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "frcrameccewen",
                    description: Some("FRCRAM ECC Error Writeback Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Radioramretnctrl",
            extends: None,
            description: Some("Configure SEQRAM Retention controls."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "seqramretnctrl",
                    description: Some("SEQRAM Retention Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Seqramretnctrl"),
                },
                Field {
                    name: "frcramretnctrl",
                    description: Some("FRCRAM Retention Control."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rambiasconf",
            extends: None,
            description: Some("Configure RAM bias configure bits."),
            bit_size: 32,
            fields: &[Field {
                name: "rambiasctrl",
                description: Some("RAM Bias Control."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 4,
                array: None,
                enumm: Some("Rambiasctrl"),
            }],
        },
        FieldSet {
            name: "Rootdata0",
            extends: None,
            description: Some("Generic data space for user to pass to root, e.g., address of struct in mem."),
            bit_size: 32,
            fields: &[Field {
                name: "data",
                description: Some("Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Rootdata1",
            extends: None,
            description: Some("Generic data space for user to pass to root, e.g., address of struct in mem."),
            bit_size: 32,
            fields: &[Field {
                name: "data",
                description: Some("Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Rootlockstatus",
            extends: None,
            description: Some("This register returns the status of the SE managed locks."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "buslock",
                    description: Some("Bus Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "reglock",
                    description: Some("Register Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mfrlock",
                    description: Some("Manufacture Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "rootdbglock",
                    description: Some("Root Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "userdbgaplock",
                    description: Some("User Debug Access Port Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "userdbglock",
                    description: Some("User Invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "usernidlock",
                    description: Some("User Non-invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "userspidlock",
                    description: Some("User Secure Invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "userspnidlock",
                    description: Some("User Secure Non-invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "radioidbglock",
                    description: Some("Radio Invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "radionidbglock",
                    description: Some("Radio Non-invasive Debug Lock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "efuseunlocked",
                    description: Some("E-Fuse Unlocked."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Rootseswversion",
            extends: None,
            description: Some("SE Software version."),
            bit_size: 32,
            fields: &[Field {
                name: "swversion",
                description: Some("SW Version."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Seqrameccaddr",
            extends: None,
            description: Some("Read to get status of the SEQRAM ECC error address."),
            bit_size: 32,
            fields: &[Field {
                name: "seqrameccaddr",
                description: Some("SEQRAM ECC Address."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[
        Enum {
            name: "Dmem0retnctrlRamretnctrl",
            description: None,
            bit_size: 15,
            variants: &[
                EnumVariant {
                    name: "Allon",
                    description: Some("None of the RAM blocks powered down."),
                    value: 0,
                },
                EnumVariant {
                    name: "Blk10to15",
                    description: Some("Power down RAM blocks 10 and above (address range 0x20028000-0x20040000)."),
                    value: 32256,
                },
                EnumVariant {
                    name: "Blk11to15",
                    description: Some("Power down RAM blocks 11 and above (address range 0x2002C000-0x20040000)."),
                    value: 31744,
                },
                EnumVariant {
                    name: "Blk12to15",
                    description: Some("Power down RAM blocks 12 and above (address range 0x20030000-0x20040000)."),
                    value: 30720,
                },
                EnumVariant {
                    name: "Blk13to15",
                    description: Some("Power down RAM blocks 13 and above (address range 0x20034000-0x20040000)."),
                    value: 28672,
                },
                EnumVariant {
                    name: "Blk14to15",
                    description: Some("Power down RAM blocks 14 and above (address range 0x20038000-0x20040000)."),
                    value: 24576,
                },
                EnumVariant {
                    name: "Blk15",
                    description: Some("Power down RAM block 15 (address range 0x2003C000-0x20040000)."),
                    value: 16384,
                },
                EnumVariant {
                    name: "Blk1to15",
                    description: Some("Power down RAM blocks 1 and above (address range 0x20004000-0x20040000)."),
                    value: 32767,
                },
                EnumVariant {
                    name: "Blk2to15",
                    description: Some("Power down RAM blocks 2 and above (address range 0x20008000-0x20040000)."),
                    value: 32766,
                },
                EnumVariant {
                    name: "Blk3to15",
                    description: Some("Power down RAM blocks 3 and above (address range 0x2000C000-0x20040000)."),
                    value: 32764,
                },
                EnumVariant {
                    name: "Blk4to15",
                    description: Some("Power down RAM blocks 4 and above (address range 0x20010000-0x20040000)."),
                    value: 32760,
                },
                EnumVariant {
                    name: "Blk5to15",
                    description: Some("Power down RAM blocks 5 and above (address range 0x20014000-0x20040000)."),
                    value: 32752,
                },
                EnumVariant {
                    name: "Blk6to15",
                    description: Some("Power down RAM blocks 6 and above (address range 0x20018000-0x20040000)."),
                    value: 32736,
                },
                EnumVariant {
                    name: "Blk7to15",
                    description: Some("Power down RAM blocks 7 and above (address range 0x2001C000-0x20040000)."),
                    value: 32704,
                },
                EnumVariant {
                    name: "Blk8to15",
                    description: Some("Power down RAM blocks 8 and above (address range 0x20020000-0x20040000)."),
                    value: 32640,
                },
                EnumVariant {
                    name: "Blk9to15",
                    description: Some("Power down RAM blocks 9 and above (address range 0x20024000-0x20040000)."),
                    value: 32512,
                },
            ],
        },
        Enum {
            name: "Family",
            description: None,
            bit_size: 6,
            variants: &[
                EnumVariant {
                    name: "Bg24",
                    description: Some("Product is in BG24 family."),
                    value: 61,
                },
                EnumVariant {
                    name: "Mg24",
                    description: Some("Product is in MG24 family."),
                    value: 60,
                },
            ],
        },
        Enum {
            name: "Rambiasctrl",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "No",
                    description: Some("None."),
                    value: 0,
                },
                EnumVariant {
                    name: "Vsb100",
                    description: Some("Voltage Source Bias 100mV."),
                    value: 1,
                },
                EnumVariant {
                    name: "Vsb200",
                    description: Some("Voltage Source Bias 200mV."),
                    value: 2,
                },
                EnumVariant {
                    name: "Vsb300",
                    description: Some("Voltage Source Bias 300mV."),
                    value: 4,
                },
                EnumVariant {
                    name: "Vsb400",
                    description: Some("Voltage Source Bias 400mV."),
                    value: 8,
                },
            ],
        },
        Enum {
            name: "Seqramretnctrl",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Alloff",
                    description: Some("Power down all SEQRAM blocks."),
                    value: 3,
                },
                EnumVariant {
                    name: "Allon",
                    description: Some("SEQRAM not powered down."),
                    value: 0,
                },
                EnumVariant {
                    name: "Blk0",
                    description: Some("Power down SEQRAM block 0."),
                    value: 1,
                },
                EnumVariant {
                    name: "Blk1",
                    description: Some("Power down SEQRAM block 1."),
                    value: 2,
                },
            ],
        },
    ],
};
