use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "UsbSApbs",
        extends: None,
        description: Some("USB_S_APBS peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "ctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ctrl"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "cal",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cal"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cal",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "fsslewt",
                description: Some("FS slew."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                bit_size: 3,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "txdse0mxsel",
                    description: Some("TXD SE0 chicken bit."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vbssnshen",
                    description: Some("VBUSSENSE going high - enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vbssnslen",
                    description: Some("VBUSSENSE going low - enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 17 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "vbusovride",
                    description: Some("VBUS override to GPPLL."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "fsslew",
                    description: Some("FS Slew."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disruptx",
                    description: Some("Disable TX pull-up resistor."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "bypsvreg",
                    description: Some("Bypass VREG signal to USB PHY."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "endatacap",
                    description: Some("Add 40pf cap to D+/D- in TX mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("Module enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disabling",
                    description: Some("Disablement busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "vbus",
                    description: Some("VBUS_SENSE interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dwcotg",
                    description: Some("DWC_OTG interrupt enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "vbus",
                    description: Some("VBUS_SENSE interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dwcotg",
                    description: Some("DWC_OTG interrupt flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP Version ID."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "vbusvalid",
                description: Some("VBus valid."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[],
};
