use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Vdac",
        extends: None,
        description: Some("VDAC peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 16,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "ch0cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ch0cfg"),
                }),
            },
            BlockItem {
                name: "ch1cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ch1cfg"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ch0f",
                description: Some("No Description."),
                array: None,
                byte_offset: 40,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch0f"),
                }),
            },
            BlockItem {
                name: "ch1f",
                description: Some("No Description."),
                array: None,
                byte_offset: 44,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch1f"),
                }),
            },
            BlockItem {
                name: "outctrl",
                description: Some("No Description."),
                array: None,
                byte_offset: 48,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Outctrl"),
                }),
            },
            BlockItem {
                name: "outtimercfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 52,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Outtimercfg"),
                }),
            },
            BlockItem {
                name: "en_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "swrst_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "swrst_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Swrst"),
                }),
            },
            BlockItem {
                name: "cfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "ch0cfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4116,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch0cfg"),
                }),
            },
            BlockItem {
                name: "ch0cfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8212,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch0cfg"),
                }),
            },
            BlockItem {
                name: "ch0cfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12308,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch0cfg"),
                }),
            },
            BlockItem {
                name: "ch1cfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch1cfg"),
                }),
            },
            BlockItem {
                name: "ch1cfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch1cfg"),
                }),
            },
            BlockItem {
                name: "ch1cfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch1cfg"),
                }),
            },
            BlockItem {
                name: "cmd_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4124,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8220,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12316,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4132,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8228,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12324,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ch0f_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4136,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch0f"),
                }),
            },
            BlockItem {
                name: "ch0f_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8232,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch0f"),
                }),
            },
            BlockItem {
                name: "ch0f_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12328,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch0f"),
                }),
            },
            BlockItem {
                name: "ch1f_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4140,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch1f"),
                }),
            },
            BlockItem {
                name: "ch1f_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8236,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch1f"),
                }),
            },
            BlockItem {
                name: "ch1f_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12332,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ch1f"),
                }),
            },
            BlockItem {
                name: "outctrl_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4144,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Outctrl"),
                }),
            },
            BlockItem {
                name: "outctrl_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8240,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Outctrl"),
                }),
            },
            BlockItem {
                name: "outctrl_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12336,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Outctrl"),
                }),
            },
            BlockItem {
                name: "outtimercfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4148,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Outtimercfg"),
                }),
            },
            BlockItem {
                name: "outtimercfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8244,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Outtimercfg"),
                }),
            },
            BlockItem {
                name: "outtimercfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12340,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Outtimercfg"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "diff",
                    description: Some("Differential Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Diff"),
                },
                Field {
                    name: "sinemode",
                    description: Some("Sine Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Sinemode"),
                },
                Field {
                    name: "sinereset",
                    description: Some("Sine Wave Reset When inactive."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0prescrst",
                    description: Some("Channel 0 Start Reset Prescaler."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "refrsel",
                    description: Some("Reference Selection."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Refrsel"),
                },
                Field {
                    name: "presc",
                    description: Some("Prescaler Setting for DAC clock."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 7 }),
                    bit_size: 7,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "timerovrflowperiod",
                    description: Some("Internal Timer Overflow Period."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Timerovrflowperiod"),
                },
                Field {
                    name: "refreshperiod",
                    description: Some("Refresh Timer Overflow Period."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Refreshperiod"),
                },
                Field {
                    name: "biaskeepwarm",
                    description: Some("Bias Keepwarm Mode Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dmawu",
                    description: Some("VDAC DMA Wakeup."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ondemandclk",
                    description: Some("Always allow clk_dac."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "dbghalt",
                    description: Some("Debug Halt."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Dbghalt"),
                },
                Field {
                    name: "warmuptime",
                    description: Some("DAC Warmup Time."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ch0cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "convmode",
                    description: Some("Channel 0 Conversion Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Ch0cfgConvmode"),
                },
                Field {
                    name: "powermode",
                    description: Some("Channel 0 Power Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Ch0cfgPowermode"),
                },
                Field {
                    name: "trigmode",
                    description: Some("Channel 0 Trigger Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Ch0cfgTrigmode"),
                },
                Field {
                    name: "refreshsource",
                    description: Some("Channel 0 Refresh Source."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Ch0cfgRefreshsource"),
                },
                Field {
                    name: "fifodvl",
                    description: Some("Channel 0 FIFO Low Watermark."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "highcaploaden",
                    description: Some("Channel 0 High Cap Load Mode Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keepwarm",
                    description: Some("Channel 0 Keepwarm Mode Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ch0f",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "data",
                description: Some("Channel 0 Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 12,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ch1cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "convmode",
                    description: Some("Channel 1 Conversion Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Ch1cfgConvmode"),
                },
                Field {
                    name: "powermode",
                    description: Some("Channel 1 Power Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Ch1cfgPowermode"),
                },
                Field {
                    name: "trigmode",
                    description: Some("Channel 1 Trigger Mode."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Ch1cfgTrigmode"),
                },
                Field {
                    name: "refreshsource",
                    description: Some("Channel 1 Refresh Source."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Ch1cfgRefreshsource"),
                },
                Field {
                    name: "fifodvl",
                    description: Some("Channel 1 FIFO Low Watermark."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 2,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "highcaploaden",
                    description: Some("Channel 1 High Cap Load Mode Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 14 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "keepwarm",
                    description: Some("Channel 1 Keepwarm Mode Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ch1f",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "data",
                description: Some("Channel 1 Data."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 12,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ch0en",
                    description: Some("DAC Channel 0 Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0dis",
                    description: Some("DAC Channel 0 Disable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1en",
                    description: Some("DAC Channel 1 Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1dis",
                    description: Some("DAC Channel 1 Disable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0fifoflush",
                    description: Some("CH0 WFIFO Flush."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1fifoflush",
                    description: Some("CH1 WFIFO Flush."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sinemodestart",
                    description: Some("Start Sine Wave Generation."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sinemodestop",
                    description: Some("Stop Sine Wave Generation."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 11 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "en",
                    description: Some("VDAC Module Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "disabling",
                    description: Some("Disablement busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ch0cd",
                    description: Some("CH0 Conversion Done Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1cd",
                    description: Some("CH1 Conversion Done Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0of",
                    description: Some("CH0 Data Overflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1of",
                    description: Some("CH1 Data Overflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0uf",
                    description: Some("CH0 Data Underflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1uf",
                    description: Some("CH1 Data Underflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "abusallocerr",
                    description: Some("ABUS Allocation Error Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0dvl",
                    description: Some("CH0 Data Valid Level Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1dvl",
                    description: Some("CH1 Data Valid Level Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "abusinputconflict",
                    description: Some("ABUS Input Conflict Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ch0cd",
                    description: Some("CH0 Conversion Done Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1cd",
                    description: Some("CH1 Conversion Done Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0of",
                    description: Some("CH0 Data Overflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1of",
                    description: Some("CH1 Data Overflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0uf",
                    description: Some("CH0 Data Underflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1uf",
                    description: Some("CH1 Data Underflow Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "abusallocerr",
                    description: Some("ABUS Port Allocation Error Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 18 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0dvl",
                    description: Some("CH0 Data Valid Level Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1dvl",
                    description: Some("CH1 Data Valid Level Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 21 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "abusinputconflict",
                    description: Some("ABUS Input Conflict Error Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IPVERSION."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Outctrl",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "mainoutench0",
                    description: Some("CH0 Main Output Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "mainoutench1",
                    description: Some("CH1 Main Output Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "auxoutench0",
                    description: Some("CH0 Alternative Output Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "auxoutench1",
                    description: Some("CH1 Alternative Output Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "shortch0",
                    description: Some("CH1 Main and Alternative Output Short."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "shortch1",
                    description: Some("CH0 Main and Alternative Output Short."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "abusportselch0",
                    description: Some("CH0 ABUS Port Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Abusportselch0"),
                },
                Field {
                    name: "abuspinselch0",
                    description: Some("CH0 ABUS Pin Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "abusportselch1",
                    description: Some("CH1 ABUS Port Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Abusportselch1"),
                },
                Field {
                    name: "abuspinselch1",
                    description: Some("CH1 ABUS Pin Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 25 }),
                    bit_size: 6,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Outtimercfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ch0outholdtime",
                    description: Some("CH0 Output Hold Time."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 10,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1outholdtime",
                    description: Some("CH1 Output Hold Time."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 10,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "ch0ens",
                    description: Some("Channel 0 Enabled Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1ens",
                    description: Some("Channel 1 Enabled Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0warm",
                    description: Some("Channel 0 Warmed Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1warm",
                    description: Some("Channel 1 Warmed Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 5 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0fifofull",
                    description: Some("Channel 0 FIFO Full Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1fifofull",
                    description: Some("Channel 1 FIFO Full Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0fifocnt",
                    description: Some("Channel 0 FIFO Valid Count."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 12 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1fifocnt",
                    description: Some("Channel 1 FIFO Valid Count."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 15 }),
                    bit_size: 3,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0currentstate",
                    description: Some("Channel 0 Current Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 19 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1currentstate",
                    description: Some("Channel 1 Current Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 20 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0fifoempty",
                    description: Some("Channel 0 FIFO Empty Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 22 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1fifoempty",
                    description: Some("Channel 1 FIFO Empty Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 23 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch0fifoflbusy",
                    description: Some("CH0 FIFO Flush Sync Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 26 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "ch1fifoflbusy",
                    description: Some("CH1 FIFO Flush Sync Busy."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 27 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "abusinputconflict",
                    description: Some("ABUS Input Conflict Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "sineactive",
                    description: Some("Sine Wave Output Status on Channel."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 29 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "abusallocerr",
                    description: Some("ABUS Allocation Error Status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 30 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "syncbusy",
                    description: Some("Sync Busy Combined."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Swrst",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "swrst",
                    description: Some("Software reset command."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "resetting",
                    description: Some("Software reset busy status."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
    ],
    enums: &[
        Enum {
            name: "Abusportselch0",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "None",
                    description: Some("No GPIO Selected for CH0 ABUS Output."),
                    value: 0,
                },
                EnumVariant {
                    name: "Porta",
                    description: Some("Port A Selected."),
                    value: 1,
                },
                EnumVariant {
                    name: "Portb",
                    description: Some("Port B Selected."),
                    value: 2,
                },
                EnumVariant {
                    name: "Portc",
                    description: Some("Port C Selected."),
                    value: 3,
                },
                EnumVariant {
                    name: "Portd",
                    description: Some("Port D Selected."),
                    value: 4,
                },
            ],
        },
        Enum {
            name: "Abusportselch1",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "None",
                    description: Some("No GPIO Selected for CH1 ABUS Output."),
                    value: 0,
                },
                EnumVariant {
                    name: "Porta",
                    description: Some("Port A Selected."),
                    value: 1,
                },
                EnumVariant {
                    name: "Portb",
                    description: Some("Port B Selected."),
                    value: 2,
                },
                EnumVariant {
                    name: "Portc",
                    description: Some("Port C Selected."),
                    value: 3,
                },
                EnumVariant {
                    name: "Portd",
                    description: Some("Port D Selected."),
                    value: 4,
                },
            ],
        },
        Enum {
            name: "Ch0cfgConvmode",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Continuous",
                    description: Some("DAC channel 0 is set in continuous mode."),
                    value: 0,
                },
                EnumVariant {
                    name: "Sampleoff",
                    description: Some("DAC channel 0 is set in sample/shut off mode."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Ch0cfgPowermode",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Highpower",
                    description: Some("Default is High Power Mode."),
                    value: 0,
                },
                EnumVariant {
                    name: "Lowpower",
                    description: Some("Set this bit for Low Power Mode."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Ch0cfgRefreshsource",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Asyncprs",
                    description: Some("Channel 0 Refresh triggered by Async PRS."),
                    value: 3,
                },
                EnumVariant {
                    name: "None",
                    description: Some("No Refresh Source Selected for Channel 0."),
                    value: 0,
                },
                EnumVariant {
                    name: "Refreshtimer",
                    description: Some("Channel 0 Refresh triggered by Refresh Timer Overflow."),
                    value: 1,
                },
                EnumVariant {
                    name: "Syncprs",
                    description: Some(
                        "Channel 0 Refresh triggered by Sync PRS. PRS Trigger should have the same clock group as VDAC.",
                    ),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Ch0cfgTrigmode",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Asyncprs",
                    description: Some("Channel 0 is triggered by Async PRS input."),
                    value: 5,
                },
                EnumVariant {
                    name: "Internaltimer",
                    description: Some("Channel 0 is triggered by Internal Timer Overflow."),
                    value: 4,
                },
                EnumVariant {
                    name: "Lesense",
                    description: Some("Channel 0 is triggered by LESENSE."),
                    value: 3,
                },
                EnumVariant {
                    name: "None",
                    description: Some("No Conversion Trigger Source Selected for Channel 0."),
                    value: 0,
                },
                EnumVariant {
                    name: "Sw",
                    description: Some("Channel 0 is triggered by Channel 0 FIFO (CH0F) write."),
                    value: 1,
                },
                EnumVariant {
                    name: "Syncprs",
                    description: Some(
                        "Channel 0 is triggered by Sync PRS input. PRS Trigger should have the same clock group as VDAC.",
                    ),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Ch1cfgConvmode",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Continuous",
                    description: Some("DAC channel 1 is set in continuous mode."),
                    value: 0,
                },
                EnumVariant {
                    name: "Sampleoff",
                    description: Some("DAC channel 1 is set in sample/shut off mode."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Ch1cfgPowermode",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Highpower",
                    description: Some("Default is High Power Mode."),
                    value: 0,
                },
                EnumVariant {
                    name: "Lowpower",
                    description: Some("Set this bit for Low Power Mode."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Ch1cfgRefreshsource",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Asyncprs",
                    description: Some("CH1 Refresh Triggered by Async PRS."),
                    value: 3,
                },
                EnumVariant {
                    name: "None",
                    description: Some("No Refresh Source Selected."),
                    value: 0,
                },
                EnumVariant {
                    name: "Refreshtimer",
                    description: Some("CH1 Refresh Triggered by Refresh Timer Overflow."),
                    value: 1,
                },
                EnumVariant {
                    name: "Syncprs",
                    description: Some(
                        "CH1 Refresh Triggered by Sync PRS. PRS Trigger should have the same clock group as VDAC.",
                    ),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Ch1cfgTrigmode",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Asyncprs",
                    description: Some("Channel 1 is triggered by Async PRS input."),
                    value: 5,
                },
                EnumVariant {
                    name: "Internaltimer",
                    description: Some("Channel 1 is triggered by Internal Timer Overflow."),
                    value: 4,
                },
                EnumVariant {
                    name: "Lesense",
                    description: Some("Channel 1 is triggered by LESENSE."),
                    value: 3,
                },
                EnumVariant {
                    name: "None",
                    description: Some("No Conversion Trigger Source Selected for Channel 1."),
                    value: 0,
                },
                EnumVariant {
                    name: "Sw",
                    description: Some("Channel 1 is triggered by Channel 1 FIFO (CH1F) write."),
                    value: 1,
                },
                EnumVariant {
                    name: "Syncprs",
                    description: Some(
                        "Channel 1 is triggered by Sync PRS input.PRS Trigger should have the same clock group as VDAC.",
                    ),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Dbghalt",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Halt",
                    description: Some("Complete the current conversion and then halt during debug mode."),
                    value: 1,
                },
                EnumVariant {
                    name: "Normal",
                    description: Some("Continue operation as normal during debug mode."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Diff",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Differential",
                    description: Some("Differential output."),
                    value: 1,
                },
                EnumVariant {
                    name: "Singleended",
                    description: Some("Single ended output."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Refreshperiod",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Cycles128",
                    description: Some("All channels with enabled refresh are refreshed every 128 CLK_REFRESH cycles."),
                    value: 6,
                },
                EnumVariant {
                    name: "Cycles16",
                    description: Some("All channels with enabled refresh are refreshed every 16 CLK_REFRESH cycles."),
                    value: 3,
                },
                EnumVariant {
                    name: "Cycles2",
                    description: Some("All channels with enabled refresh are refreshed every 2 CLK_REFRESH cycles."),
                    value: 0,
                },
                EnumVariant {
                    name: "Cycles256",
                    description: Some("All channels with enabled refresh are refreshed every 256 CLK_REFRESH cycles."),
                    value: 7,
                },
                EnumVariant {
                    name: "Cycles32",
                    description: Some("All channels with enabled refresh are refreshed every 32 CLK_REFRESH cycles."),
                    value: 4,
                },
                EnumVariant {
                    name: "Cycles4",
                    description: Some("All channels with enabled refresh are refreshed every 4 CLK_REFRESH cycles."),
                    value: 1,
                },
                EnumVariant {
                    name: "Cycles64",
                    description: Some("All channels with enabled refresh are refreshed every 64 CLK_REFRESH cycles."),
                    value: 5,
                },
                EnumVariant {
                    name: "Cycles8",
                    description: Some("All channels with enabled refresh are refreshed every 8 CLK_REFRESH cycles."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Refrsel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Ext",
                    description: Some("External pin reference."),
                    value: 3,
                },
                EnumVariant {
                    name: "V125",
                    description: Some("Internal 1.25 V bandgap reference."),
                    value: 0,
                },
                EnumVariant {
                    name: "V25",
                    description: Some("Internal 2.5 V bandgap reference."),
                    value: 1,
                },
                EnumVariant {
                    name: "Vdd",
                    description: Some("AVDD reference."),
                    value: 2,
                },
            ],
        },
        Enum {
            name: "Sinemode",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Dissinemode",
                    description: Some("Sine mode disabled. Sine reset to 0 degrees."),
                    value: 0,
                },
                EnumVariant {
                    name: "Ensinemode",
                    description: Some("Sine mode enabled."),
                    value: 1,
                },
            ],
        },
        Enum {
            name: "Timerovrflowperiod",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Cycles16",
                    description: Some("The Timer overflows every 16 Prescaled CLK_DAC cycles."),
                    value: 3,
                },
                EnumVariant {
                    name: "Cycles2",
                    description: Some("The Timer overflows every 2 Prescaled CLK_DAC cycles."),
                    value: 0,
                },
                EnumVariant {
                    name: "Cycles32",
                    description: Some("The Timer overflows every 32 Prescaled CLK_DAC cycles."),
                    value: 4,
                },
                EnumVariant {
                    name: "Cycles4",
                    description: Some("The Timer overflows every 4 Prescaled CLK_DAC cycles."),
                    value: 1,
                },
                EnumVariant {
                    name: "Cycles64",
                    description: Some("The Timer overflows every 64 Prescaled CLK_DAC cycles."),
                    value: 5,
                },
                EnumVariant {
                    name: "Cycles8",
                    description: Some("The Timer overflows every 8 Prescaled CLK_DAC cycles."),
                    value: 2,
                },
            ],
        },
    ],
};
