use crate::metadata::ir::*;

pub static REGISTERS: IR = IR {
    blocks: &[Block {
        name: "Wdog",
        extends: None,
        description: Some("WDOG peripheral."),
        items: &[
            BlockItem {
                name: "ipversion",
                description: Some("No Description."),
                array: None,
                byte_offset: 0,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Ipversion"),
                }),
            },
            BlockItem {
                name: "en",
                description: Some("No Description."),
                array: None,
                byte_offset: 4,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "cfg",
                description: Some("No Description."),
                array: None,
                byte_offset: 8,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cmd",
                description: Some("No Description."),
                array: None,
                byte_offset: 12,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "status",
                description: Some("No Description."),
                array: None,
                byte_offset: 20,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Status"),
                }),
            },
            BlockItem {
                name: "if_",
                description: Some("No Description."),
                array: None,
                byte_offset: 24,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien",
                description: Some("No Description."),
                array: None,
                byte_offset: 28,
                inner: BlockItemInner::Register(Register {
                    access: Access::ReadWrite,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "lock",
                description: Some("No Description."),
                array: None,
                byte_offset: 32,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "syncbusy",
                description: Some("No Description."),
                array: None,
                byte_offset: 36,
                inner: BlockItemInner::Register(Register {
                    access: Access::Read,
                    bit_size: 32,
                    fieldset: Some("Syncbusy"),
                }),
            },
            BlockItem {
                name: "en_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4100,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8196,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "en_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12292,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("En"),
                }),
            },
            BlockItem {
                name: "cfg_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4104,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8200,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cfg_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12296,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cfg"),
                }),
            },
            BlockItem {
                name: "cmd_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4108,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8204,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "cmd_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12300,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Cmd"),
                }),
            },
            BlockItem {
                name: "if_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4120,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8216,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "if_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12312,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("If"),
                }),
            },
            BlockItem {
                name: "ien_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4124,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8220,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "ien_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12316,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Ien"),
                }),
            },
            BlockItem {
                name: "lock_set",
                description: Some("No Description. (write-1-to-set alias)"),
                array: None,
                byte_offset: 4128,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_clr",
                description: Some("No Description. (write-1-to-clr alias)"),
                array: None,
                byte_offset: 8224,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
            BlockItem {
                name: "lock_tgl",
                description: Some("No Description. (write-1-to-tgl alias)"),
                array: None,
                byte_offset: 12320,
                inner: BlockItemInner::Register(Register {
                    access: Access::Write,
                    bit_size: 32,
                    fieldset: Some("Lock"),
                }),
            },
        ],
    }],
    fieldsets: &[
        FieldSet {
            name: "Cfg",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "clrsrc",
                    description: Some("WDOG Clear Source."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: Some("Clrsrc"),
                },
                Field {
                    name: "em2run",
                    description: Some("EM2 Run."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "em3run",
                    description: Some("EM3 Run."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "em4block",
                    description: Some("EM4 Block."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "debugrun",
                    description: Some("Debug Mode Run."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "wdogrstdis",
                    description: Some("WDOG Reset Disable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 8 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prs0missrsten",
                    description: Some("PRS Src0 Missing Event WDOG Reset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 9 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "prs1missrsten",
                    description: Some("PRS Src1 Missing Event WDOG Reset."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 10 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "persel",
                    description: Some("WDOG Timeout Period Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 16 }),
                    bit_size: 4,
                    array: None,
                    enumm: Some("Persel"),
                },
                Field {
                    name: "warnsel",
                    description: Some("WDOG Warning Period Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 24 }),
                    bit_size: 2,
                    array: None,
                    enumm: Some("Warnsel"),
                },
                Field {
                    name: "winsel",
                    description: Some("WDOG Illegal Window Select."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 28 }),
                    bit_size: 3,
                    array: None,
                    enumm: Some("Winsel"),
                },
            ],
        },
        FieldSet {
            name: "Cmd",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "clear",
                description: Some("WDOG Timer Clear."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: Some("Clear"),
            }],
        },
        FieldSet {
            name: "En",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "en",
                description: Some("Module Enable."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Ien",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "tout",
                    description: Some("WDOG Timeout Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "warn",
                    description: Some("WDOG Warning Timeout Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "win",
                    description: Some("WDOG Window Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pem0",
                    description: Some("PRS Src0 Event Missing Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pem1",
                    description: Some("PRS Src1 Event Missing Interrupt Enable."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "If",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[
                Field {
                    name: "tout",
                    description: Some("WDOG Timeout Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "warn",
                    description: Some("WDOG Warning Timeout Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 1 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "win",
                    description: Some("WDOG Window Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 2 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pem0",
                    description: Some("PRS Src0 Event Missing Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 3 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
                Field {
                    name: "pem1",
                    description: Some("PRS Src1 Event Missing Interrupt Flag."),
                    bit_offset: BitOffset::Regular(RegularBitOffset { offset: 4 }),
                    bit_size: 1,
                    array: None,
                    enumm: None,
                },
            ],
        },
        FieldSet {
            name: "Ipversion",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "ipversion",
                description: Some("IP Version."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 32,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Lock",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lockkey",
                description: Some("WDOG Configuration Lock."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 16,
                array: None,
                enumm: Some("Lockkey"),
            }],
        },
        FieldSet {
            name: "Status",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "lock",
                description: Some("WDOG Configuration Lock Status."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 31 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
        FieldSet {
            name: "Syncbusy",
            extends: None,
            description: Some("No Description."),
            bit_size: 32,
            fields: &[Field {
                name: "cmd",
                description: Some("Sync Busy for Cmd Register."),
                bit_offset: BitOffset::Regular(RegularBitOffset { offset: 0 }),
                bit_size: 1,
                array: None,
                enumm: None,
            }],
        },
    ],
    enums: &[
        Enum {
            name: "Clear",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Cleared",
                    description: Some("WDOG timer is cleared to 0."),
                    value: 1,
                },
                EnumVariant {
                    name: "Unchanged",
                    description: Some("WDOG timer is unchanged."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Clrsrc",
            description: None,
            bit_size: 1,
            variants: &[
                EnumVariant {
                    name: "Prssrc0",
                    description: Some("A rising edge on the PRS Source 0 will clear the WDOG counter."),
                    value: 1,
                },
                EnumVariant {
                    name: "Sw",
                    description: Some("A write to the clear bit will clear the WDOG counter."),
                    value: 0,
                },
            ],
        },
        Enum {
            name: "Lockkey",
            description: None,
            bit_size: 16,
            variants: &[
                EnumVariant {
                    name: "Lock",
                    description: Some("Lock WDOG lockable registers."),
                    value: 0,
                },
                EnumVariant {
                    name: "Unlock",
                    description: Some("Unlock WDOG lockable registers."),
                    value: 44008,
                },
            ],
        },
        Enum {
            name: "Persel",
            description: None,
            bit_size: 4,
            variants: &[
                EnumVariant {
                    name: "Sel0",
                    description: Some("Timeout period of 9 wdog cycles."),
                    value: 0,
                },
                EnumVariant {
                    name: "Sel1",
                    description: Some("Timeout period of 17 wdog cycles."),
                    value: 1,
                },
                EnumVariant {
                    name: "Sel10",
                    description: Some("Timeout period of 8k wdog cycles."),
                    value: 10,
                },
                EnumVariant {
                    name: "Sel11",
                    description: Some("Timeout period of 16k wdog cycles."),
                    value: 11,
                },
                EnumVariant {
                    name: "Sel12",
                    description: Some("Timeout period of 32k wdog cycles."),
                    value: 12,
                },
                EnumVariant {
                    name: "Sel13",
                    description: Some("Timeout period of 64k wdog cycles."),
                    value: 13,
                },
                EnumVariant {
                    name: "Sel14",
                    description: Some("Timeout period of 128k wdog cycles."),
                    value: 14,
                },
                EnumVariant {
                    name: "Sel15",
                    description: Some("Timeout period of 256k wdog cycles."),
                    value: 15,
                },
                EnumVariant {
                    name: "Sel2",
                    description: Some("Timeout period of 33 wdog cycles."),
                    value: 2,
                },
                EnumVariant {
                    name: "Sel3",
                    description: Some("Timeout period of 65 wdog cycles."),
                    value: 3,
                },
                EnumVariant {
                    name: "Sel4",
                    description: Some("Timeout period of 129 wdog cycles."),
                    value: 4,
                },
                EnumVariant {
                    name: "Sel5",
                    description: Some("Timeout period of 257 wdog cycles."),
                    value: 5,
                },
                EnumVariant {
                    name: "Sel6",
                    description: Some("Timeout period of 513 wdog cycles."),
                    value: 6,
                },
                EnumVariant {
                    name: "Sel7",
                    description: Some("Timeout period of 1k wdog cycles."),
                    value: 7,
                },
                EnumVariant {
                    name: "Sel8",
                    description: Some("Timeout period of 2k wdog cycles."),
                    value: 8,
                },
                EnumVariant {
                    name: "Sel9",
                    description: Some("Timeout period of 4k wdog cycles."),
                    value: 9,
                },
            ],
        },
        Enum {
            name: "Warnsel",
            description: None,
            bit_size: 2,
            variants: &[
                EnumVariant {
                    name: "Dis",
                    description: Some("Disable."),
                    value: 0,
                },
                EnumVariant {
                    name: "Sel1",
                    description: Some("Warning timeout is 25% of the Timeout."),
                    value: 1,
                },
                EnumVariant {
                    name: "Sel2",
                    description: Some("Warning timeout is 50% of the Timeout."),
                    value: 2,
                },
                EnumVariant {
                    name: "Sel3",
                    description: Some("Warning timeout is 75% of the Timeout."),
                    value: 3,
                },
            ],
        },
        Enum {
            name: "Winsel",
            description: None,
            bit_size: 3,
            variants: &[
                EnumVariant {
                    name: "Dis",
                    description: Some("Disabled."),
                    value: 0,
                },
                EnumVariant {
                    name: "Sel1",
                    description: Some("Window timeout is 12.5% of the Timeout."),
                    value: 1,
                },
                EnumVariant {
                    name: "Sel2",
                    description: Some("Window timeout is 25% of the Timeout."),
                    value: 2,
                },
                EnumVariant {
                    name: "Sel3",
                    description: Some("Window timeout is 37.5% of the Timeout."),
                    value: 3,
                },
                EnumVariant {
                    name: "Sel4",
                    description: Some("Window timeout is 50% of the Timeout."),
                    value: 4,
                },
                EnumVariant {
                    name: "Sel5",
                    description: Some("Window timeout is 62.5% of the Timeout."),
                    value: 5,
                },
                EnumVariant {
                    name: "Sel6",
                    description: Some("Window timeout is 75.5% of the Timeout."),
                    value: 6,
                },
                EnumVariant {
                    name: "Sel7",
                    description: Some("Window timeout is 87.5% of the Timeout."),
                    value: 7,
                },
            ],
        },
    ],
};
